-- Run inside a transaction after the migration, then ROLLBACK. No real accounts used.
create function pg_temp.family_ids() returns uuid[] language sql as $$ select array_agg(gen_random_uuid()) from generate_series(1,8); $$;
create function pg_temp.assert_family(ok boolean,label text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception 'ASSERTION FAILED: %',label; end if; end $$;
do $$
declare
 a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid();
 ap uuid:=gen_random_uuid(); bp uuid:=gen_random_uuid(); op uuid:=gen_random_uuid();
 w uuid; w2 uuid; r jsonb; snapshot jsonb; ids uuid[]; cmd uuid; list_id uuid; task_id uuid; child_id uuid;
 invite_id uuid; token text:=repeat('a',64); denied boolean; version int;
begin
 insert into identity.identities(person_ref,auth_user_id,full_name) values(ap,a,'Test owner'),(bp,b,'Test member'),(op,outsider,'Test outsider');
 perform pg_temp.assert_family(not has_table_privilege('authenticated','family.tasks','SELECT'),'no direct authenticated table access');
 perform pg_temp.assert_family(not has_function_privilege('anon','api.family_snapshot(uuid)','EXECUTE'),'anon cannot read');
 perform pg_temp.assert_family(not has_function_privilege('anon','api.family_command(uuid,uuid,text,jsonb,uuid[])','EXECUTE'),'anon cannot write');
 execute 'set local role authenticated';
 perform set_config('request.jwt.claim.sub',a::text,true);
 ids:=pg_temp.family_ids(); cmd:=gen_random_uuid();
 r:=api.family_command(cmd,null,'create','{"name":"Test family","displayName":"Test owner"}',ids); w:=(r->>'workspaceId')::uuid;
 perform pg_temp.assert_family((api.family_snapshot(w)->>'canManage')::boolean,'owner can manage');
 perform pg_temp.assert_family(api.family_command(cmd,null,'create','{"name":"Test family","displayName":"Test owner"}',ids)=r,'idempotent creation');
 r:=api.family_command(gen_random_uuid(),w,'person','{"name":"Child","kind":"child"}',pg_temp.family_ids());child_id:=(r->>'id')::uuid;
 r:=api.family_command(gen_random_uuid(),w,'list','{"name":"Groceries"}',pg_temp.family_ids());list_id:=(r->>'id')::uuid;
 r:=api.family_command(gen_random_uuid(),w,'task',jsonb_build_object('title','Milk','listId',list_id,'assigneeId',child_id),pg_temp.family_ids());task_id:=(r->>'id')::uuid;
 perform api.family_command(gen_random_uuid(),w,'complete',jsonb_build_object('id',task_id,'version',1,'today','2026-09-29'),pg_temp.family_ids());
 perform pg_temp.assert_family((api.family_snapshot(w)->'tasks'->0->>'completed_at') is not null,'list item completed');
 perform api.family_command(gen_random_uuid(),w,'complete',jsonb_build_object('id',task_id,'version',2,'today','2026-09-29'),pg_temp.family_ids());
 perform pg_temp.assert_family((api.family_snapshot(w)->'tasks'->0->>'completed_at') is null,'list item reopened');
 r:=api.family_command(gen_random_uuid(),w,'task','{"title":"Water plants","dueOn":"2026-09-20","repeatDays":7}',pg_temp.family_ids());task_id:=(r->>'id')::uuid;
 ids:=pg_temp.family_ids();cmd:=gen_random_uuid();
 r:=api.family_command(cmd,w,'complete',jsonb_build_object('id',task_id,'version',1,'today','2026-09-29'),ids);
 perform pg_temp.assert_family(api.family_command(cmd,w,'complete',jsonb_build_object('id',task_id,'version',1,'today','2026-09-29'),ids)=r,'retry does not advance recurring task twice');
 select (v->>'version')::int into version from jsonb_array_elements(api.family_snapshot(w)->'tasks') v where v->>'id'=task_id::text;
 perform pg_temp.assert_family(version=2,'recurring version advances once');
 perform pg_temp.assert_family(exists(select 1 from jsonb_array_elements(api.family_snapshot(w)->'tasks') v where v->>'id'=task_id::text and v->>'due_on'='2026-10-06'),'recurrence uses completion date');
 denied:=false;begin perform api.family_command(gen_random_uuid(),w,'complete',jsonb_build_object('id',task_id,'version',1,'today','2026-09-29'),pg_temp.family_ids());exception when others then denied:=sqlerrm='family_conflict';end;
 perform pg_temp.assert_family(denied,'stale task completion rejected');
 perform api.family_command(gen_random_uuid(),w,'event','{"title":"Holiday","startsOn":"2026-12-28","endsOn":"2027-01-04","kind":"holiday"}',pg_temp.family_ids());
 perform pg_temp.assert_family(jsonb_array_length(api.family_snapshot(w)->'events')=1,'holiday persists across years');
 r:=api.family_command(gen_random_uuid(),w,'invite',jsonb_build_object('token',token),pg_temp.family_ids());invite_id:=(r->>'id')::uuid;
 perform pg_temp.assert_family((api.family_snapshot(w)->'invitations'->0) ? 'token_hash'=false,'invite hash not exposed');
 perform set_config('request.jwt.claim.sub',outsider::text,true);
 denied:=false;begin perform api.family_snapshot(w);exception when insufficient_privilege then denied:=true;end;
 perform pg_temp.assert_family(denied,'outsider cannot read family');
 denied:=false;begin perform api.family_command(gen_random_uuid(),w,'list','{"name":"Attack"}',pg_temp.family_ids());exception when insufficient_privilege then denied:=true;end;
 perform pg_temp.assert_family(denied,'outsider cannot write family');
 r:=api.family_command(gen_random_uuid(),null,'create','{"name":"Separate family","displayName":"Outsider"}',pg_temp.family_ids());w2:=(r->>'workspaceId')::uuid;
 perform set_config('request.jwt.claim.sub',a::text,true);
 denied:=false;begin perform api.family_command(gen_random_uuid(),w2,'task',jsonb_build_object('title','Attack','assigneeId',child_id),pg_temp.family_ids());exception when insufficient_privilege then denied:=true;end;
 perform pg_temp.assert_family(denied,'cross-family mutation rejected');
 -- A second family owned by the same caller still cannot reference the first family's people/lists.
 r:=api.family_command(gen_random_uuid(),null,'create','{"name":"Owner second family","displayName":"Test owner"}',pg_temp.family_ids());w2:=(r->>'workspaceId')::uuid;
 denied:=false;begin perform api.family_command(gen_random_uuid(),w2,'task',jsonb_build_object('title','Wrong assignee','assigneeId',child_id),pg_temp.family_ids());exception when others then denied:=sqlerrm='family_invalid_input';end;
 perform pg_temp.assert_family(denied,'cross-family assignee rejected even when caller owns both');
 denied:=false;begin perform api.family_command(gen_random_uuid(),w2,'task',jsonb_build_object('title','Wrong list','listId',list_id),pg_temp.family_ids());exception when others then denied:=sqlerrm='family_invalid_input';end;
 perform pg_temp.assert_family(denied,'cross-family list rejected even when caller owns both');
 denied:=false;begin perform api.family_command(gen_random_uuid(),w,'event','{"title":"Invalid","startsOn":"2027-01-04","endsOn":"2026-12-28","kind":"holiday"}',pg_temp.family_ids());exception when check_violation then denied:=true;end;
 perform pg_temp.assert_family(denied,'end date cannot precede start date');
 perform set_config('request.jwt.claim.sub',b::text,true);
 r:=api.family_command(gen_random_uuid(),null,'join',jsonb_build_object('token',token,'displayName','Test member'),pg_temp.family_ids());
 snapshot:=api.family_snapshot(w);
 perform pg_temp.assert_family(not (snapshot->>'canManage')::boolean,'invited adult not an organiser');
 perform pg_temp.assert_family(jsonb_array_length(snapshot->'tasks')=2,'member can read shared tasks');
 perform api.family_command(gen_random_uuid(),w,'list','{"name":"Packing"}',pg_temp.family_ids());
 denied:=false;begin perform api.family_command(gen_random_uuid(),w,'invite',jsonb_build_object('token',repeat('b',64)),pg_temp.family_ids());exception when insufficient_privilege then denied:=true;end;
 perform pg_temp.assert_family(denied,'ordinary member cannot invite');
 perform set_config('request.jwt.claim.sub',outsider::text,true);
 denied:=false;begin perform api.family_command(gen_random_uuid(),null,'join',jsonb_build_object('token',token,'displayName','Outsider'),pg_temp.family_ids());exception when others then denied:=sqlerrm='family_invalid_invite';end;
 perform pg_temp.assert_family(denied,'invitation is single use');
 perform set_config('request.jwt.claim.sub',a::text,true);
 select (v->>'id')::uuid into child_id from jsonb_array_elements(api.family_snapshot(w)->'people') v where v->>'name'='Test member';
 perform api.family_command(gen_random_uuid(),w,'remove_person',jsonb_build_object('id',child_id),pg_temp.family_ids());
 perform set_config('request.jwt.claim.sub',b::text,true);
 denied:=false;begin perform api.family_snapshot(w);exception when insufficient_privilege then denied:=true;end;
 perform pg_temp.assert_family(denied,'removed member loses access immediately');
 perform set_config('request.jwt.claim.sub',a::text,true);
 r:=api.family_command(gen_random_uuid(),w,'invite',jsonb_build_object('token',repeat('b',64)),pg_temp.family_ids());
 perform api.family_command(gen_random_uuid(),w,'revoke_invite',jsonb_build_object('id',r->>'id'),pg_temp.family_ids());
 perform set_config('request.jwt.claim.sub',b::text,true);
 denied:=false;begin perform api.family_command(gen_random_uuid(),null,'join',jsonb_build_object('token',repeat('b',64),'displayName','Test member'),pg_temp.family_ids());exception when others then denied:=sqlerrm='family_invalid_invite';end;
 perform pg_temp.assert_family(denied,'revoked invitation cannot be used');
 perform set_config('request.jwt.claim.sub',a::text,true);
 r:=api.family_command(gen_random_uuid(),w,'invite',jsonb_build_object('token',repeat('c',64)),pg_temp.family_ids());
 execute 'reset role';
 update family.invitations set expires_at=now()-interval '1 second' where id=(r->>'id')::uuid;
 execute 'set local role authenticated';
 perform set_config('request.jwt.claim.sub',b::text,true);
 denied:=false;begin perform api.family_command(gen_random_uuid(),null,'join',jsonb_build_object('token',repeat('c',64),'displayName','Test member'),pg_temp.family_ids());exception when others then denied:=sqlerrm='family_invalid_invite';end;
 perform pg_temp.assert_family(denied,'expired invitation cannot be used');
 execute 'reset role';
end $$;
select 'Family database contracts passed' as result;
