// Copy lives outside the components so every family screen uses the selected locale.
const en = {
 title:'Family', tagline:'A little less to remember. More life together.', back:'Back to Klussie',
 today:'Today', lists:'Lists', chores:'Chores', calendar:'Calendar', people:'People', navChores:'Chores', navPeople:'People',
 create:'Create a family', join:'Join a family', name:'Name', yourName:'Your name', familyName:'Family name',
 welcome:'Make room for everyday life', intro:'Keep shared lists, chores and plans together in a private family space.',
 createHint:'Start with a name. Invite other adults when you are ready.',
 joinHint:'Paste the single-use invitation code shared with you. Joining shares family lists and plans, not personal home records.',
 code:'Invitation code', save:'Save', cancel:'Cancel', close:'Close', add:'Add', edit:'Edit', archive:'Archive',
 loading:'Loading your family…', loadFailed:'Your family could not be refreshed. Try again.', retry:'Try again',
 saveFailed:'Could not save this change. Your entries are still here. Try again.',
 conflict:'Someone changed this record. Close this form, refresh and try again.',
 invalidInvite:'This invitation is invalid, expired or already used.', alreadyMember:'You already belong to this family.',
 due:'Due date', assignee:'Who is handling this?', anyone:'Anyone', repeat:'Repeat after completion',
 once:'Does not repeat', daily:'Every day', weekly:'Every 7 days', fortnightly:'Every 14 days', monthly:'Every 30 days',
 taskTitle:'What needs doing?', addChore:'Add a chore', addList:'New list', addItem:'Add an item',
 listName:'List name', emptyLists:'Groceries, errands, packing. Start with one useful list.', emptyChores:'Share the work, one small chore at a time.',
 emptyTasks:'Nothing on this list yet.', done:'Done', reopen:'Reopen', completed:'Completed', upcoming:'Coming up', overdue:'Overdue',
 todayEmpty:'Nothing due today. A little breathing room.', todayHint:'The things that need you, all in one place.',
 addEvent:'Add a plan', eventTitle:'What is happening?', start:'First day', end:'Last day', event:'Plan', holiday:'Holiday',
 eventKind:'Type', notes:'Notes', allDay:'All-day plans', emptyEvents:'Make space for a holiday, school break or a day together.',
 previous:'Previous month', next:'Next month', addPerson:'Add a household member', personName:'Display name',
 adult:'Adult', child:'Child', owner:'Family organiser', member:'Family member', noLogin:'Managed profile · no login',
 personHint:'A managed profile can be assigned chores but cannot sign in. Invite an adult separately to give them access.',
 invite:'Invite an adult', inviteHint:'This code can be used once within 7 days. Share it only with the person you want to invite.',
 inviteCode:'Your invitation code', pendingInvites:'Open invitations', expires:'Expires', revoke:'Revoke', remove:'Remove member',
 removeHint:'Their family access will end and their chores will become unassigned.', confirm:'Confirm',
 privacy:'Your family space is separate from your homes and professional work.', refresh:'Refresh',
 budgetLater:'Shared budgets and holiday savings are next. This release focuses on everyday coordination.',
 newFamily:'New family', all:'All', mine:'Assigned to me', noMatches:'Nothing in this view.',
};
const nl = {
 title:'Familie', tagline:'Minder onthouden. Meer samen leven.', back:'Terug naar Klussie',
 today:'Vandaag', lists:'Lijstjes', chores:'Huishoudtaken', calendar:'Kalender', people:'Gezinsleden', navChores:'Taken', navPeople:'Leden',
 create:'Gezin aanmaken', join:'Aansluiten bij een gezin', name:'Naam', yourName:'Jouw naam', familyName:'Gezinsnaam',
 welcome:'Ruimte voor het dagelijks leven', intro:'Bewaar gedeelde lijstjes, huishoudtaken en plannen in een eigen gezinsruimte.',
 createHint:'Begin met een naam. Nodig andere volwassenen uit wanneer je wilt.',
 joinHint:'Plak de eenmalige uitnodigingscode die je kreeg. Je deelt gezinslijstjes en plannen, geen persoonlijke woninggegevens.',
 code:'Uitnodigingscode', save:'Opslaan', cancel:'Annuleren', close:'Sluiten', add:'Toevoegen', edit:'Bewerken', archive:'Archiveren',
 loading:'Je gezin laden…', loadFailed:'Je gezin kon niet worden vernieuwd. Probeer het opnieuw.', retry:'Opnieuw proberen',
 saveFailed:'Opslaan is niet gelukt. Je invoer is bewaard. Probeer het opnieuw.',
 conflict:'Iemand heeft dit gewijzigd. Sluit dit formulier, vernieuw en probeer opnieuw.',
 invalidInvite:'Deze uitnodiging is ongeldig, verlopen of al gebruikt.', alreadyMember:'Je bent al lid van dit gezin.',
 due:'Uiterste datum', assignee:'Wie doet dit?', anyone:'Iedereen', repeat:'Herhalen na afronden',
 once:'Niet herhalen', daily:'Elke dag', weekly:'Elke 7 dagen', fortnightly:'Elke 14 dagen', monthly:'Elke 30 dagen',
 taskTitle:'Wat moet er gebeuren?', addChore:'Huishoudtaak toevoegen', addList:'Nieuw lijstje', addItem:'Item toevoegen',
 listName:'Naam van het lijstje', emptyLists:'Boodschappen, klusjes, inpakken. Begin met één handig lijstje.', emptyChores:'Verdeel het werk, één taak tegelijk.',
 emptyTasks:'Dit lijstje is nog leeg.', done:'Klaar', reopen:'Heropenen', completed:'Afgerond', upcoming:'Binnenkort', overdue:'Te laat',
 todayEmpty:'Niets te doen voor vandaag. Even ademruimte.', todayHint:'Wat je aandacht vraagt, op één plek.',
 addEvent:'Plan toevoegen', eventTitle:'Wat staat er gepland?', start:'Eerste dag', end:'Laatste dag', event:'Plan', holiday:'Vakantie',
 eventKind:'Type', notes:'Notities', allDay:'Plannen voor hele dagen', emptyEvents:'Plan een vakantie, schoolvakantie of een dag samen.',
 previous:'Vorige maand', next:'Volgende maand', addPerson:'Gezinslid toevoegen', personName:'Weergavenaam',
 adult:'Volwassene', child:'Kind', owner:'Gezinsbeheerder', member:'Gezinslid', noLogin:'Beheerd profiel · geen login',
 personHint:'Een beheerd profiel kan taken krijgen maar niet inloggen. Nodig een volwassene apart uit om toegang te geven.',
 invite:'Volwassene uitnodigen', inviteHint:'Deze code is één keer bruikbaar binnen 7 dagen. Deel hem alleen met de persoon die je wilt uitnodigen.',
 inviteCode:'Jouw uitnodigingscode', pendingInvites:'Open uitnodigingen', expires:'Verloopt', revoke:'Intrekken', remove:'Lid verwijderen',
 removeHint:'De toegang tot het gezin stopt en de taken worden niet meer toegewezen.', confirm:'Bevestigen',
 privacy:'Je gezinsruimte staat los van je woningen en je professionele werk.', refresh:'Vernieuwen',
 budgetLater:'Gezinsbudgetten en sparen voor vakantie volgen later. Deze versie helpt met de dagelijkse organisatie.',
 newFamily:'Nieuw gezin', all:'Alles', mine:'Voor mij', noMatches:'Niets in deze weergave.',
};
export const FAMILY_STRINGS = { en, nl };
export function familyStrings(locale) { return FAMILY_STRINGS[locale] || en; }
