// Copy lives outside the components so every family screen uses the selected locale.
const en = {
 title:'Family', tagline:'A little less to remember. More life together.', back:'Back to Klussie',
 today:'Today', lists:'Lists', chores:'Chores', calendar:'Calendar', people:'People', navChores:'Chores', navPeople:'People',
 create:'Create a family', join:'Join a family', name:'Name', yourName:'Your name', familyName:'Family name',
 welcome:'Make room for everyday life', intro:'Keep shared lists, chores and plans together in a private family space.',
 createHint:'Start with a name. Invite other adults when you are ready.',
 joinHint:'Paste the single-use invitation code shared with you. Joining shares family lists and plans, not personal home records.',
 code:'Invitation code', save:'Save', cancel:'Cancel', close:'Close', add:'Add', edit:'Edit', archive:'Archive',
 loading:'Loading your family…', loadFailed:'Your family could not be refreshed. Try again.', retry:'Try again',
 saveFailed:'Could not save this change. Your entries are still here. Try again.',
 conflict:'Someone changed this record. Close this form, refresh and try again.',
 invalidInvite:'This invitation is invalid, expired or already used.', alreadyMember:'You already belong to this family.',
 due:'Due date', assignee:'Who is handling this?', anyone:'Anyone', repeat:'Repeat after completion',
 once:'Does not repeat', daily:'Every day', weekly:'Every 7 days', fortnightly:'Every 14 days', monthly:'Every 30 days',
 taskTitle:'What needs doing?', addChore:'Add a chore', addList:'New list', addItem:'Add an item',
 listName:'List name', emptyLists:'Groceries, errands, packing. Start with one useful list.', emptyChores:'Share the work, one small chore at a time.',
 emptyTasks:'Nothing on this list yet.', done:'Done', reopen:'Reopen', completed:'Completed', upcoming:'Coming up', overdue:'Overdue',
 todayEmpty:'Nothing due today. A little breathing room.', todayHint:'The things that need you, all in one place.',
 addEvent:'Add a plan', eventTitle:'What is happening?', start:'First day', end:'Last day', event:'Plan', holiday:'Holiday',
 eventKind:'Type', notes:'Notes', allDay:'All-day plans', emptyEvents:'Make space for a holiday, school break or a day together.',
 previous:'Previous month', next:'Next month', addPerson:'Add a household member', personName:'Display name',
 adult:'Adult', child:'Child', owner:'Family organiser', member:'Family member', noLogin:'Managed profile · no login',
 personHint:'A managed profile can be assigned chores but cannot sign in. Invite an adult separately to give them access.',
 invite:'Invite an adult', inviteHint:'This code can be used once within 7 days. Share it only with the person you want to invite.',
 inviteCode:'Your invitation code', pendingInvites:'Open invitations', expires:'Expires', revoke:'Revoke', remove:'Remove member',
 removeHint:'Their family access will end and their chores will become unassigned.', confirm:'Confirm',
 privacy:'Your family space is separate from your homes and professional work.', refresh:'Refresh',
 budgetLater:'Shared budgets and holiday savings are next. This release focuses on everyday coordination.',
 newFamily:'New family', all:'All', mine:'Assigned to me', noMatches:'Nothing in this view.',
};
const nl = {
 title:'Familie', tagline:'Minder onthouden. Meer samen leven.', back:'Terug naar Klussie',
 today:'Vandaag', lists:'Lijstjes', chores:'Huishoudtaken', calendar:'Kalender', people:'Gezinsleden', navChores:'Taken', navPeople:'Leden',
 create:'Gezin aanmaken', join:'Aansluiten bij een gezin', name:'Naam', yourName:'Jouw naam', familyName:'Gezinsnaam',
 welcome:'Ruimte voor het dagelijks leven', intro:'Bewaar gedeelde lijstjes, huishoudtaken en plannen in een eigen gezinsruimte.',
 createHint:'Begin met een naam. Nodig andere volwassenen uit wanneer je wilt.',
 joinHint:'Plak de eenmalige uitnodigingscode die je kreeg. Je deelt gezinslijstjes en plannen, geen persoonlijke woninggegevens.',
 code:'Uitnodigingscode', save:'Opslaan', cancel:'Annuleren', close:'Sluiten', add:'Toevoegen', edit:'Bewerken', archive:'Archiveren',
 loading:'Je gezin laden…', loadFailed:'Je gezin kon niet worden vernieuwd. Probeer het opnieuw.', retry:'Opnieuw proberen',
 saveFailed:'Opslaan is niet gelukt. Je invoer is bewaard. Probeer het opnieuw.',
 conflict:'Iemand heeft dit gewijzigd. Sluit dit formulier, vernieuw en probeer opnieuw.',
 invalidInvite:'Deze uitnodiging is ongeldig, verlopen of al gebruikt.', alreadyMember:'Je bent al lid van dit gezin.',
 due:'Uiterste datum', assignee:'Wie doet dit?', anyone:'Iedereen', repeat:'Herhalen na afronden',
 once:'Niet herhalen', daily:'Elke dag', weekly:'Elke 7 dagen', fortnightly:'Elke 14 dagen', monthly:'Elke 30 dagen',
 taskTitle:'Wat moet er gebeuren?', addChore:'Huishoudtaak toevoegen', addList:'Nieuw lijstje', addItem:'Item toevoegen',
 listName:'Naam van het lijstje', emptyLists:'Boodschappen, klusjes, inpakken. Begin met één handig lijstje.', emptyChores:'Verdeel het werk, één taak tegelijk.',
 emptyTasks:'Dit lijstje is nog leeg.', done:'Klaar', reopen:'Heropenen', completed:'Afgerond', upcoming:'Binnenkort', overdue:'Te laat',
 todayEmpty:'Niets te doen voor vandaag. Even ademruimte.', todayHint:'Wat je aandacht vraagt, op één plek.',
 addEvent:'Plan toevoegen', eventTitle:'Wat staat er gepland?', start:'Eerste dag', end:'Laatste dag', event:'Plan', holiday:'Vakantie',
 eventKind:'Type', notes:'Notities', allDay:'Plannen voor hele dagen', emptyEvents:'Plan een vakantie, schoolvakantie of een dag samen.',
 previous:'Vorige maand', next:'Volgende maand', addPerson:'Gezinslid toevoegen', personName:'Weergavenaam',
 adult:'Volwassene', child:'Kind', owner:'Gezinsbeheerder', member:'Gezinslid', noLogin:'Beheerd profiel · geen login',
 personHint:'Een beheerd profiel kan taken krijgen maar niet inloggen. Nodig een volwassene apart uit om toegang te geven.',
 invite:'Volwassene uitnodigen', inviteHint:'Deze code is één keer bruikbaar binnen 7 dagen. Deel hem alleen met de persoon die je wilt uitnodigen.',
 inviteCode:'Jouw uitnodigingscode', pendingInvites:'Open uitnodigingen', expires:'Verloopt', revoke:'Intrekken', remove:'Lid verwijderen',
 removeHint:'De toegang tot het gezin stopt en de taken worden niet meer toegewezen.', confirm:'Bevestigen',
 privacy:'Je gezinsruimte staat los van je woningen en je professionele werk.', refresh:'Vernieuwen',
 budgetLater:'Gezinsbudgetten en sparen voor vakantie volgen later. Deze versie helpt met de dagelijkse organisatie.',
 newFamily:'Nieuw gezin', all:'Alles', mine:'Voor mij', noMatches:'Niets in deze weergave.',
};
const fr = {
 title:'Famille', tagline:'Moins à retenir. Plus de vie ensemble.', back:'Retour à Klussie',
 today:'Aujourd\'hui', lists:'Listes', chores:'Tâches', calendar:'Calendrier', people:'Membres', navChores:'Tâches', navPeople:'Membres',
 create:'Créer une famille', join:'Rejoindre une famille', name:'Nom', yourName:'Ton nom', familyName:'Nom de la famille',
 welcome:'Fais de la place pour la vie quotidienne', intro:'Garde des listes, tâches et plans partagés dans un espace familial privé.',
 createHint:'Commence par un nom. Invite d\'autres adultes quand tu es prêt.',
 joinHint:'Colle le code d\'invitation à usage unique que tu as reçu. Rejoindre partage les listes et plans familiaux, pas les données de ton logement.',
 code:'Code d\'invitation', save:'Enregistrer', cancel:'Annuler', close:'Fermer', add:'Ajouter', edit:'Modifier', archive:'Archiver',
 loading:'Chargement de ta famille…', loadFailed:'Impossible d\'actualiser ta famille. Réessaie.', retry:'Réessayer',
 saveFailed:'Impossible d\'enregistrer ce changement. Tes données sont toujours là. Réessaie.',
 conflict:'Quelqu\'un a modifié cet élément. Ferme ce formulaire, actualise et réessaie.',
 invalidInvite:'Cette invitation est invalide, expirée ou déjà utilisée.', alreadyMember:'Tu fais déjà partie de cette famille.',
 due:'Date d\'échéance', assignee:'Qui s\'en occupe ?', anyone:'N\'importe qui', repeat:'Répéter après réalisation',
 once:'Ne se répète pas', daily:'Chaque jour', weekly:'Tous les 7 jours', fortnightly:'Tous les 14 jours', monthly:'Tous les 30 jours',
 taskTitle:'Que faut-il faire ?', addChore:'Ajouter une tâche', addList:'Nouvelle liste', addItem:'Ajouter un élément',
 listName:'Nom de la liste', emptyLists:'Courses, commissions, bagages. Commence par une liste utile.', emptyChores:'Partage les tâches, une à la fois.',
 emptyTasks:'Cette liste est encore vide.', done:'Terminé', reopen:'Rouvrir', completed:'Terminé', upcoming:'À venir', overdue:'En retard',
 todayEmpty:'Rien à faire aujourd\'hui. Un peu de répit.', todayHint:'Ce qui demande ton attention, au même endroit.',
 addEvent:'Ajouter un plan', eventTitle:'Qu\'est-ce qui se passe ?', start:'Premier jour', end:'Dernier jour', event:'Plan', holiday:'Vacances',
 eventKind:'Type', notes:'Notes', allDay:'Plans sur la journée', emptyEvents:'Fais de la place pour des vacances, un congé scolaire ou une journée ensemble.',
 previous:'Mois précédent', next:'Mois suivant', addPerson:'Ajouter un membre du foyer', personName:'Nom affiché',
 adult:'Adulte', child:'Enfant', owner:'Organisateur familial', member:'Membre de la famille', noLogin:'Profil géré · pas de connexion',
 personHint:'Un profil géré peut recevoir des tâches mais ne peut pas se connecter. Invite un adulte séparément pour lui donner accès.',
 invite:'Inviter un adulte', inviteHint:'Ce code est utilisable une fois dans les 7 jours. Ne le partage qu\'avec la personne que tu veux inviter.',
 inviteCode:'Ton code d\'invitation', pendingInvites:'Invitations en attente', expires:'Expire', revoke:'Révoquer', remove:'Retirer le membre',
 removeHint:'Son accès à la famille prendra fin et ses tâches ne seront plus assignées.', confirm:'Confirmer',
 privacy:'Ton espace familial est séparé de tes logements et de ton activité professionnelle.', refresh:'Actualiser',
 budgetLater:'Les budgets partagés et l\'épargne vacances arrivent bientôt. Cette version se concentre sur l\'organisation quotidienne.',
 newFamily:'Nouvelle famille', all:'Tout', mine:'Assigné à moi', noMatches:'Rien dans cette vue.',
};
const de = {
 title:'Familie', tagline:'Weniger merken. Mehr gemeinsam erleben.', back:'Zurück zu Klussie',
 today:'Heute', lists:'Listen', chores:'Aufgaben', calendar:'Kalender', people:'Mitglieder', navChores:'Aufgaben', navPeople:'Mitglieder',
 create:'Familie erstellen', join:'Familie beitreten', name:'Name', yourName:'Dein Name', familyName:'Familienname',
 welcome:'Platz für den Alltag schaffen', intro:'Bewahre gemeinsame Listen, Aufgaben und Pläne in einem privaten Familienbereich auf.',
 createHint:'Beginne mit einem Namen. Lade später weitere Erwachsene ein.',
 joinHint:'Füge den einmaligen Einladungscode ein, den du erhalten hast. Beim Beitreten werden Familienlisten und -pläne geteilt, keine persönlichen Wohndaten.',
 code:'Einladungscode', save:'Speichern', cancel:'Abbrechen', close:'Schließen', add:'Hinzufügen', edit:'Bearbeiten', archive:'Archivieren',
 loading:'Deine Familie wird geladen…', loadFailed:'Deine Familie konnte nicht aktualisiert werden. Versuche es erneut.', retry:'Erneut versuchen',
 saveFailed:'Diese Änderung konnte nicht gespeichert werden. Deine Eingaben sind noch da. Versuche es erneut.',
 conflict:'Jemand hat diesen Eintrag geändert. Schließe dieses Formular, aktualisiere und versuche es erneut.',
 invalidInvite:'Diese Einladung ist ungültig, abgelaufen oder bereits verwendet.', alreadyMember:'Du gehörst bereits zu dieser Familie.',
 due:'Fälligkeitsdatum', assignee:'Wer übernimmt das?', anyone:'Jeder', repeat:'Nach Erledigung wiederholen',
 once:'Wiederholt sich nicht', daily:'Jeden Tag', weekly:'Alle 7 Tage', fortnightly:'Alle 14 Tage', monthly:'Alle 30 Tage',
 taskTitle:'Was muss erledigt werden?', addChore:'Aufgabe hinzufügen', addList:'Neue Liste', addItem:'Element hinzufügen',
 listName:'Name der Liste', emptyLists:'Einkäufe, Besorgungen, Packen. Beginne mit einer nützlichen Liste.', emptyChores:'Teile die Arbeit, eine kleine Aufgabe nach der anderen.',
 emptyTasks:'Diese Liste ist noch leer.', done:'Erledigt', reopen:'Wieder öffnen', completed:'Erledigt', upcoming:'Demnächst', overdue:'Überfällig',
 todayEmpty:'Heute nichts fällig. Etwas Luft zum Atmen.', todayHint:'Was deine Aufmerksamkeit braucht, an einem Ort.',
 addEvent:'Plan hinzufügen', eventTitle:'Was ist los?', start:'Erster Tag', end:'Letzter Tag', event:'Plan', holiday:'Urlaub',
 eventKind:'Typ', notes:'Notizen', allDay:'Ganztägige Pläne', emptyEvents:'Schaffe Platz für Urlaub, Schulferien oder einen gemeinsamen Tag.',
 previous:'Vorheriger Monat', next:'Nächster Monat', addPerson:'Haushaltsmitglied hinzufügen', personName:'Anzeigename',
 adult:'Erwachsener', child:'Kind', owner:'Familienorganisator', member:'Familienmitglied', noLogin:'Verwaltetes Profil · kein Login',
 personHint:'Ein verwaltetes Profil kann Aufgaben erhalten, sich aber nicht anmelden. Lade einen Erwachsenen separat ein, um ihm Zugang zu geben.',
 invite:'Erwachsenen einladen', inviteHint:'Dieser Code ist einmal innerhalb von 7 Tagen nutzbar. Teile ihn nur mit der Person, die du einladen möchtest.',
 inviteCode:'Dein Einladungscode', pendingInvites:'Offene Einladungen', expires:'Läuft ab', revoke:'Widerrufen', remove:'Mitglied entfernen',
 removeHint:'Der Familienzugang endet und die Aufgaben werden nicht mehr zugewiesen.', confirm:'Bestätigen',
 privacy:'Dein Familienbereich ist getrennt von deinen Wohnungen und deiner beruflichen Tätigkeit.', refresh:'Aktualisieren',
 budgetLater:'Gemeinsame Budgets und Urlaubssparen folgen als Nächstes. Diese Version konzentriert sich auf den Alltag.',
 newFamily:'Neue Familie', all:'Alle', mine:'Mir zugewiesen', noMatches:'Nichts in dieser Ansicht.',
};
const es = {
 title:'Familia', tagline:'Menos que recordar. Más vida en común.', back:'Volver a Klussie',
 today:'Hoy', lists:'Listas', chores:'Tareas', calendar:'Calendario', people:'Miembros', navChores:'Tareas', navPeople:'Miembros',
 create:'Crear una familia', join:'Unirse a una familia', name:'Nombre', yourName:'Tu nombre', familyName:'Nombre de la familia',
 welcome:'Haz espacio para la vida diaria', intro:'Guarda listas, tareas y planes compartidos en un espacio familiar privado.',
 createHint:'Empieza con un nombre. Invita a otros adultos cuando quieras.',
 joinHint:'Pega el código de invitación de un solo uso que recibiste. Unirte comparte listas y planes familiares, no los datos de tu vivienda.',
 code:'Código de invitación', save:'Guardar', cancel:'Cancelar', close:'Cerrar', add:'Añadir', edit:'Editar', archive:'Archivar',
 loading:'Cargando tu familia…', loadFailed:'No se pudo actualizar tu familia. Inténtalo de nuevo.', retry:'Reintentar',
 saveFailed:'No se pudo guardar este cambio. Tus datos siguen aquí. Inténtalo de nuevo.',
 conflict:'Alguien cambió este registro. Cierra este formulario, actualiza e inténtalo de nuevo.',
 invalidInvite:'Esta invitación no es válida, caducó o ya se usó.', alreadyMember:'Ya perteneces a esta familia.',
 due:'Fecha límite', assignee:'¿Quién se encarga?', anyone:'Cualquiera', repeat:'Repetir tras completarse',
 once:'No se repite', daily:'Cada día', weekly:'Cada 7 días', fortnightly:'Cada 14 días', monthly:'Cada 30 días',
 taskTitle:'¿Qué hay que hacer?', addChore:'Añadir una tarea', addList:'Nueva lista', addItem:'Añadir un elemento',
 listName:'Nombre de la lista', emptyLists:'Compras, recados, equipaje. Empieza con una lista útil.', emptyChores:'Reparte el trabajo, una tarea a la vez.',
 emptyTasks:'Esta lista está vacía todavía.', done:'Hecho', reopen:'Reabrir', completed:'Completado', upcoming:'Próximamente', overdue:'Atrasado',
 todayEmpty:'Nada pendiente hoy. Un respiro.', todayHint:'Lo que necesita tu atención, en un solo lugar.',
 addEvent:'Añadir un plan', eventTitle:'¿Qué va a pasar?', start:'Primer día', end:'Último día', event:'Plan', holiday:'Vacaciones',
 eventKind:'Tipo', notes:'Notas', allDay:'Planes de todo el día', emptyEvents:'Haz espacio para unas vacaciones, un puente escolar o un día juntos.',
 previous:'Mes anterior', next:'Mes siguiente', addPerson:'Añadir un miembro del hogar', personName:'Nombre visible',
 adult:'Adulto', child:'Niño/a', owner:'Organizador familiar', member:'Miembro de la familia', noLogin:'Perfil gestionado · sin acceso',
 personHint:'Un perfil gestionado puede recibir tareas pero no puede iniciar sesión. Invita a un adulto por separado para darle acceso.',
 invite:'Invitar a un adulto', inviteHint:'Este código se puede usar una vez en 7 días. Compártelo solo con la persona que quieras invitar.',
 inviteCode:'Tu código de invitación', pendingInvites:'Invitaciones pendientes', expires:'Caduca', revoke:'Revocar', remove:'Quitar miembro',
 removeHint:'Su acceso a la familia terminará y sus tareas quedarán sin asignar.', confirm:'Confirmar',
 privacy:'Tu espacio familiar está separado de tus viviendas y tu actividad profesional.', refresh:'Actualizar',
 budgetLater:'Los presupuestos compartidos y el ahorro para vacaciones llegarán después. Esta versión se centra en la organización diaria.',
 newFamily:'Nueva familia', all:'Todo', mine:'Asignado a mí', noMatches:'Nada en esta vista.',
};
const ar = {
 title:'العائلة', tagline:'أقل ما يجب تذكره. المزيد من الحياة معًا.', back:'العودة إلى Klussie',
 today:'اليوم', lists:'القوائم', chores:'المهام', calendar:'التقويم', people:'الأفراد', navChores:'المهام', navPeople:'الأفراد',
 create:'إنشاء عائلة', join:'الانضمام إلى عائلة', name:'الاسم', yourName:'اسمك', familyName:'اسم العائلة',
 welcome:'أفسح مجالاً للحياة اليومية', intro:'احتفظ بالقوائم والمهام والخطط المشتركة في مساحة عائلية خاصة.',
 createHint:'ابدأ باسم. ادعُ بالغين آخرين عندما تكون مستعدًا.',
 joinHint:'الصق رمز الدعوة المخصص للاستخدام مرة واحدة الذي تلقيته. الانضمام يشارك قوائم وخطط العائلة، وليس بيانات منزلك الشخصية.',
 code:'رمز الدعوة', save:'حفظ', cancel:'إلغاء', close:'إغلاق', add:'إضافة', edit:'تعديل', archive:'أرشفة',
 loading:'جارٍ تحميل عائلتك…', loadFailed:'تعذّر تحديث عائلتك. حاول مرة أخرى.', retry:'إعادة المحاولة',
 saveFailed:'تعذّر حفظ هذا التغيير. بياناتك لا تزال هنا. حاول مرة أخرى.',
 conflict:'قام شخص ما بتغيير هذا السجل. أغلق هذا النموذج، حدّث وحاول مرة أخرى.',
 invalidInvite:'هذه الدعوة غير صالحة أو منتهية الصلاحية أو مستخدمة بالفعل.', alreadyMember:'أنت بالفعل عضو في هذه العائلة.',
 due:'تاريخ الاستحقاق', assignee:'من يتولى هذا؟', anyone:'أي شخص', repeat:'تكرار بعد الإنجاز',
 once:'لا يتكرر', daily:'كل يوم', weekly:'كل 7 أيام', fortnightly:'كل 14 يومًا', monthly:'كل 30 يومًا',
 taskTitle:'ما الذي يجب إنجازه؟', addChore:'إضافة مهمة', addList:'قائمة جديدة', addItem:'إضافة عنصر',
 listName:'اسم القائمة', emptyLists:'التسوق، المهام، التحضير للسفر. ابدأ بقائمة مفيدة واحدة.', emptyChores:'شارك العمل، مهمة صغيرة في كل مرة.',
 emptyTasks:'هذه القائمة لا تزال فارغة.', done:'تم', reopen:'إعادة الفتح', completed:'مكتمل', upcoming:'قادم', overdue:'متأخر',
 todayEmpty:'لا يوجد شيء مستحق اليوم. استراحة قصيرة.', todayHint:'كل ما يحتاج انتباهك، في مكان واحد.',
 addEvent:'إضافة خطة', eventTitle:'ما الذي يحدث؟', start:'اليوم الأول', end:'اليوم الأخير', event:'خطة', holiday:'عطلة',
 eventKind:'النوع', notes:'ملاحظات', allDay:'خطط اليوم الكامل', emptyEvents:'أفسح مجالاً لعطلة أو إجازة مدرسية أو يوم معًا.',
 previous:'الشهر السابق', next:'الشهر التالي', addPerson:'إضافة فرد من الأسرة', personName:'الاسم المعروض',
 adult:'بالغ', child:'طفل', owner:'منظّم العائلة', member:'فرد من العائلة', noLogin:'ملف مُدار · بدون تسجيل دخول',
 personHint:'يمكن تكليف الملف المُدار بمهام لكنه لا يستطيع تسجيل الدخول. ادعُ بالغًا بشكل منفصل لمنحه حق الوصول.',
 invite:'دعوة بالغ', inviteHint:'يمكن استخدام هذا الرمز مرة واحدة خلال 7 أيام. شاركه فقط مع الشخص الذي تريد دعوته.',
 inviteCode:'رمز دعوتك', pendingInvites:'الدعوات المعلّقة', expires:'تنتهي الصلاحية', revoke:'إلغاء', remove:'إزالة العضو',
 removeHint:'سينتهي وصوله إلى العائلة وستصبح مهامه غير مُسندة.', confirm:'تأكيد',
 privacy:'مساحة عائلتك منفصلة عن منازلك وعملك المهني.', refresh:'تحديث',
 budgetLater:'الميزانيات المشتركة وادخار العطلات قادمة لاحقًا. يركز هذا الإصدار على التنظيم اليومي.',
 newFamily:'عائلة جديدة', all:'الكل', mine:'المسندة إليّ', noMatches:'لا شيء في هذا العرض.',
};
const fa = {
 title:'خانواده', tagline:'کمتر به یاد بسپار. زندگی بیشتری با هم داشته باش.', back:'بازگشت به Klussie',
 today:'امروز', lists:'فهرست‌ها', chores:'کارها', calendar:'تقویم', people:'اعضا', navChores:'کارها', navPeople:'اعضا',
 create:'ساخت خانواده', join:'پیوستن به خانواده', name:'نام', yourName:'نام شما', familyName:'نام خانواده',
 welcome:'برای زندگی روزمره جا باز کنید', intro:'فهرست‌ها، کارها و برنامه‌های مشترک را در فضای خصوصی خانواده نگه دارید.',
 createHint:'با یک نام شروع کنید. وقتی آماده بودید بزرگسالان دیگر را دعوت کنید.',
 joinHint:'کد دعوت یک‌بارمصرفی که دریافت کرده‌اید را وارد کنید. پیوستن، فهرست‌ها و برنامه‌های خانواده را به اشتراک می‌گذارد، نه اطلاعات شخصی خانه شما.',
 code:'کد دعوت', save:'ذخیره', cancel:'لغو', close:'بستن', add:'افزودن', edit:'ویرایش', archive:'بایگانی',
 loading:'در حال بارگذاری خانواده شما…', loadFailed:'خانواده شما به‌روزرسانی نشد. دوباره تلاش کنید.', retry:'تلاش دوباره',
 saveFailed:'این تغییر ذخیره نشد. ورودی‌های شما همچنان اینجاست. دوباره تلاش کنید.',
 conflict:'شخصی این مورد را تغییر داد. این فرم را ببندید، به‌روزرسانی کنید و دوباره تلاش کنید.',
 invalidInvite:'این دعوت نامعتبر، منقضی یا قبلاً استفاده شده است.', alreadyMember:'شما قبلاً عضو این خانواده هستید.',
 due:'تاریخ سررسید', assignee:'چه کسی این کار را انجام می‌دهد؟', anyone:'هر کسی', repeat:'تکرار پس از انجام',
 once:'تکرار نمی‌شود', daily:'هر روز', weekly:'هر ۷ روز', fortnightly:'هر ۱۴ روز', monthly:'هر ۳۰ روز',
 taskTitle:'چه کاری باید انجام شود؟', addChore:'افزودن کار', addList:'فهرست جدید', addItem:'افزودن مورد',
 listName:'نام فهرست', emptyLists:'خرید، کارهای روزمره، بستن چمدان. با یک فهرست مفید شروع کنید.', emptyChores:'کارها را تقسیم کنید، هر بار یک کار کوچک.',
 emptyTasks:'این فهرست هنوز خالی است.', done:'انجام شد', reopen:'بازگشایی', completed:'انجام‌شده', upcoming:'پیش رو', overdue:'عقب‌افتاده',
 todayEmpty:'امروز کاری سررسید ندارد. کمی آسودگی.', todayHint:'آنچه نیاز به توجه شما دارد، در یک مکان.',
 addEvent:'افزودن برنامه', eventTitle:'چه اتفاقی می‌افتد؟', start:'روز اول', end:'روز آخر', event:'برنامه', holiday:'تعطیلات',
 eventKind:'نوع', notes:'یادداشت‌ها', allDay:'برنامه‌های تمام‌روز', emptyEvents:'برای تعطیلات، تعطیلی مدرسه یا یک روز با هم جا باز کنید.',
 previous:'ماه قبل', next:'ماه بعد', addPerson:'افزودن عضو خانه', personName:'نام نمایشی',
 adult:'بزرگسال', child:'کودک', owner:'سازمان‌دهنده خانواده', member:'عضو خانواده', noLogin:'پروفایل مدیریت‌شده · بدون ورود',
 personHint:'پروفایل مدیریت‌شده می‌تواند کار بگیرد اما نمی‌تواند وارد شود. برای دسترسی، یک بزرگسال را جداگانه دعوت کنید.',
 invite:'دعوت بزرگسال', inviteHint:'این کد یک بار ظرف ۷ روز قابل استفاده است. آن را فقط با فردی که می‌خواهید دعوت کنید به اشتراک بگذارید.',
 inviteCode:'کد دعوت شما', pendingInvites:'دعوت‌های در انتظار', expires:'انقضا', revoke:'لغو', remove:'حذف عضو',
 removeHint:'دسترسی او به خانواده پایان می‌یابد و کارهایش بدون تخصیص می‌شوند.', confirm:'تأیید',
 privacy:'فضای خانواده شما جدا از خانه‌ها و کار حرفه‌ای شماست.', refresh:'به‌روزرسانی',
 budgetLater:'بودجه‌های مشترک و پس‌انداز تعطیلات بعداً می‌آیند. این نسخه بر سازمان‌دهی روزمره تمرکز دارد.',
 newFamily:'خانواده جدید', all:'همه', mine:'به من واگذار شده', noMatches:'چیزی در این نما نیست.',
};
const tr = {
 title:'Aile', tagline:'Daha az hatırla. Daha çok birlikte yaşa.', back:'Klussie\'ye dön',
 today:'Bugün', lists:'Listeler', chores:'Görevler', calendar:'Takvim', people:'Üyeler', navChores:'Görevler', navPeople:'Üyeler',
 create:'Aile oluştur', join:'Bir aileye katıl', name:'İsim', yourName:'Adın', familyName:'Aile adı',
 welcome:'Günlük hayata yer aç', intro:'Paylaşılan listeleri, görevleri ve planları özel bir aile alanında tut.',
 createHint:'Bir isimle başla. Hazır olduğunda diğer yetişkinleri davet et.',
 joinHint:'Sana paylaşılan tek kullanımlık davet kodunu yapıştır. Katılmak aile listelerini ve planlarını paylaşır, kişisel ev kayıtlarını değil.',
 code:'Davet kodu', save:'Kaydet', cancel:'İptal', close:'Kapat', add:'Ekle', edit:'Düzenle', archive:'Arşivle',
 loading:'Ailen yükleniyor…', loadFailed:'Ailen yenilenemedi. Tekrar dene.', retry:'Tekrar dene',
 saveFailed:'Bu değişiklik kaydedilemedi. Girdiklerin hâlâ burada. Tekrar dene.',
 conflict:'Birisi bu kaydı değiştirdi. Bu formu kapat, yenile ve tekrar dene.',
 invalidInvite:'Bu davet geçersiz, süresi dolmuş veya zaten kullanılmış.', alreadyMember:'Zaten bu ailenin bir üyesisin.',
 due:'Son tarih', assignee:'Bunu kim üstlenecek?', anyone:'Herkes', repeat:'Tamamlandıktan sonra tekrarla',
 once:'Tekrarlanmaz', daily:'Her gün', weekly:'Her 7 günde bir', fortnightly:'Her 14 günde bir', monthly:'Her 30 günde bir',
 taskTitle:'Ne yapılması gerekiyor?', addChore:'Görev ekle', addList:'Yeni liste', addItem:'Öğe ekle',
 listName:'Liste adı', emptyLists:'Market, işler, paketleme. Faydalı bir listeyle başla.', emptyChores:'İşi paylaş, seferde bir küçük görev.',
 emptyTasks:'Bu liste henüz boş.', done:'Tamam', reopen:'Yeniden aç', completed:'Tamamlandı', upcoming:'Yaklaşan', overdue:'Gecikmiş',
 todayEmpty:'Bugün için bir şey yok. Biraz nefes alma zamanı.', todayHint:'Dikkatini isteyen her şey, tek bir yerde.',
 addEvent:'Plan ekle', eventTitle:'Ne oluyor?', start:'İlk gün', end:'Son gün', event:'Plan', holiday:'Tatil',
 eventKind:'Tür', notes:'Notlar', allDay:'Tüm gün süren planlar', emptyEvents:'Bir tatil, okul tatili veya birlikte geçirilecek bir gün için yer aç.',
 previous:'Önceki ay', next:'Sonraki ay', addPerson:'Ev halkı üyesi ekle', personName:'Görünen ad',
 adult:'Yetişkin', child:'Çocuk', owner:'Aile düzenleyicisi', member:'Aile üyesi', noLogin:'Yönetilen profil · giriş yok',
 personHint:'Yönetilen bir profile görev atanabilir ama giriş yapamaz. Erişim vermek için bir yetişkini ayrıca davet et.',
 invite:'Yetişkin davet et', inviteHint:'Bu kod 7 gün içinde bir kez kullanılabilir. Yalnızca davet etmek istediğin kişiyle paylaş.',
 inviteCode:'Davet kodun', pendingInvites:'Bekleyen davetler', expires:'Son kullanma', revoke:'İptal et', remove:'Üyeyi kaldır',
 removeHint:'Aile erişimi sona erecek ve görevleri atanmamış hale gelecek.', confirm:'Onayla',
 privacy:'Aile alanın, evlerinden ve profesyonel işinden ayrıdır.', refresh:'Yenile',
 budgetLater:'Paylaşılan bütçeler ve tatil tasarrufu sırada. Bu sürüm günlük organizasyona odaklanıyor.',
 newFamily:'Yeni aile', all:'Tümü', mine:'Bana atanan', noMatches:'Bu görünümde hiçbir şey yok.',
};
const ru = {
 title:'Семья', tagline:'Меньше держать в голове. Больше жить вместе.', back:'Назад в Klussie',
 today:'Сегодня', lists:'Списки', chores:'Дела', calendar:'Календарь', people:'Участники', navChores:'Дела', navPeople:'Участники',
 create:'Создать семью', join:'Присоединиться к семье', name:'Имя', yourName:'Твоё имя', familyName:'Название семьи',
 welcome:'Освободи место для повседневной жизни', intro:'Храните общие списки, дела и планы в приватном семейном пространстве.',
 createHint:'Начни с названия. Пригласи других взрослых, когда будешь готов.',
 joinHint:'Вставь одноразовый код приглашения, который тебе прислали. Присоединение открывает доступ к семейным спискам и планам, но не к личным данным дома.',
 code:'Код приглашения', save:'Сохранить', cancel:'Отмена', close:'Закрыть', add:'Добавить', edit:'Изменить', archive:'Архивировать',
 loading:'Загружаем твою семью…', loadFailed:'Не удалось обновить данные семьи. Попробуй снова.', retry:'Повторить',
 saveFailed:'Не удалось сохранить изменение. Твои данные всё ещё здесь. Попробуй снова.',
 conflict:'Кто-то изменил эту запись. Закрой форму, обнови и попробуй снова.',
 invalidInvite:'Это приглашение недействительно, истекло или уже использовано.', alreadyMember:'Ты уже состоишь в этой семье.',
 due:'Срок выполнения', assignee:'Кто этим займётся?', anyone:'Любой', repeat:'Повторять после выполнения',
 once:'Не повторяется', daily:'Каждый день', weekly:'Каждые 7 дней', fortnightly:'Каждые 14 дней', monthly:'Каждые 30 дней',
 taskTitle:'Что нужно сделать?', addChore:'Добавить дело', addList:'Новый список', addItem:'Добавить пункт',
 listName:'Название списка', emptyLists:'Покупки, поручения, сборы. Начни с одного полезного списка.', emptyChores:'Разделите работу — по одному небольшому делу.',
 emptyTasks:'Этот список пока пуст.', done:'Готово', reopen:'Открыть снова', completed:'Выполнено', upcoming:'Скоро', overdue:'Просрочено',
 todayEmpty:'На сегодня дел нет. Немного передышки.', todayHint:'Всё, что требует твоего внимания, в одном месте.',
 addEvent:'Добавить план', eventTitle:'Что происходит?', start:'Первый день', end:'Последний день', event:'План', holiday:'Отпуск',
 eventKind:'Тип', notes:'Заметки', allDay:'Планы на весь день', emptyEvents:'Освободи место для отпуска, школьных каникул или дня вместе.',
 previous:'Предыдущий месяц', next:'Следующий месяц', addPerson:'Добавить члена семьи', personName:'Отображаемое имя',
 adult:'Взрослый', child:'Ребёнок', owner:'Организатор семьи', member:'Член семьи', noLogin:'Управляемый профиль · без входа',
 personHint:'Управляемому профилю можно назначать дела, но он не может входить в систему. Пригласи взрослого отдельно, чтобы дать ему доступ.',
 invite:'Пригласить взрослого', inviteHint:'Этот код можно использовать один раз в течение 7 дней. Делись им только с тем, кого хочешь пригласить.',
 inviteCode:'Твой код приглашения', pendingInvites:'Открытые приглашения', expires:'Истекает', revoke:'Отозвать', remove:'Удалить участника',
 removeHint:'Доступ к семье будет закрыт, а его дела останутся без исполнителя.', confirm:'Подтвердить',
 privacy:'Семейное пространство отделено от твоих домов и профессиональной деятельности.', refresh:'Обновить',
 budgetLater:'Общие бюджеты и накопления на отпуск появятся позже. Эта версия посвящена повседневной организации.',
 newFamily:'Новая семья', all:'Все', mine:'Назначено мне', noMatches:'В этом разделе ничего нет.',
};
const zh = {
 title:'家庭', tagline:'少一些记挂，多一些共同生活。', back:'返回 Klussie',
 today:'今天', lists:'清单', chores:'家务', calendar:'日历', people:'成员', navChores:'家务', navPeople:'成员',
 create:'创建家庭', join:'加入家庭', name:'姓名', yourName:'你的姓名', familyName:'家庭名称',
 welcome:'为日常生活腾出空间', intro:'在私密的家庭空间中保存共享的清单、家务和计划。',
 createHint:'先取一个名称，准备好后再邀请其他成年人。',
 joinHint:'粘贴你收到的一次性邀请码。加入后将共享家庭清单和计划，而不是你的个人住宅信息。',
 code:'邀请码', save:'保存', cancel:'取消', close:'关闭', add:'添加', edit:'编辑', archive:'归档',
 loading:'正在加载你的家庭…', loadFailed:'无法刷新你的家庭信息，请重试。', retry:'重试',
 saveFailed:'无法保存此更改，你的输入仍保留在此，请重试。',
 conflict:'有人修改了此记录。请关闭此表单，刷新后重试。',
 invalidInvite:'此邀请无效、已过期或已被使用。', alreadyMember:'你已经是这个家庭的成员。',
 due:'截止日期', assignee:'谁来负责？', anyone:'任何人', repeat:'完成后重复',
 once:'不重复', daily:'每天', weekly:'每 7 天', fortnightly:'每 14 天', monthly:'每 30 天',
 taskTitle:'需要做什么？', addChore:'添加家务', addList:'新建清单', addItem:'添加项目',
 listName:'清单名称', emptyLists:'购物、跑腿、打包。先建一个有用的清单。', emptyChores:'分担工作，一次一个小任务。',
 emptyTasks:'这个清单还是空的。', done:'完成', reopen:'重新打开', completed:'已完成', upcoming:'即将到来', overdue:'已逾期',
 todayEmpty:'今天没有待办事项，喘口气吧。', todayHint:'所有需要你关注的事，都在一个地方。',
 addEvent:'添加计划', eventTitle:'发生了什么？', start:'第一天', end:'最后一天', event:'计划', holiday:'假期',
 eventKind:'类型', notes:'备注', allDay:'全天计划', emptyEvents:'为假期、学校假期或共度的一天留出空间。',
 previous:'上个月', next:'下个月', addPerson:'添加家庭成员', personName:'显示名称',
 adult:'成人', child:'儿童', owner:'家庭组织者', member:'家庭成员', noLogin:'托管资料 · 无法登录',
 personHint:'托管资料可以被分配家务，但无法登录。请单独邀请成人以授予其访问权限。',
 invite:'邀请成人', inviteHint:'此邀请码可在 7 天内使用一次，请仅与你想邀请的人分享。',
 inviteCode:'你的邀请码', pendingInvites:'待处理的邀请', expires:'过期时间', revoke:'撤销', remove:'移除成员',
 removeHint:'其家庭访问权限将被终止，其家务将变为未分配状态。', confirm:'确认',
 privacy:'你的家庭空间与你的住宅和职业工作是分开的。', refresh:'刷新',
 budgetLater:'共享预算和假期储蓄功能即将推出。此版本专注于日常协调。',
 newFamily:'新建家庭', all:'全部', mine:'分配给我', noMatches:'此视图中没有内容。',
};
export const FAMILY_STRINGS = { en, nl, fr, de, es, ar, fa, tr, ru, zh };
export function familyStrings(locale) { return FAMILY_STRINGS[locale] || en; }
