// Locale copy for the customer home surface (hero, section tabs, intents, the
// "today" card, My Home, My Items, and the first-login tour).
//
// Kept out of src/App.jsx's STRINGS object on purpose: that file is already the
// largest in the repository (MASTER_CONTEXT.md §12 tracks it as high-severity
// debt), and adding ~120 keys across 10 locales to it would make the single worst
// file measurably worse. App() merges this in, so `t` stays one flat lookup at
// every call site — same shape, different home.
//
// Dutch is the reference locale (COPY_GUIDELINES.md); the other seven follow it.
// Any string describing something not yet built says so plainly rather than
// implying the capability exists (Constitution Rule 9).

export const HOME_STRINGS = {
  nl: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "Waarmee kan Klussie je vandaag helpen?",
    homeHeroFallbackLabel: "Warm interieur van een woning",
    homeTabsLabel: "Onderdelen van je woning",
    homeTabKlussie: "Klussie", homeTabMyHome: "Mijn woning", homeTabMyItems: "Mijn spullen",

    intentsLabel: "Waar gaat het over?",
    intentBroken: "Er is iets kapot", intentImprove: "Ik wil iets verbeteren",
    intentMaintain: "Ik wil onderhoud plannen", intentAdvice: "Ik heb advies nodig",
    intentOther: "Iets anders",
    intentChosen: "Gekozen", intentChange: "Kies iets anders",

    homeComposerPlaceholder: "Beschrijf kort wat er aan de hand is…",
    homeVoiceAction: "Inspreken", homePhotoAction: "Foto toevoegen", homeSendAction: "Versturen",
    homeAnswerLabel: "Jouw antwoord",
    followUpProgress: "Vraag {n} van {total}",
    followUpBack: "Vorige vraag", followUpSkip: "Sla over en verstuur",

    safetyTitle: "Dit klinkt mogelijk onveilig",
    safetyBody: "Ruik je gas, zie je vuur, staat er water of is er gevaar door elektriciteit? Bel dan eerst de hulpdiensten of je netbeheerder. Klussie stelt geen diagnose.",
    safetyContinue: "Toch verder met mijn aanvraag", safetyBack: "Terug",

    todayHeading: "Vandaag voor jouw woning",
    todayQuotesTitle: "Offertes wachten op je keuze",
    todayQuotesBody: "Bekijk de offertes voor {service} en kies wie de klus doet.",
    todayBookedTitle: "Je klus staat gepland",
    todayBookedBody: "{service} is geboekt. Je vakman houdt je op de hoogte.",
    todayAwaitingTitle: "Je aanvraag ligt bij één vakman",
    todayAwaitingBody: "{service} — je hoort het zodra hij of zij reageert.",
    todayCollectingTitle: "Vakmensen bekijken je aanvraag",
    todayCollectingBody: "{service} — offertes komen meestal binnen enkele minuten binnen.",
    todayReviewTitle: "Laat weten hoe het ging",
    todayReviewBody: "{service} is afgerond. Je beoordeling helpt de volgende klant.",
    todayOpenCta: "Bekijk aanvraag",
    todayEmptyTitle: "Maak je woning slimmer met Klussie",
    todayEmptyBody: "Voeg je eerste ruimte, installatie of huishoudelijk item toe.",
    todayEmptyCta: "Stel mijn woning in",
    homeActiveTitle: "Loopt op dit moment",

    myHomeQuestion: "Wat wil je over je woning bekijken of bijhouden?",
    homeReportProblem: "Probleem melden",
    myHomeNoPropertyYet: "Zodra je iets via Klussie laat doen, bouwt de geschiedenis van je woning zich hier op.",
    myHomeKnownSince: "Bij Klussie sinds {date}",
    myHomeJobsSummary: "{total} aanvragen, waarvan {completed} afgerond.",
    myHomeDoneBy: "Uitgevoerd door {name}",
    myHomeAiRead: "Klussie las",
    myHomeActiveTitle: "Loopt nu",
    myHomeActiveEmpty: "Er loopt op dit moment niets.",
    myHomeProsTitle: "Vakmensen die je woning kennen",
    myHomeProsEmpty: "Nog geen vakman die hier een klus afrondde.",
    myHomeOneJobTogether: "1 klus samen",
    myHomeJobsTogether: "{count} klussen samen",
    myHomeHistoryTitle: "Geschiedenis van je woning",
    myHomeHistoryEmpty: "Zodra je een klus afrondt via Klussie, verschijnt die hier.",
    myHomeReviewsTitle: "Jouw beoordelingen",
    myHomeReviewsEmpty: "Je hebt nog geen beoordeling geschreven.",
    myHomeAiTitle: "Wat Klussie begreep",
    myHomeAiEmpty: "Nog geen AI-analyse van een klus.",
    myHomePhotosTitle: "Foto's van je woning",
    myHomePhotosEmpty: "Nog geen foto's bij een aanvraag toegevoegd.",
    myHomePhotosLoading: "Foto's laden…",

    myItemsQuestion: "Wat wil je toevoegen of terugvinden?",
    myItemsEmptyTitle: "Je hebt nog niets toegevoegd.",
    myItemsEmptyHint: "Voeg je ketel, wasmachine of gereedschap toe — dan weet je later precies welk model je hebt.",
    myItemsLoading: "Je spullen laden…",
    myItemsLoadFailed: "We konden je spullen niet laden. Probeer het later opnieuw.",
    myItemsRoomsTitle: "Ruimtes", myItemsRoomsEmpty: "Nog geen ruimtes toegevoegd.",
    myItemsMaintenanceTitle: "Onderhoud", myItemsMaintenanceEmpty: "Niets gepland of achterstallig.",
    myItemsMaintenanceOverdue: "Achterstallig", myItemsMaintenanceDueOn: "Verval op {date}",
    myItemsDocumentsTitle: "Documenten", myItemsDocumentsEmpty: "Nog geen documenten toegevoegd.",
    myItemsDocumentExpired: "Verlopen", myItemsDocumentValidUntil: "Geldig tot {date}",
    homeBuilderTitle: "Ruimtes", homeBuilderLoading: "Ruimtes laden…",
    homeBuilderNoPropertyYet: "We zijn je woning nog aan het instellen. Kom zo snel mogelijk terug.",
    homeBuilderEmptyTitle: "Begin met het opbouwen van je woning",
    homeBuilderEmptyHint: "Voeg je eerste ruimte toe — bijvoorbeeld de keuken of woonkamer — en bouw van daaruit verder.",
    homeBuilderAddFirstRoom: "Voeg je eerste ruimte toe", homeBuilderAddAnotherRoom: "Nog een ruimte toevoegen",
    locationEditTitle: "Ruimte bewerken", locationSaveChanges: "Wijzigingen opslaan",
    locationAddItemHere: "Iets toevoegen in deze ruimte", locationRemove: "Ruimte verwijderen",
    locationRemoveConfirm: "Deze ruimte verwijderen? Dit kan niet ongedaan gemaakt worden.",
    locationRetireBlockedChildren: "Deze ruimte bevat nog een andere ruimte. Verwijder die eerst.",
    locationRetireBlockedItems: "Er staat nog iets in deze ruimte. Verwijder of verplaats dat eerst.",
    locationFormAddTitle: "Ruimte toevoegen", locationFormNameLabel: "Naam",
    locationFormNamePlaceholder: "bv. Zolder", locationFormTypeLabel: "Soort (optioneel)",
    locationFormTypePlaceholder: "bv. slaapkamer", locationFormParentLabel: "Binnen (optioneel)",
    locationFormParentNone: "Geen — bovenaan", locationFormSaveNew: "Ruimte bewaren",
    locationFormSaveFailed: "We konden de ruimte niet bewaren. Probeer het opnieuw.",
    documentFormAddTitle: "Document toevoegen", documentFormFileLabel: "Bestand",
    documentFormFileAdd: "Bestand kiezen", documentFormTypeLabel: "Soort",
    documentTypeWarranty: "Garantie", documentTypeCertificate: "Certificaat",
    documentTypeManual: "Handleiding", documentTypeOther: "Andere",
    documentTypePortfolioPhoto: "Portfoliofoto", documentTypeRequestPhoto: "Aanvraagfoto",
    documentFormIssuerLabel: "Uitgever (optioneel)", documentFormValidUntilLabel: "Geldig tot (optioneel)",
    documentFormSaveNew: "Document bewaren",
    documentFormSaveFailed: "We konden het document niet bewaren. Probeer het opnieuw.",
    myItemsOneItem: "1 stuk", myItemsCount: "{count} stuks",
    itemCatAppliance: "Toestellen", itemCatElectronics: "Elektronica",
    itemCatFurniture: "Meubels en verlichting", itemCatGarden: "Tuin",
    itemCatTool: "Gereedschap", itemCatOther: "Andere",
    itemRoomKitchen: "Keuken", itemRoomLiving: "Woonkamer", itemRoomBedroom: "Slaapkamer",
    itemRoomBathroom: "Badkamer", itemRoomGarage: "Garage", itemRoomGarden: "Tuin",
    itemRoomAttic: "Zolder", itemRoomBasement: "Kelder",
    itemAddTitle: "Item toevoegen", itemEditTitle: "Item bewerken",
    itemNameLabel: "Wat is het?", itemNamePlaceholder: "bv. wasmachine",
    itemCategoryLabel: "Soort", itemRoomLabel: "Waar staat het?", itemRoomPlaceholder: "bv. keuken",
    itemRoomNone: "Geen ruimte gekozen",
    itemBrandLabel: "Merk (optioneel)", itemModelLabel: "Model (optioneel)",
    itemPhotoLabel: "Foto (optioneel)", itemPhotoAdd: "Foto toevoegen", itemPhotoRemove: "Foto verwijderen",
    itemPurchasedLabel: "Gekocht op (optioneel)", itemNotesLabel: "Notities (optioneel)",
    itemSaveNew: "Item bewaren", itemSaveChanges: "Wijzigingen opslaan",
    itemDelete: "Item verwijderen",
    itemDeleteConfirm: "Dit item verwijderen? Dit kan niet ongedaan gemaakt worden.",

    tourTitle: "Rondleiding door Klussie",
    tourProgress: "Stap {n} van {total}",
    tourStep1Title: "Vertel of toon wat er aan de hand is",
    tourStep1Body: "Gebruik tekst, spraak of een foto.",
    tourStep2Title: "Klussie stelt de juiste vragen",
    tourStep2Body: "We maken samen een duidelijke aanvraag.",
    tourStep3Title: "Bewaar alles over je woning",
    tourStep3Body: "Houd ruimtes, installaties, documenten en onderhoud bij.",
    tourStep4Title: "Volg je spullen en garanties",
    tourStep4Body: "Bewaar producten, aankoopbewijzen, handleidingen en garanties.",
    proTourStep0Title: "Welkom", proTourStep0Body: "Elke klus die je zo meteen ziet, is een kans om te doen waar je goed in bent — en er eerlijk voor betaald te worden. Laat ik je even wegwijs maken.",
    proTourStep1Title: "Dashboard", proTourStep1Body: "Zodra een klant in de buurt precies zoekt wat jij aanbiedt, zie je het hier — niet toevallig, maar omdat het bij jou past.",
    proTourStep2Title: "Mijn klussen", proTourStep2Body: "Elke offerte die je verstuurt, elke klus die je boekt, van voorstel tot betaling — allemaal op één plek.",
    proTourStep3Title: "Berichten", proTourStep3Body: "Praat rechtstreeks met je klant, geen nummers uitwisselen.",
    proTourStep4Title: "Jouw tempo, jouw keuze", proTourStep4Body: "Even geen tijd? Zet jezelf hier tijdelijk op pauze — je verdwijnt niet, je bent gewoon even niet zichtbaar voor nieuwe klussen.",
    proTourStep5Title: "Dat is het", proTourStep5Body: "De leads komen naar jou toe — jij kiest wat je aanneemt.",
    proTourDoneCta: "Naar dashboard",
    tourNext: "Volgende", tourBack: "Vorige", tourSkip: "Overslaan",
    tourStartCta: "Start met Klussie", tourSetupHomeCta: "Stel eerst mijn woning in",
    helpSectionTitle: "Hulp & uitleg", helpReplayTour: "Rondleiding opnieuw bekijken",
  },

  fr: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "Comment Klussie peut-il t'aider aujourd'hui ?",
    homeHeroFallbackLabel: "Intérieur chaleureux d'une habitation",
    homeTabsLabel: "Sections de ton logement",
    homeTabKlussie: "Klussie", homeTabMyHome: "Mon logement", homeTabMyItems: "Mes objets",

    intentsLabel: "De quoi s'agit-il ?",
    intentBroken: "Quelque chose est cassé", intentImprove: "Je veux améliorer quelque chose",
    intentMaintain: "Je veux planifier un entretien", intentAdvice: "J'ai besoin de conseils",
    intentOther: "Autre chose",
    intentChosen: "Choisi", intentChange: "Choisir autre chose",

    homeComposerPlaceholder: "Décris brièvement ce qui se passe…",
    homeVoiceAction: "Dicter", homePhotoAction: "Ajouter une photo", homeSendAction: "Envoyer",
    homeAnswerLabel: "Ta réponse",
    followUpProgress: "Question {n} sur {total}",
    followUpBack: "Question précédente", followUpSkip: "Passer et envoyer",

    safetyTitle: "Cela peut être dangereux",
    safetyBody: "Tu sens le gaz, tu vois du feu, il y a de l'eau ou un danger électrique ? Appelle d'abord les secours ou ton gestionnaire de réseau. Klussie ne pose aucun diagnostic.",
    safetyContinue: "Continuer quand même ma demande", safetyBack: "Retour",

    todayHeading: "Aujourd'hui pour ton logement",
    todayQuotesTitle: "Des devis attendent ton choix",
    todayQuotesBody: "Consulte les devis pour {service} et choisis qui fera le travail.",
    todayBookedTitle: "Ta tâche est planifiée",
    todayBookedBody: "{service} est réservé. Ton pro te tient au courant.",
    todayAwaitingTitle: "Ta demande est chez un seul pro",
    todayAwaitingBody: "{service} — tu seras prévenu dès qu'il ou elle répond.",
    todayCollectingTitle: "Les pros examinent ta demande",
    todayCollectingBody: "{service} — les devis arrivent généralement en quelques minutes.",
    todayReviewTitle: "Dis-nous comment cela s'est passé",
    todayReviewBody: "{service} est terminé. Ton avis aide le prochain client.",
    todayOpenCta: "Voir la demande",
    todayEmptyTitle: "Rends ton logement plus intelligent avec Klussie",
    todayEmptyBody: "Ajoute ta première pièce, installation ou objet du foyer.",
    todayEmptyCta: "Configurer mon logement",
    homeActiveTitle: "En cours actuellement",

    myHomeQuestion: "Que veux-tu consulter ou suivre pour ton logement ?",
    homeReportProblem: "Signaler un problème",
    myHomeNoPropertyYet: "Dès que tu fais réaliser quelque chose via Klussie, l'histoire de ton logement se construit ici.",
    myHomeKnownSince: "Sur Klussie depuis le {date}",
    myHomeJobsSummary: "{total} demandes, dont {completed} terminées.",
    myHomeDoneBy: "Réalisé par {name}",
    myHomeAiRead: "Klussie a compris",
    myHomeActiveTitle: "En cours",
    myHomeActiveEmpty: "Rien en cours pour le moment.",
    myHomeProsTitle: "Les pros qui connaissent ton logement",
    myHomeProsEmpty: "Aucun pro n'a encore terminé de travaux ici.",
    myHomeOneJobTogether: "1 chantier ensemble",
    myHomeJobsTogether: "{count} chantiers ensemble",
    myHomeHistoryTitle: "Historique de ton logement",
    myHomeHistoryEmpty: "Dès que tu termines une tâche via Klussie, elle apparaît ici.",
    myHomeReviewsTitle: "Tes avis",
    myHomeReviewsEmpty: "Tu n'as pas encore écrit d'avis.",
    myHomeAiTitle: "Ce que Klussie a compris",
    myHomeAiEmpty: "Aucune analyse IA pour l'instant.",
    myHomePhotosTitle: "Photos de ton logement",
    myHomePhotosEmpty: "Aucune photo ajoutée à une demande pour l'instant.",
    myHomePhotosLoading: "Chargement des photos…",

    myItemsQuestion: "Que veux-tu ajouter ou retrouver ?",
    myItemsEmptyTitle: "Tu n'as encore rien ajouté.",
    myItemsEmptyHint: "Ajoute ta chaudière, ton lave-linge ou tes outils — tu sauras plus tard exactement quel modèle tu as.",
    myItemsLoading: "Chargement de tes objets…",
    myItemsLoadFailed: "Impossible de charger tes objets. Réessaie plus tard.",
    myItemsRoomsTitle: "Pièces", myItemsRoomsEmpty: "Aucune pièce ajoutée pour l'instant.",
    myItemsMaintenanceTitle: "Entretien", myItemsMaintenanceEmpty: "Rien de prévu ni en retard.",
    myItemsMaintenanceOverdue: "En retard", myItemsMaintenanceDueOn: "Échéance le {date}",
    myItemsDocumentsTitle: "Documents", myItemsDocumentsEmpty: "Aucun document ajouté pour l'instant.",
    myItemsDocumentExpired: "Expiré", myItemsDocumentValidUntil: "Valable jusqu'au {date}",
    homeBuilderTitle: "Pièces", homeBuilderLoading: "Chargement des pièces…",
    homeBuilderNoPropertyYet: "Nous configurons encore votre logement. Revenez bientôt.",
    homeBuilderEmptyTitle: "Commencez à construire votre logement",
    homeBuilderEmptyHint: "Ajoutez votre première pièce — par exemple la cuisine ou le salon — puis continuez à partir de là.",
    homeBuilderAddFirstRoom: "Ajouter votre première pièce", homeBuilderAddAnotherRoom: "Ajouter une autre pièce",
    locationEditTitle: "Modifier la pièce", locationSaveChanges: "Enregistrer les modifications",
    locationAddItemHere: "Ajouter un objet dans cette pièce", locationRemove: "Supprimer la pièce",
    locationRemoveConfirm: "Supprimer cette pièce ? Cette action est irréversible.",
    locationRetireBlockedChildren: "Cette pièce contient encore une autre pièce. Supprimez-la d'abord.",
    locationRetireBlockedItems: "Il y a encore quelque chose dans cette pièce. Supprimez-le ou déplacez-le d'abord.",
    locationFormAddTitle: "Ajouter une pièce", locationFormNameLabel: "Nom",
    locationFormNamePlaceholder: "p.ex. Grenier", locationFormTypeLabel: "Type (optionnel)",
    locationFormTypePlaceholder: "p.ex. chambre", locationFormParentLabel: "Dans (optionnel)",
    locationFormParentNone: "Aucun — au premier niveau", locationFormSaveNew: "Enregistrer la pièce",
    locationFormSaveFailed: "Impossible d'enregistrer la pièce. Réessaie plus tard.",
    documentFormAddTitle: "Ajouter un document", documentFormFileLabel: "Fichier",
    documentFormFileAdd: "Choisir un fichier", documentFormTypeLabel: "Type",
    documentTypeWarranty: "Garantie", documentTypeCertificate: "Certificat",
    documentTypeManual: "Manuel", documentTypeOther: "Autre",
    documentTypePortfolioPhoto: "Photo de portfolio", documentTypeRequestPhoto: "Photo de la demande",
    documentFormIssuerLabel: "Émetteur (optionnel)", documentFormValidUntilLabel: "Valable jusqu'au (optionnel)",
    documentFormSaveNew: "Enregistrer le document",
    documentFormSaveFailed: "Impossible d'enregistrer le document. Réessaie plus tard.",
    myItemsOneItem: "1 objet", myItemsCount: "{count} objets",
    itemCatAppliance: "Électroménager", itemCatElectronics: "Électronique",
    itemCatFurniture: "Meubles et éclairage", itemCatGarden: "Jardin",
    itemCatTool: "Outils", itemCatOther: "Autre",
    itemRoomKitchen: "Cuisine", itemRoomLiving: "Salon", itemRoomBedroom: "Chambre",
    itemRoomBathroom: "Salle de bain", itemRoomGarage: "Garage", itemRoomGarden: "Jardin",
    itemRoomAttic: "Grenier", itemRoomBasement: "Cave",
    itemAddTitle: "Ajouter un objet", itemEditTitle: "Modifier l'objet",
    itemNameLabel: "Qu'est-ce que c'est ?", itemNamePlaceholder: "ex. lave-linge",
    itemCategoryLabel: "Type", itemRoomLabel: "Où se trouve-t-il ?", itemRoomPlaceholder: "ex. cuisine",
    itemRoomNone: "Aucune pièce choisie",
    itemBrandLabel: "Marque (facultatif)", itemModelLabel: "Modèle (facultatif)",
    itemPhotoLabel: "Photo (facultatif)", itemPhotoAdd: "Ajouter une photo", itemPhotoRemove: "Supprimer la photo",
    itemPurchasedLabel: "Acheté le (facultatif)", itemNotesLabel: "Notes (facultatif)",
    itemSaveNew: "Enregistrer l'objet", itemSaveChanges: "Enregistrer les modifications",
    itemDelete: "Supprimer l'objet",
    itemDeleteConfirm: "Supprimer cet objet ? Cette action est irréversible.",

    tourTitle: "Visite guidée de Klussie",
    tourProgress: "Étape {n} sur {total}",
    tourStep1Title: "Raconte ou montre ce qui se passe",
    tourStep1Body: "Utilise le texte, la voix ou une photo.",
    tourStep2Title: "Klussie pose les bonnes questions",
    tourStep2Body: "Nous construisons ensemble une demande claire.",
    tourStep3Title: "Garde tout sur ton logement",
    tourStep3Body: "Suis tes pièces, installations, documents et entretiens.",
    tourStep4Title: "Suis tes objets et tes garanties",
    tourStep4Body: "Conserve produits, preuves d'achat, manuels et garanties.",
    proTourStep0Title: "Bienvenue", proTourStep0Body: "Chaque chantier que tu vas voir est une occasion de faire ce que tu fais bien — et d'être payé équitablement pour ça. Laisse-moi te faire visiter.",
    proTourStep1Title: "Tableau de bord", proTourStep1Body: "Dès qu'un client à proximité cherche exactement ce que tu proposes, tu le vois ici — pas par hasard, parce que ça te correspond.",
    proTourStep2Title: "Mes chantiers", proTourStep2Body: "Chaque devis envoyé, chaque chantier réservé, du devis au paiement — tout au même endroit.",
    proTourStep3Title: "Messages", proTourStep3Body: "Parle directement avec ton client, sans échanger de numéros.",
    proTourStep4Title: "Ton rythme, ton choix", proTourStep4Body: "Pas le temps là maintenant ? Mets-toi en pause ici — tu ne disparais pas, tu es juste temporairement invisible pour les nouveaux chantiers.",
    proTourStep5Title: "C'est tout", proTourStep5Body: "Les chantiers viennent à toi — c'est toi qui choisis ce que tu acceptes.",
    proTourDoneCta: "Aller au tableau de bord",
    tourNext: "Suivant", tourBack: "Précédent", tourSkip: "Passer",
    tourStartCta: "Commencer avec Klussie", tourSetupHomeCta: "Configurer d'abord mon logement",
    helpSectionTitle: "Aide & explications", helpReplayTour: "Revoir la visite guidée",
  },

  de: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "Womit kann Klussie dir heute helfen?",
    homeHeroFallbackLabel: "Warmer Innenraum einer Wohnung",
    homeTabsLabel: "Bereiche deines Zuhauses",
    homeTabKlussie: "Klussie", homeTabMyHome: "Mein Zuhause", homeTabMyItems: "Meine Sachen",

    intentsLabel: "Worum geht es?",
    intentBroken: "Etwas ist kaputt", intentImprove: "Ich möchte etwas verbessern",
    intentMaintain: "Ich möchte Wartung planen", intentAdvice: "Ich brauche einen Rat",
    intentOther: "Etwas anderes",
    intentChosen: "Ausgewählt", intentChange: "Etwas anderes wählen",

    homeComposerPlaceholder: "Beschreibe kurz, was los ist…",
    homeVoiceAction: "Sprechen", homePhotoAction: "Foto hinzufügen", homeSendAction: "Senden",
    homeAnswerLabel: "Deine Antwort",
    followUpProgress: "Frage {n} von {total}",
    followUpBack: "Vorherige Frage", followUpSkip: "Überspringen und senden",

    safetyTitle: "Das klingt möglicherweise gefährlich",
    safetyBody: "Riechst du Gas, siehst du Feuer, steht Wasser oder besteht Gefahr durch Strom? Rufe zuerst den Notruf oder deinen Netzbetreiber an. Klussie stellt keine Diagnose.",
    safetyContinue: "Trotzdem mit meiner Anfrage weitermachen", safetyBack: "Zurück",

    todayHeading: "Heute für dein Zuhause",
    todayQuotesTitle: "Angebote warten auf deine Wahl",
    todayQuotesBody: "Sieh dir die Angebote für {service} an und wähle, wer die Arbeit macht.",
    todayBookedTitle: "Dein Auftrag ist geplant",
    todayBookedBody: "{service} ist gebucht. Dein Profi hält dich auf dem Laufenden.",
    todayAwaitingTitle: "Deine Anfrage liegt bei einem Profi",
    todayAwaitingBody: "{service} — du hörst es, sobald er oder sie antwortet.",
    todayCollectingTitle: "Profis sehen sich deine Anfrage an",
    todayCollectingBody: "{service} — Angebote kommen meist innerhalb weniger Minuten.",
    todayReviewTitle: "Sag uns, wie es gelaufen ist",
    todayReviewBody: "{service} ist abgeschlossen. Deine Bewertung hilft dem nächsten Kunden.",
    todayOpenCta: "Anfrage ansehen",
    todayEmptyTitle: "Mach dein Zuhause schlauer mit Klussie",
    todayEmptyBody: "Füge deinen ersten Raum, deine erste Anlage oder dein erstes Haushaltsgerät hinzu.",
    todayEmptyCta: "Mein Zuhause einrichten",
    homeActiveTitle: "Läuft gerade",

    myHomeQuestion: "Was möchtest du zu deinem Zuhause ansehen oder festhalten?",
    homeReportProblem: "Problem melden",
    myHomeNoPropertyYet: "Sobald du etwas über Klussie erledigen lässt, entsteht hier die Geschichte deines Zuhauses.",
    myHomeKnownSince: "Bei Klussie seit {date}",
    myHomeJobsSummary: "{total} Anfragen, davon {completed} abgeschlossen.",
    myHomeDoneBy: "Ausgeführt von {name}",
    myHomeAiRead: "Klussie verstand",
    myHomeActiveTitle: "Läuft gerade",
    myHomeActiveEmpty: "Im Moment läuft nichts.",
    myHomeProsTitle: "Profis, die dein Zuhause kennen",
    myHomeProsEmpty: "Noch kein Profi hat hier einen Auftrag abgeschlossen.",
    myHomeOneJobTogether: "1 gemeinsamer Auftrag",
    myHomeJobsTogether: "{count} gemeinsame Aufträge",
    myHomeHistoryTitle: "Geschichte deines Zuhauses",
    myHomeHistoryEmpty: "Sobald du einen Auftrag über Klussie abschließt, erscheint er hier.",
    myHomeReviewsTitle: "Deine Bewertungen",
    myHomeReviewsEmpty: "Du hast noch keine Bewertung geschrieben.",
    myHomeAiTitle: "Was Klussie verstanden hat",
    myHomeAiEmpty: "Noch keine KI-Analyse zu einem Auftrag.",
    myHomePhotosTitle: "Fotos deines Zuhauses",
    myHomePhotosEmpty: "Noch keine Fotos zu einer Anfrage hinzugefügt.",
    myHomePhotosLoading: "Fotos werden geladen…",

    myItemsQuestion: "Was möchtest du hinzufügen oder wiederfinden?",
    myItemsEmptyTitle: "Du hast noch nichts hinzugefügt.",
    myItemsEmptyHint: "Füge deine Heizung, Waschmaschine oder Werkzeuge hinzu — dann weißt du später genau, welches Modell du hast.",
    myItemsLoading: "Deine Sachen werden geladen…",
    myItemsLoadFailed: "Wir konnten deine Sachen nicht laden. Bitte später erneut versuchen.",
    myItemsRoomsTitle: "Räume", myItemsRoomsEmpty: "Noch keine Räume hinzugefügt.",
    myItemsMaintenanceTitle: "Wartung", myItemsMaintenanceEmpty: "Nichts geplant oder überfällig.",
    myItemsMaintenanceOverdue: "Überfällig", myItemsMaintenanceDueOn: "Fällig am {date}",
    myItemsDocumentsTitle: "Dokumente", myItemsDocumentsEmpty: "Noch keine Dokumente hinzugefügt.",
    myItemsDocumentExpired: "Abgelaufen", myItemsDocumentValidUntil: "Gültig bis {date}",
    homeBuilderTitle: "Räume", homeBuilderLoading: "Räume werden geladen…",
    homeBuilderNoPropertyYet: "Wir richten dein Zuhause noch ein. Bitte schau bald wieder vorbei.",
    homeBuilderEmptyTitle: "Beginne, dein Zuhause aufzubauen",
    homeBuilderEmptyHint: "Füge deinen ersten Raum hinzu — zum Beispiel die Küche oder das Wohnzimmer — und baue von dort aus weiter.",
    homeBuilderAddFirstRoom: "Ersten Raum hinzufügen", homeBuilderAddAnotherRoom: "Weiteren Raum hinzufügen",
    locationEditTitle: "Raum bearbeiten", locationSaveChanges: "Änderungen speichern",
    locationAddItemHere: "Etwas in diesem Raum hinzufügen", locationRemove: "Raum entfernen",
    locationRemoveConfirm: "Diesen Raum entfernen? Das kann nicht rückgängig gemacht werden.",
    locationRetireBlockedChildren: "Dieser Raum enthält noch einen weiteren Raum. Entferne diesen zuerst.",
    locationRetireBlockedItems: "In diesem Raum befindet sich noch etwas. Entferne oder verschiebe es zuerst.",
    locationFormAddTitle: "Raum hinzufügen", locationFormNameLabel: "Name",
    locationFormNamePlaceholder: "z. B. Dachboden", locationFormTypeLabel: "Art (optional)",
    locationFormTypePlaceholder: "z. B. Schlafzimmer", locationFormParentLabel: "Innerhalb (optional)",
    locationFormParentNone: "Keine — oberste Ebene", locationFormSaveNew: "Raum speichern",
    locationFormSaveFailed: "Wir konnten den Raum nicht speichern. Bitte später erneut versuchen.",
    documentFormAddTitle: "Dokument hinzufügen", documentFormFileLabel: "Datei",
    documentFormFileAdd: "Datei auswählen", documentFormTypeLabel: "Art",
    documentTypeWarranty: "Garantie", documentTypeCertificate: "Zertifikat",
    documentTypeManual: "Anleitung", documentTypeOther: "Andere",
    documentTypePortfolioPhoto: "Portfoliofoto", documentTypeRequestPhoto: "Anfragefoto",
    documentFormIssuerLabel: "Aussteller (optional)", documentFormValidUntilLabel: "Gültig bis (optional)",
    documentFormSaveNew: "Dokument speichern",
    documentFormSaveFailed: "Wir konnten das Dokument nicht speichern. Bitte später erneut versuchen.",
    myItemsOneItem: "1 Stück", myItemsCount: "{count} Stück",
    itemCatAppliance: "Geräte", itemCatElectronics: "Elektronik",
    itemCatFurniture: "Möbel und Licht", itemCatGarden: "Garten",
    itemCatTool: "Werkzeug", itemCatOther: "Sonstiges",
    itemRoomKitchen: "Küche", itemRoomLiving: "Wohnzimmer", itemRoomBedroom: "Schlafzimmer",
    itemRoomBathroom: "Badezimmer", itemRoomGarage: "Garage", itemRoomGarden: "Garten",
    itemRoomAttic: "Dachboden", itemRoomBasement: "Keller",
    itemAddTitle: "Gegenstand hinzufügen", itemEditTitle: "Gegenstand bearbeiten",
    itemNameLabel: "Was ist es?", itemNamePlaceholder: "z.B. Waschmaschine",
    itemCategoryLabel: "Art", itemRoomLabel: "Wo steht es?", itemRoomPlaceholder: "z.B. Küche",
    itemRoomNone: "Kein Raum ausgewählt",
    itemBrandLabel: "Marke (optional)", itemModelLabel: "Modell (optional)",
    itemPhotoLabel: "Foto (optional)", itemPhotoAdd: "Foto hinzufügen", itemPhotoRemove: "Foto entfernen",
    itemPurchasedLabel: "Gekauft am (optional)", itemNotesLabel: "Notizen (optional)",
    itemSaveNew: "Gegenstand speichern", itemSaveChanges: "Änderungen speichern",
    itemDelete: "Gegenstand löschen",
    itemDeleteConfirm: "Diesen Gegenstand löschen? Das kann nicht rückgängig gemacht werden.",

    tourTitle: "Rundgang durch Klussie",
    tourProgress: "Schritt {n} von {total}",
    tourStep1Title: "Erzähl oder zeig, was los ist",
    tourStep1Body: "Nutze Text, Sprache oder ein Foto.",
    tourStep2Title: "Klussie stellt die richtigen Fragen",
    tourStep2Body: "Gemeinsam machen wir daraus eine klare Anfrage.",
    tourStep3Title: "Halte alles zu deinem Zuhause fest",
    tourStep3Body: "Räume, Anlagen, Dokumente und Wartung an einem Ort.",
    tourStep4Title: "Behalte Sachen und Garantien im Blick",
    tourStep4Body: "Bewahre Produkte, Kaufbelege, Anleitungen und Garantien auf.",
    proTourStep0Title: "Willkommen", proTourStep0Body: "Jeder Auftrag, den du gleich siehst, ist eine Chance, das zu tun, was du gut kannst — und fair dafür bezahlt zu werden. Lass mich dir kurz alles zeigen.",
    proTourStep1Title: "Dashboard", proTourStep1Body: "Sobald ein Kunde in deiner Nähe genau das sucht, was du anbietest, siehst du es hier — nicht zufällig, sondern weil es zu dir passt.",
    proTourStep2Title: "Meine Aufträge", proTourStep2Body: "Jedes Angebot, das du verschickst, jeder Auftrag, den du buchst, vom Vorschlag bis zur Bezahlung — alles an einem Ort.",
    proTourStep3Title: "Nachrichten", proTourStep3Body: "Sprich direkt mit deinem Kunden, ohne Nummern auszutauschen.",
    proTourStep4Title: "Dein Tempo, deine Wahl", proTourStep4Body: "Gerade keine Zeit? Pausiere dich hier — du verschwindest nicht, du bist nur vorübergehend für neue Aufträge nicht sichtbar.",
    proTourStep5Title: "Das war's", proTourStep5Body: "Die Aufträge kommen zu dir — du entscheidest, was du annimmst.",
    proTourDoneCta: "Zum Dashboard",
    tourNext: "Weiter", tourBack: "Zurück", tourSkip: "Überspringen",
    tourStartCta: "Mit Klussie starten", tourSetupHomeCta: "Zuerst mein Zuhause einrichten",
    helpSectionTitle: "Hilfe & Erklärung", helpReplayTour: "Rundgang erneut ansehen",
  },

  en: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "What can Klussie help you with today?",
    homeHeroFallbackLabel: "Warm interior of a home",
    homeTabsLabel: "Sections of your home",
    homeTabKlussie: "Klussie", homeTabMyHome: "My Home", homeTabMyItems: "My Items",

    intentsLabel: "What is this about?",
    intentBroken: "Something is broken", intentImprove: "I want to improve something",
    intentMaintain: "I want to plan maintenance", intentAdvice: "I need advice",
    intentOther: "Something else",
    intentChosen: "Chosen", intentChange: "Choose something else",

    homeComposerPlaceholder: "Briefly describe what's going on…",
    homeVoiceAction: "Speak", homePhotoAction: "Add a photo", homeSendAction: "Send",
    homeAnswerLabel: "Your answer",
    followUpProgress: "Question {n} of {total}",
    followUpBack: "Previous question", followUpSkip: "Skip and send",

    safetyTitle: "This may not be safe",
    safetyBody: "Do you smell gas, see fire, is there standing water, or a danger from electricity? Call emergency services or your grid operator first. Klussie does not make a diagnosis.",
    safetyContinue: "Continue with my request anyway", safetyBack: "Back",

    todayHeading: "Today for your home",
    todayQuotesTitle: "Quotes are waiting for your choice",
    todayQuotesBody: "Review the quotes for {service} and choose who does the job.",
    todayBookedTitle: "Your job is scheduled",
    todayBookedBody: "{service} is booked. Your professional will keep you posted.",
    todayAwaitingTitle: "Your request is with one professional",
    todayAwaitingBody: "{service} — you'll hear from us as soon as they respond.",
    todayCollectingTitle: "Professionals are reviewing your request",
    todayCollectingBody: "{service} — quotes usually arrive within a few minutes.",
    todayReviewTitle: "Let us know how it went",
    todayReviewBody: "{service} is finished. Your review helps the next customer.",
    todayOpenCta: "View request",
    todayEmptyTitle: "Make your home smarter with Klussie",
    todayEmptyBody: "Add your first room, installation, or household item.",
    todayEmptyCta: "Set up my home",
    homeActiveTitle: "In progress right now",

    myHomeQuestion: "What would you like to see or keep track of about your home?",
    homeReportProblem: "Report a problem",
    myHomeNoPropertyYet: "As soon as you have something done through Klussie, your home's history starts building here.",
    myHomeKnownSince: "On Klussie since {date}",
    myHomeJobsSummary: "{total} requests, {completed} of them completed.",
    myHomeDoneBy: "Done by {name}",
    myHomeAiRead: "Klussie read",
    myHomeActiveTitle: "Happening now",
    myHomeActiveEmpty: "Nothing is in progress right now.",
    myHomeProsTitle: "Professionals who know your home",
    myHomeProsEmpty: "No professional has finished a job here yet.",
    myHomeOneJobTogether: "1 job together",
    myHomeJobsTogether: "{count} jobs together",
    myHomeHistoryTitle: "Your home's history",
    myHomeHistoryEmpty: "Once you complete a job through Klussie, it appears here.",
    myHomeReviewsTitle: "Your reviews",
    myHomeReviewsEmpty: "You haven't written a review yet.",
    myHomeAiTitle: "What Klussie understood",
    myHomeAiEmpty: "No AI analysis of a job yet.",
    myHomePhotosTitle: "Photos of your home",
    myHomePhotosEmpty: "No photos added to a request yet.",
    myHomePhotosLoading: "Loading photos…",

    myItemsQuestion: "What would you like to add or find again?",
    myItemsEmptyTitle: "You haven't added anything yet.",
    myItemsEmptyHint: "Add your boiler, washing machine or tools — then you'll know exactly which model you have when it matters.",
    myItemsLoading: "Loading your items…",
    myItemsLoadFailed: "We couldn't load your items. Please try again later.",
    myItemsRoomsTitle: "Rooms", myItemsRoomsEmpty: "No rooms added yet.",
    myItemsMaintenanceTitle: "Maintenance", myItemsMaintenanceEmpty: "Nothing scheduled or overdue.",
    myItemsMaintenanceOverdue: "Overdue", myItemsMaintenanceDueOn: "Due {date}",
    myItemsDocumentsTitle: "Documents", myItemsDocumentsEmpty: "No documents added yet.",
    myItemsDocumentExpired: "Expired", myItemsDocumentValidUntil: "Valid until {date}",
    homeBuilderTitle: "Rooms", homeBuilderLoading: "Loading rooms…",
    homeBuilderNoPropertyYet: "We're still setting up your home. Please check back soon.",
    homeBuilderEmptyTitle: "Start building your home",
    homeBuilderEmptyHint: "Add your first room — for example the kitchen or living room — and build from there.",
    homeBuilderAddFirstRoom: "Add your first room", homeBuilderAddAnotherRoom: "Add another room",
    locationEditTitle: "Edit room", locationSaveChanges: "Save changes",
    locationAddItemHere: "Add something to this room", locationRemove: "Remove room",
    locationRemoveConfirm: "Remove this room? This can't be undone.",
    locationRetireBlockedChildren: "This room still contains another room. Remove that one first.",
    locationRetireBlockedItems: "Something is still placed in this room. Remove or move it first.",
    locationFormAddTitle: "Add a room", locationFormNameLabel: "Name",
    locationFormNamePlaceholder: "e.g. Attic", locationFormTypeLabel: "Type (optional)",
    locationFormTypePlaceholder: "e.g. bedroom", locationFormParentLabel: "Inside (optional)",
    locationFormParentNone: "None — top level", locationFormSaveNew: "Save room",
    locationFormSaveFailed: "We couldn't save the room. Please try again later.",
    documentFormAddTitle: "Add a document", documentFormFileLabel: "File",
    documentFormFileAdd: "Choose file", documentFormTypeLabel: "Type",
    documentTypeWarranty: "Warranty", documentTypeCertificate: "Certificate",
    documentTypeManual: "Manual", documentTypeOther: "Other",
    documentTypePortfolioPhoto: "Portfolio photo", documentTypeRequestPhoto: "Request photo",
    documentFormIssuerLabel: "Issuer (optional)", documentFormValidUntilLabel: "Valid until (optional)",
    documentFormSaveNew: "Save document",
    documentFormSaveFailed: "We couldn't save the document. Please try again later.",
    myItemsOneItem: "1 item", myItemsCount: "{count} items",
    itemCatAppliance: "Appliances", itemCatElectronics: "Electronics",
    itemCatFurniture: "Furniture and lighting", itemCatGarden: "Garden",
    itemCatTool: "Tools", itemCatOther: "Other",
    itemRoomKitchen: "Kitchen", itemRoomLiving: "Living room", itemRoomBedroom: "Bedroom",
    itemRoomBathroom: "Bathroom", itemRoomGarage: "Garage", itemRoomGarden: "Garden",
    itemRoomAttic: "Attic", itemRoomBasement: "Basement",
    itemAddTitle: "Add an item", itemEditTitle: "Edit item",
    itemNameLabel: "What is it?", itemNamePlaceholder: "e.g. washing machine",
    itemCategoryLabel: "Kind", itemRoomLabel: "Where is it?", itemRoomPlaceholder: "e.g. kitchen",
    itemRoomNone: "No room selected",
    itemBrandLabel: "Brand (optional)", itemModelLabel: "Model (optional)",
    itemPhotoLabel: "Photo (optional)", itemPhotoAdd: "Add a photo", itemPhotoRemove: "Remove photo",
    itemPurchasedLabel: "Bought on (optional)", itemNotesLabel: "Notes (optional)",
    itemSaveNew: "Save item", itemSaveChanges: "Save changes",
    itemDelete: "Delete item",
    itemDeleteConfirm: "Delete this item? This can't be undone.",

    tourTitle: "A quick tour of Klussie",
    tourProgress: "Step {n} of {total}",
    tourStep1Title: "Tell or show us what's going on",
    tourStep1Body: "Use text, your voice, or a photo.",
    tourStep2Title: "Klussie asks the right questions",
    tourStep2Body: "Together we turn it into a clear request.",
    tourStep3Title: "Keep everything about your home",
    tourStep3Body: "Track rooms, installations, documents, and maintenance.",
    tourStep4Title: "Track your items and guarantees",
    tourStep4Body: "Keep products, receipts, manuals, and guarantees.",
    proTourStep0Title: "Welcome", proTourStep0Body: "Every job you're about to see is a chance to do what you're good at — and get paid fairly for it. Let me show you around.",
    proTourStep1Title: "Dashboard", proTourStep1Body: "The moment a nearby customer needs exactly what you offer, you'll see it here — not by chance, because it matches you.",
    proTourStep2Title: "My jobs", proTourStep2Body: "Every quote you send, every job you book, from proposal to paid — all in one place.",
    proTourStep3Title: "Messages", proTourStep3Body: "Talk directly with your customer, no swapping numbers.",
    proTourStep4Title: "Your pace, your choice", proTourStep4Body: "No time right now? Pause yourself here — you don't disappear, you're just temporarily not visible for new jobs.",
    proTourStep5Title: "That's it", proTourStep5Body: "The leads come to you — you choose what you take on.",
    proTourDoneCta: "Go to dashboard",
    tourNext: "Next", tourBack: "Back", tourSkip: "Skip",
    tourStartCta: "Start with Klussie", tourSetupHomeCta: "Set up my home first",
    helpSectionTitle: "Help & explanation", helpReplayTour: "Watch the tour again",
  },

  es: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "¿En qué puede ayudarte Klussie hoy?",
    homeHeroFallbackLabel: "Interior cálido de una vivienda",
    homeTabsLabel: "Partes de tu vivienda",
    homeTabKlussie: "Klussie", homeTabMyHome: "Mi vivienda", homeTabMyItems: "Mis cosas",

    intentsLabel: "¿De qué se trata?",
    intentBroken: "Algo está roto", intentImprove: "Quiero mejorar algo",
    intentMaintain: "Quiero planificar un mantenimiento", intentAdvice: "Necesito consejo",
    intentOther: "Otra cosa",
    intentChosen: "Elegido", intentChange: "Elegir otra cosa",

    homeComposerPlaceholder: "Describe brevemente qué ocurre…",
    homeVoiceAction: "Hablar", homePhotoAction: "Añadir una foto", homeSendAction: "Enviar",
    homeAnswerLabel: "Tu respuesta",
    followUpProgress: "Pregunta {n} de {total}",
    followUpBack: "Pregunta anterior", followUpSkip: "Saltar y enviar",

    safetyTitle: "Esto podría no ser seguro",
    safetyBody: "¿Hueles a gas, ves fuego, hay agua acumulada o riesgo eléctrico? Llama primero a los servicios de emergencia o a tu distribuidora. Klussie no hace diagnósticos.",
    safetyContinue: "Continuar igualmente con mi solicitud", safetyBack: "Volver",

    todayHeading: "Hoy para tu vivienda",
    todayQuotesTitle: "Hay presupuestos esperando tu decisión",
    todayQuotesBody: "Revisa los presupuestos de {service} y elige quién hace el trabajo.",
    todayBookedTitle: "Tu trabajo está programado",
    todayBookedBody: "{service} está reservado. Tu profesional te irá informando.",
    todayAwaitingTitle: "Tu solicitud está con un profesional",
    todayAwaitingBody: "{service} — te avisaremos en cuanto responda.",
    todayCollectingTitle: "Los profesionales están revisando tu solicitud",
    todayCollectingBody: "{service} — los presupuestos suelen llegar en unos minutos.",
    todayReviewTitle: "Cuéntanos qué tal fue",
    todayReviewBody: "{service} ha terminado. Tu valoración ayuda al siguiente cliente.",
    todayOpenCta: "Ver solicitud",
    todayEmptyTitle: "Haz tu vivienda más inteligente con Klussie",
    todayEmptyBody: "Añade tu primera habitación, instalación u objeto del hogar.",
    todayEmptyCta: "Configurar mi vivienda",
    homeActiveTitle: "En curso ahora mismo",

    myHomeQuestion: "¿Qué quieres consultar o registrar sobre tu vivienda?",
    homeReportProblem: "Informar de un problema",
    myHomeNoPropertyYet: "En cuanto hagas algo a través de Klussie, aquí empezará a construirse la historia de tu vivienda.",
    myHomeKnownSince: "En Klussie desde el {date}",
    myHomeJobsSummary: "{total} solicitudes, {completed} de ellas completadas.",
    myHomeDoneBy: "Realizado por {name}",
    myHomeAiRead: "Klussie entendió",
    myHomeActiveTitle: "Ahora mismo",
    myHomeActiveEmpty: "Ahora mismo no hay nada en curso.",
    myHomeProsTitle: "Profesionales que conocen tu vivienda",
    myHomeProsEmpty: "Todavía ningún profesional ha terminado un trabajo aquí.",
    myHomeOneJobTogether: "1 trabajo juntos",
    myHomeJobsTogether: "{count} trabajos juntos",
    myHomeHistoryTitle: "Historia de tu vivienda",
    myHomeHistoryEmpty: "Cuando termines un trabajo con Klussie, aparecerá aquí.",
    myHomeReviewsTitle: "Tus valoraciones",
    myHomeReviewsEmpty: "Todavía no has escrito ninguna valoración.",
    myHomeAiTitle: "Lo que Klussie entendió",
    myHomeAiEmpty: "Todavía no hay ningún análisis de IA de un trabajo.",
    myHomePhotosTitle: "Fotos de tu vivienda",
    myHomePhotosEmpty: "Todavía no has añadido fotos a ninguna solicitud.",
    myHomePhotosLoading: "Cargando fotos…",

    myItemsQuestion: "¿Qué quieres añadir o volver a encontrar?",
    myItemsEmptyTitle: "Todavía no has añadido nada.",
    myItemsEmptyHint: "Añade tu caldera, tu lavadora o tus herramientas — así sabrás exactamente qué modelo tienes cuando haga falta.",
    myItemsLoading: "Cargando tus cosas…",
    myItemsLoadFailed: "No hemos podido cargar tus cosas. Inténtalo de nuevo más tarde.",
    myItemsRoomsTitle: "Habitaciones", myItemsRoomsEmpty: "Todavía no has añadido habitaciones.",
    myItemsMaintenanceTitle: "Mantenimiento", myItemsMaintenanceEmpty: "Nada programado ni atrasado.",
    myItemsMaintenanceOverdue: "Atrasado", myItemsMaintenanceDueOn: "Vence el {date}",
    myItemsDocumentsTitle: "Documentos", myItemsDocumentsEmpty: "Todavía no has añadido documentos.",
    myItemsDocumentExpired: "Caducado", myItemsDocumentValidUntil: "Válido hasta {date}",
    homeBuilderTitle: "Habitaciones", homeBuilderLoading: "Cargando habitaciones…",
    homeBuilderNoPropertyYet: "Todavía estamos configurando tu vivienda. Vuelve a intentarlo pronto.",
    homeBuilderEmptyTitle: "Empieza a construir tu vivienda",
    homeBuilderEmptyHint: "Añade tu primera habitación — por ejemplo la cocina o el salón — y sigue construyendo desde ahí.",
    homeBuilderAddFirstRoom: "Añadir tu primera habitación", homeBuilderAddAnotherRoom: "Añadir otra habitación",
    locationEditTitle: "Editar habitación", locationSaveChanges: "Guardar cambios",
    locationAddItemHere: "Añadir algo en esta habitación", locationRemove: "Eliminar habitación",
    locationRemoveConfirm: "¿Eliminar esta habitación? Esta acción no se puede deshacer.",
    locationRetireBlockedChildren: "Esta habitación todavía contiene otra habitación. Elimínala primero.",
    locationRetireBlockedItems: "Todavía hay algo en esta habitación. Elimínalo o muévelo primero.",
    locationFormAddTitle: "Añadir una habitación", locationFormNameLabel: "Nombre",
    locationFormNamePlaceholder: "p. ej. Desván", locationFormTypeLabel: "Tipo (opcional)",
    locationFormTypePlaceholder: "p. ej. dormitorio", locationFormParentLabel: "Dentro de (opcional)",
    locationFormParentNone: "Ninguno — nivel superior", locationFormSaveNew: "Guardar habitación",
    locationFormSaveFailed: "No hemos podido guardar la habitación. Inténtalo de nuevo más tarde.",
    documentFormAddTitle: "Añadir un documento", documentFormFileLabel: "Archivo",
    documentFormFileAdd: "Elegir archivo", documentFormTypeLabel: "Tipo",
    documentTypeWarranty: "Garantía", documentTypeCertificate: "Certificado",
    documentTypeManual: "Manual", documentTypeOther: "Otro",
    documentTypePortfolioPhoto: "Foto de portafolio", documentTypeRequestPhoto: "Foto de la solicitud",
    documentFormIssuerLabel: "Emisor (opcional)", documentFormValidUntilLabel: "Válido hasta (opcional)",
    documentFormSaveNew: "Guardar documento",
    documentFormSaveFailed: "No hemos podido guardar el documento. Inténtalo de nuevo más tarde.",
    myItemsOneItem: "1 objeto", myItemsCount: "{count} objetos",
    itemCatAppliance: "Electrodomésticos", itemCatElectronics: "Electrónica",
    itemCatFurniture: "Muebles e iluminación", itemCatGarden: "Jardín",
    itemCatTool: "Herramientas", itemCatOther: "Otros",
    itemRoomKitchen: "Cocina", itemRoomLiving: "Salón", itemRoomBedroom: "Dormitorio",
    itemRoomBathroom: "Baño", itemRoomGarage: "Garaje", itemRoomGarden: "Jardín",
    itemRoomAttic: "Ático", itemRoomBasement: "Sótano",
    itemAddTitle: "Añadir un objeto", itemEditTitle: "Editar objeto",
    itemNameLabel: "¿Qué es?", itemNamePlaceholder: "p. ej. lavadora",
    itemCategoryLabel: "Tipo", itemRoomLabel: "¿Dónde está?", itemRoomPlaceholder: "p. ej. cocina",
    itemRoomNone: "Ninguna habitación seleccionada",
    itemBrandLabel: "Marca (opcional)", itemModelLabel: "Modelo (opcional)",
    itemPhotoLabel: "Foto (opcional)", itemPhotoAdd: "Añadir una foto", itemPhotoRemove: "Quitar la foto",
    itemPurchasedLabel: "Comprado el (opcional)", itemNotesLabel: "Notas (opcional)",
    itemSaveNew: "Guardar objeto", itemSaveChanges: "Guardar cambios",
    itemDelete: "Eliminar objeto",
    itemDeleteConfirm: "¿Eliminar este objeto? Esta acción no se puede deshacer.",

    tourTitle: "Un recorrido rápido por Klussie",
    tourProgress: "Paso {n} de {total}",
    tourStep1Title: "Cuéntanos o enséñanos qué ocurre",
    tourStep1Body: "Usa texto, tu voz o una foto.",
    tourStep2Title: "Klussie hace las preguntas adecuadas",
    tourStep2Body: "Juntos lo convertimos en una solicitud clara.",
    tourStep3Title: "Guarda todo sobre tu vivienda",
    tourStep3Body: "Registra habitaciones, instalaciones, documentos y mantenimiento.",
    tourStep4Title: "Controla tus objetos y garantías",
    tourStep4Body: "Guarda productos, recibos, manuales y garantías.",
    proTourStep0Title: "Bienvenido", proTourStep0Body: "Cada trabajo que vas a ver es una oportunidad de hacer lo que se te da bien — y que te paguen justamente por ello. Déjame enseñarte cómo funciona.",
    proTourStep1Title: "Panel", proTourStep1Body: "En cuanto un cliente cercano busque exactamente lo que ofreces, lo verás aquí — no por casualidad, sino porque encaja contigo.",
    proTourStep2Title: "Mis trabajos", proTourStep2Body: "Cada presupuesto que envías, cada trabajo que reservas, desde la propuesta hasta el pago — todo en un solo lugar.",
    proTourStep3Title: "Mensajes", proTourStep3Body: "Habla directamente con tu cliente, sin intercambiar números.",
    proTourStep4Title: "Tu ritmo, tu elección", proTourStep4Body: "¿Sin tiempo ahora mismo? Ponte en pausa aquí — no desapareces, solo dejas de ser visible temporalmente para trabajos nuevos.",
    proTourStep5Title: "Eso es todo", proTourStep5Body: "Los trabajos vienen a ti — tú eliges cuáles aceptas.",
    proTourDoneCta: "Ir al panel",
    tourNext: "Siguiente", tourBack: "Atrás", tourSkip: "Saltar",
    tourStartCta: "Empezar con Klussie",
    tourSetupHomeCta: "Configurar primero mi vivienda",

    helpSectionTitle: "Ayuda y explicación",
    helpReplayTour: "Volver a ver el recorrido",
  },
  ar: {
    homeGreetName: "{greeting}، {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "بماذا يمكن أن يساعدك Klussie اليوم؟",
    homeHeroFallbackLabel: "منزل دافئ من الداخل",
    homeTabsLabel: "أقسام منزلك",
    homeTabKlussie: "Klussie", homeTabMyHome: "منزلي", homeTabMyItems: "أغراضي",

    intentsLabel: "عن ماذا يدور الأمر؟",
    intentBroken: "هناك شيء معطّل", intentImprove: "أريد تحسين شيء ما",
    intentMaintain: "أريد جدولة صيانة", intentAdvice: "أحتاج إلى نصيحة",
    intentOther: "شيء آخر",
    intentChosen: "تم الاختيار", intentChange: "اختر شيئًا آخر",

    homeComposerPlaceholder: "صف باختصار ما الذي يحدث…",
    homeVoiceAction: "تحدّث", homePhotoAction: "أضف صورة", homeSendAction: "إرسال",
    homeAnswerLabel: "إجابتك",
    followUpProgress: "السؤال {n} من {total}",
    followUpBack: "السؤال السابق", followUpSkip: "تخطَّ وأرسل",

    safetyTitle: "قد لا يكون هذا آمنًا",
    safetyBody: "هل تشمّ غازًا، أو ترى نارًا، أو هناك مياه راكدة أو خطر كهربائي؟ اتصل أولًا بخدمات الطوارئ أو بمشغّل الشبكة. Klussie لا يقدّم تشخيصًا.",
    safetyContinue: "المتابعة بطلبي على أي حال", safetyBack: "رجوع",

    todayHeading: "اليوم من أجل منزلك",
    todayQuotesTitle: "عروض أسعار بانتظار اختيارك",
    todayQuotesBody: "راجع عروض {service} واختر من سينفّذ العمل.",
    todayBookedTitle: "تم جدولة مهمتك",
    todayBookedBody: "تم حجز {service}. سيبقيك الحرفي على اطّلاع.",
    todayAwaitingTitle: "طلبك لدى حرفي واحد",
    todayAwaitingBody: "{service} — سنخبرك حالما يردّ.",
    todayCollectingTitle: "الحرفيون يراجعون طلبك",
    todayCollectingBody: "{service} — تصل العروض عادةً خلال دقائق.",
    todayReviewTitle: "أخبرنا كيف سارت الأمور",
    todayReviewBody: "اكتمل {service}. تقييمك يساعد العميل التالي.",
    todayOpenCta: "عرض الطلب",
    todayEmptyTitle: "اجعل منزلك أذكى مع Klussie",
    todayEmptyBody: "أضف أول غرفة أو تركيبة أو غرض منزلي.",
    todayEmptyCta: "إعداد منزلي",
    homeActiveTitle: "قيد التنفيذ الآن",

    myHomeQuestion: "ما الذي تريد الاطلاع عليه أو تتبعه بشأن منزلك؟",
    homeReportProblem: "الإبلاغ عن مشكلة",
    myHomeNoPropertyYet: "بمجرد أن تنجز شيئًا عبر Klussie، يبدأ تاريخ منزلك بالتكوّن هنا.",
    myHomeKnownSince: "على Klussie منذ {date}",
    myHomeJobsSummary: "{total} طلبات، منها {completed} مكتملة.",
    myHomeDoneBy: "نفّذها {name}",
    myHomeAiRead: "فهم Klussie",
    myHomeActiveTitle: "يجري الآن",
    myHomeActiveEmpty: "لا شيء قيد التنفيذ حاليًا.",
    myHomeProsTitle: "محترفون يعرفون منزلك",
    myHomeProsEmpty: "لم يُنهِ أي محترف عملًا هنا بعد.",
    myHomeOneJobTogether: "عمل واحد معًا",
    myHomeJobsTogether: "{count} أعمال معًا",
    myHomeHistoryTitle: "تاريخ منزلك",
    myHomeHistoryEmpty: "بمجرد إتمام عمل عبر Klussie، سيظهر هنا.",
    myHomeReviewsTitle: "تقييماتك",
    myHomeReviewsEmpty: "لم تكتب أي تقييم بعد.",
    myHomeAiTitle: "ما فهمه Klussie",
    myHomeAiEmpty: "لا يوجد تحليل بالذكاء الاصطناعي بعد.",
    myHomePhotosTitle: "صور منزلك",
    myHomePhotosEmpty: "لم تُضف أي صور إلى طلب بعد.",
    myHomePhotosLoading: "جارٍ تحميل الصور…",

    myItemsQuestion: "ما الذي تريد إضافته أو العثور عليه؟",
    myItemsEmptyTitle: "لم تضف شيئًا بعد.",
    myItemsEmptyHint: "أضف السخّان أو الغسالة أو أدواتك — لتعرف لاحقًا الطراز بالضبط عند الحاجة.",
    myItemsLoading: "جارٍ تحميل أغراضك…",
    myItemsLoadFailed: "تعذّر تحميل أغراضك. حاول مرة أخرى لاحقًا.",
    myItemsRoomsTitle: "الغرف", myItemsRoomsEmpty: "لم تتم إضافة أي غرف بعد.",
    myItemsMaintenanceTitle: "الصيانة", myItemsMaintenanceEmpty: "لا شيء مجدوَل أو متأخر.",
    myItemsMaintenanceOverdue: "متأخر", myItemsMaintenanceDueOn: "الموعد المحدد {date}",
    myItemsDocumentsTitle: "المستندات", myItemsDocumentsEmpty: "لم تتم إضافة أي مستندات بعد.",
    myItemsDocumentExpired: "منتهي الصلاحية", myItemsDocumentValidUntil: "صالح حتى {date}",
    homeBuilderTitle: "الغرف", homeBuilderLoading: "جارٍ تحميل الغرف…",
    homeBuilderNoPropertyYet: "ما زلنا نُعِدّ منزلك. يُرجى المحاولة مرة أخرى قريبًا.",
    homeBuilderEmptyTitle: "ابدأ ببناء منزلك",
    homeBuilderEmptyHint: "أضف أول غرفة — مثل المطبخ أو غرفة المعيشة — وابنِ من هناك.",
    homeBuilderAddFirstRoom: "إضافة أول غرفة", homeBuilderAddAnotherRoom: "إضافة غرفة أخرى",
    locationEditTitle: "تعديل الغرفة", locationSaveChanges: "حفظ التغييرات",
    locationAddItemHere: "إضافة شيء في هذه الغرفة", locationRemove: "حذف الغرفة",
    locationRemoveConfirm: "هل تريد حذف هذه الغرفة؟ لا يمكن التراجع عن ذلك.",
    locationRetireBlockedChildren: "لا تزال هذه الغرفة تحتوي على غرفة أخرى. احذف تلك الغرفة أولاً.",
    locationRetireBlockedItems: "لا يزال هناك شيء في هذه الغرفة. احذفه أو انقله أولاً.",
    locationFormAddTitle: "إضافة غرفة", locationFormNameLabel: "الاسم",
    locationFormNamePlaceholder: "مثال: العلية", locationFormTypeLabel: "النوع (اختياري)",
    locationFormTypePlaceholder: "مثال: غرفة نوم", locationFormParentLabel: "داخل (اختياري)",
    locationFormParentNone: "لا شيء — المستوى الأعلى", locationFormSaveNew: "حفظ الغرفة",
    locationFormSaveFailed: "تعذّر حفظ الغرفة. حاول مرة أخرى لاحقًا.",
    documentFormAddTitle: "إضافة مستند", documentFormFileLabel: "الملف",
    documentFormFileAdd: "اختيار ملف", documentFormTypeLabel: "النوع",
    documentTypeWarranty: "الضمان", documentTypeCertificate: "الشهادة",
    documentTypeManual: "الدليل", documentTypeOther: "أخرى",
    documentTypePortfolioPhoto: "صورة من الأعمال السابقة", documentTypeRequestPhoto: "صورة الطلب",
    documentFormIssuerLabel: "الجهة المصدرة (اختياري)", documentFormValidUntilLabel: "صالح حتى (اختياري)",
    documentFormSaveNew: "حفظ المستند",
    documentFormSaveFailed: "تعذّر حفظ المستند. حاول مرة أخرى لاحقًا.",
    myItemsOneItem: "غرض واحد", myItemsCount: "{count} أغراض",
    itemCatAppliance: "الأجهزة", itemCatElectronics: "الإلكترونيات",
    itemCatFurniture: "الأثاث والإضاءة", itemCatGarden: "الحديقة",
    itemCatTool: "الأدوات", itemCatOther: "أخرى",
    itemRoomKitchen: "المطبخ", itemRoomLiving: "غرفة المعيشة", itemRoomBedroom: "غرفة النوم",
    itemRoomBathroom: "الحمّام", itemRoomGarage: "المرآب", itemRoomGarden: "الحديقة",
    itemRoomAttic: "العلّية", itemRoomBasement: "القبو",
    itemAddTitle: "إضافة غرض", itemEditTitle: "تعديل الغرض",
    itemNameLabel: "ما هو؟", itemNamePlaceholder: "مثال: غسالة",
    itemCategoryLabel: "النوع", itemRoomLabel: "أين يوجد؟", itemRoomPlaceholder: "مثال: المطبخ",
    itemRoomNone: "لم يتم اختيار غرفة",
    itemBrandLabel: "الماركة (اختياري)", itemModelLabel: "الطراز (اختياري)",
    itemPhotoLabel: "صورة (اختياري)", itemPhotoAdd: "إضافة صورة", itemPhotoRemove: "إزالة الصورة",
    itemPurchasedLabel: "تاريخ الشراء (اختياري)", itemNotesLabel: "ملاحظات (اختياري)",
    itemSaveNew: "حفظ الغرض", itemSaveChanges: "حفظ التغييرات",
    itemDelete: "حذف الغرض",
    itemDeleteConfirm: "هل تريد حذف هذا الغرض؟ لا يمكن التراجع عن ذلك.",

    tourTitle: "جولة سريعة في Klussie",
    tourProgress: "الخطوة {n} من {total}",
    tourStep1Title: "احكِ أو أرِنا ما الذي يحدث",
    tourStep1Body: "استخدم النص أو صوتك أو صورة.",
    tourStep2Title: "يطرح Klussie الأسئلة الصحيحة",
    tourStep2Body: "معًا نحوّلها إلى طلب واضح.",
    tourStep3Title: "احتفظ بكل شيء عن منزلك",
    tourStep3Body: "تتبّع الغرف والتركيبات والمستندات والصيانة.",
    tourStep4Title: "تتبّع أغراضك وضماناتك",
    tourStep4Body: "احتفظ بالمنتجات وإثباتات الشراء والأدلة والضمانات.",
    proTourStep0Title: "أهلاً بك", proTourStep0Body: "كل عمل ستراه الآن هو فرصة لتفعل ما تجيده — وتُدفع لك أجرة عادلة مقابله. دعني أُريك الأساسيات.",
    proTourStep1Title: "لوحة التحكم", proTourStep1Body: "بمجرد أن يبحث عميل قريب عن بالضبط ما تقدمه، ستراه هنا — ليس بالصدفة، بل لأنه يناسبك.",
    proTourStep2Title: "أعمالي", proTourStep2Body: "كل عرض ترسله، وكل عمل تحجزه، من العرض حتى الدفع — كل ذلك في مكان واحد.",
    proTourStep3Title: "الرسائل", proTourStep3Body: "تحدث مباشرة مع عميلك، دون تبادل الأرقام.",
    proTourStep4Title: "وتيرتك، اختيارك", proTourStep4Body: "لا وقت لديك الآن؟ ضع نفسك في وضع الإيقاف المؤقت هنا — لن تختفي، فقط لن تكون مرئيًا مؤقتًا للأعمال الجديدة.",
    proTourStep5Title: "هذا كل شيء", proTourStep5Body: "الأعمال تأتي إليك — أنت من يختار ما تقبله.",
    proTourDoneCta: "الذهاب إلى لوحة التحكم",
    tourNext: "التالي", tourBack: "السابق", tourSkip: "تخطّي",
    tourStartCta: "ابدأ مع Klussie", tourSetupHomeCta: "إعداد منزلي أولًا",
    helpSectionTitle: "المساعدة والشرح", helpReplayTour: "إعادة مشاهدة الجولة",
  },

  fa: {
    homeGreetName: "{greeting}، {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "امروز Klussie چطور می‌تواند کمکتان کند؟",
    homeHeroFallbackLabel: "فضای داخلی گرم یک خانه",
    homeTabsLabel: "بخش‌های خانه شما",
    homeTabKlussie: "Klussie", homeTabMyHome: "خانه من", homeTabMyItems: "وسایل من",

    intentsLabel: "موضوع چیست؟",
    intentBroken: "چیزی خراب شده", intentImprove: "می‌خواهم چیزی را بهتر کنم",
    intentMaintain: "می‌خواهم سرویس دوره‌ای برنامه‌ریزی کنم", intentAdvice: "به مشورت نیاز دارم",
    intentOther: "چیز دیگری",
    intentChosen: "انتخاب‌شده", intentChange: "انتخاب چیز دیگر",

    homeComposerPlaceholder: "کوتاه بنویسید چه اتفاقی افتاده…",
    homeVoiceAction: "گفتن", homePhotoAction: "افزودن عکس", homeSendAction: "ارسال",
    homeAnswerLabel: "پاسخ شما",
    followUpProgress: "پرسش {n} از {total}",
    followUpBack: "پرسش قبلی", followUpSkip: "رد کردن و ارسال",

    safetyTitle: "این وضعیت ممکن است خطرناک باشد",
    safetyBody: "بوی گاز می‌آید، آتش می‌بینید، آب جمع شده یا خطر برق‌گرفتگی هست؟ ابتدا با اورژانس یا شرکت خدمات تماس بگیرید. Klussie تشخیص پزشکی یا فنی نمی‌دهد.",
    safetyContinue: "با این حال درخواستم را ادامه بده", safetyBack: "بازگشت",

    todayHeading: "امروز برای خانه شما",
    todayQuotesTitle: "پیشنهادهای قیمت منتظر انتخاب شماست",
    todayQuotesBody: "پیشنهادهای {service} را ببینید و انتخاب کنید چه کسی کار را انجام دهد.",
    todayBookedTitle: "کار شما زمان‌بندی شد",
    todayBookedBody: "{service} رزرو شد. متخصص شما در جریان می‌گذاردتان.",
    todayAwaitingTitle: "درخواست شما نزد یک متخصص است",
    todayAwaitingBody: "{service} — به‌محض پاسخ او خبرتان می‌کنیم.",
    todayCollectingTitle: "متخصصان در حال بررسی درخواست شما هستند",
    todayCollectingBody: "{service} — پیشنهادها معمولاً ظرف چند دقیقه می‌رسند.",
    todayReviewTitle: "بگویید کار چطور بود",
    todayReviewBody: "{service} تمام شد. نظر شما به مشتری بعدی کمک می‌کند.",
    todayOpenCta: "دیدن درخواست",
    todayEmptyTitle: "خانه‌تان را با Klussie هوشمندتر کنید",
    todayEmptyBody: "اولین اتاق، تجهیزات یا وسیله خانه‌تان را اضافه کنید.",
    todayEmptyCta: "تنظیم خانه من",
    homeActiveTitle: "همین حالا در جریان",

    myHomeQuestion: "می‌خواهید چه چیزی از خانه‌تان را ببینید یا ثبت کنید؟",
    homeReportProblem: "گزارش مشکل",
    myHomeNoPropertyYet: "به‌محض اینکه کاری را از طریق Klussie انجام دهید، تاریخچه خانه‌تان اینجا شکل می‌گیرد.",
    myHomeKnownSince: "در Klussie از {date}",
    myHomeJobsSummary: "{total} درخواست، که {completed} مورد آن تکمیل شده است.",
    myHomeDoneBy: "انجام‌شده توسط {name}",
    myHomeAiRead: "برداشت Klussie",
    myHomeActiveTitle: "همین حالا",
    myHomeActiveEmpty: "در حال حاضر چیزی در جریان نیست.",
    myHomeProsTitle: "متخصصانی که خانه شما را می‌شناسند",
    myHomeProsEmpty: "هنوز هیچ متخصصی اینجا کاری را تمام نکرده است.",
    myHomeOneJobTogether: "۱ کار مشترک",
    myHomeJobsTogether: "{count} کار مشترک",
    myHomeHistoryTitle: "تاریخچه خانه شما",
    myHomeHistoryEmpty: "وقتی کاری را از طریق Klussie تمام کنید، اینجا نمایش داده می‌شود.",
    myHomeReviewsTitle: "نظرهای شما",
    myHomeReviewsEmpty: "هنوز نظری ننوشته‌اید.",
    myHomeAiTitle: "آنچه Klussie فهمید",
    myHomeAiEmpty: "هنوز تحلیل هوش مصنوعی برای کاری وجود ندارد.",
    myHomePhotosTitle: "عکس‌های خانه شما",
    myHomePhotosEmpty: "هنوز عکسی به هیچ درخواستی اضافه نشده است.",
    myHomePhotosLoading: "در حال بارگذاری عکس‌ها…",

    myItemsQuestion: "می‌خواهید چه چیزی اضافه کنید یا دوباره پیدا کنید؟",
    myItemsEmptyTitle: "هنوز چیزی اضافه نکرده‌اید.",
    myItemsEmptyHint: "پکیج، ماشین لباسشویی یا ابزارتان را اضافه کنید — بعداً دقیقاً می‌دانید چه مدلی دارید.",
    myItemsLoading: "در حال بارگذاری وسایل شما…",
    myItemsLoadFailed: "نتوانستیم وسایل شما را بارگذاری کنیم. بعداً دوباره تلاش کنید.",
    myItemsRoomsTitle: "اتاق‌ها", myItemsRoomsEmpty: "هنوز اتاقی اضافه نشده است.",
    myItemsMaintenanceTitle: "نگهداری", myItemsMaintenanceEmpty: "چیزی برنامه‌ریزی‌شده یا عقب‌افتاده نیست.",
    myItemsMaintenanceOverdue: "عقب‌افتاده", myItemsMaintenanceDueOn: "موعد: {date}",
    myItemsDocumentsTitle: "مدارک", myItemsDocumentsEmpty: "هنوز مدرکی اضافه نشده است.",
    myItemsDocumentExpired: "منقضی‌شده", myItemsDocumentValidUntil: "اعتبار تا {date}",
    homeBuilderTitle: "اتاق‌ها", homeBuilderLoading: "در حال بارگذاری اتاق‌ها…",
    homeBuilderNoPropertyYet: "ما هنوز خانه شما را تنظیم می‌کنیم. لطفاً کمی بعد دوباره سر بزنید.",
    homeBuilderEmptyTitle: "ساخت خانه‌تان را شروع کنید",
    homeBuilderEmptyHint: "اولین اتاق خود را اضافه کنید — مثلاً آشپزخانه یا اتاق نشیمن — و از همان‌جا ادامه دهید.",
    homeBuilderAddFirstRoom: "افزودن اولین اتاق", homeBuilderAddAnotherRoom: "افزودن اتاق دیگر",
    locationEditTitle: "ویرایش اتاق", locationSaveChanges: "ذخیره تغییرات",
    locationAddItemHere: "افزودن چیزی به این اتاق", locationRemove: "حذف اتاق",
    locationRemoveConfirm: "این اتاق حذف شود؟ این کار قابل بازگشت نیست.",
    locationRetireBlockedChildren: "این اتاق هنوز شامل اتاق دیگری است. ابتدا آن را حذف کنید.",
    locationRetireBlockedItems: "هنوز چیزی در این اتاق قرار دارد. ابتدا آن را حذف یا جابه‌جا کنید.",
    locationFormAddTitle: "افزودن اتاق", locationFormNameLabel: "نام",
    locationFormNamePlaceholder: "مثلاً: اتاق زیرشیروانی", locationFormTypeLabel: "نوع (اختیاری)",
    locationFormTypePlaceholder: "مثلاً: اتاق خواب", locationFormParentLabel: "داخل (اختیاری)",
    locationFormParentNone: "هیچ‌کدام — سطح بالا", locationFormSaveNew: "ذخیره اتاق",
    locationFormSaveFailed: "نتوانستیم اتاق را ذخیره کنیم. بعداً دوباره تلاش کنید.",
    documentFormAddTitle: "افزودن مدرک", documentFormFileLabel: "فایل",
    documentFormFileAdd: "انتخاب فایل", documentFormTypeLabel: "نوع",
    documentTypeWarranty: "گارانتی", documentTypeCertificate: "گواهی",
    documentTypeManual: "دفترچه راهنما", documentTypeOther: "دیگر",
    documentTypePortfolioPhoto: "عکس نمونه‌کار", documentTypeRequestPhoto: "عکس درخواست",
    documentFormIssuerLabel: "صادرکننده (اختیاری)", documentFormValidUntilLabel: "اعتبار تا (اختیاری)",
    documentFormSaveNew: "ذخیره مدرک",
    documentFormSaveFailed: "نتوانستیم مدرک را ذخیره کنیم. بعداً دوباره تلاش کنید.",
    myItemsOneItem: "۱ مورد", myItemsCount: "{count} مورد",
    itemCatAppliance: "لوازم خانگی", itemCatElectronics: "لوازم الکترونیکی",
    itemCatFurniture: "مبلمان و روشنایی", itemCatGarden: "باغچه",
    itemCatTool: "ابزار", itemCatOther: "سایر",
    itemRoomKitchen: "آشپزخانه", itemRoomLiving: "اتاق نشیمن", itemRoomBedroom: "اتاق خواب",
    itemRoomBathroom: "حمام", itemRoomGarage: "پارکینگ", itemRoomGarden: "باغچه",
    itemRoomAttic: "زیرشیروانی", itemRoomBasement: "زیرزمین",
    itemAddTitle: "افزودن وسیله", itemEditTitle: "ویرایش وسیله",
    itemNameLabel: "این چیست؟", itemNamePlaceholder: "مثلاً ماشین لباسشویی",
    itemCategoryLabel: "نوع", itemRoomLabel: "کجاست؟", itemRoomPlaceholder: "مثلاً آشپزخانه",
    itemRoomNone: "اتاقی انتخاب نشده است",
    itemBrandLabel: "برند (اختیاری)", itemModelLabel: "مدل (اختیاری)",
    itemPhotoLabel: "عکس (اختیاری)", itemPhotoAdd: "افزودن عکس", itemPhotoRemove: "حذف عکس",
    itemPurchasedLabel: "تاریخ خرید (اختیاری)", itemNotesLabel: "یادداشت (اختیاری)",
    itemSaveNew: "ذخیره وسیله", itemSaveChanges: "ذخیره تغییرات",
    itemDelete: "حذف وسیله",
    itemDeleteConfirm: "این وسیله حذف شود؟ این کار قابل بازگشت نیست.",

    tourTitle: "یک راهنمای کوتاه Klussie",
    tourProgress: "گام {n} از {total}",
    tourStep1Title: "بگویید یا نشان دهید چه خبر است",
    tourStep1Body: "با متن، صدا یا عکس.",
    tourStep2Title: "Klussie پرسش‌های درست را می‌پرسد",
    tourStep2Body: "با هم آن را به یک درخواست روشن تبدیل می‌کنیم.",
    tourStep3Title: "همه‌چیز خانه‌تان را نگه دارید",
    tourStep3Body: "اتاق‌ها، تجهیزات، مدارک و سرویس‌ها را ثبت کنید.",
    tourStep4Title: "وسایل و گارانتی‌هایتان را پیگیری کنید",
    tourStep4Body: "محصولات، رسیدها، دفترچه‌ها و گارانتی‌ها را نگه دارید.",
    proTourStep0Title: "خوش آمدید", proTourStep0Body: "هر کاری که الان می‌بینید فرصتی است برای انجام کاری که در آن مهارت دارید — و دستمزد منصفانه دریافت کنید. بگذارید اطراف را نشانتان بدهم.",
    proTourStep1Title: "داشبورد", proTourStep1Body: "به‌محض اینکه مشتری‌ای در نزدیکی دقیقاً همان چیزی را که ارائه می‌دهید بخواهد، اینجا می‌بینیدش — نه اتفاقی، بلکه چون با شما تناسب دارد.",
    proTourStep2Title: "کارهای من", proTourStep2Body: "هر پیشنهادی که می‌فرستید، هر کاری که رزرو می‌کنید، از پیشنهاد تا پرداخت — همه در یک جا.",
    proTourStep3Title: "پیام‌ها", proTourStep3Body: "مستقیم با مشتری‌تان صحبت کنید، بدون رد و بدل کردن شماره.",
    proTourStep4Title: "سرعت شما، انتخاب شما", proTourStep4Body: "الان وقت ندارید؟ اینجا خودتان را موقتاً متوقف کنید — ناپدید نمی‌شوید، فقط موقتاً برای کارهای جدید دیده نمی‌شوید.",
    proTourStep5Title: "همین بود", proTourStep5Body: "کارها به سراغ شما می‌آیند — شما انتخاب می‌کنید کدام را بپذیرید.",
    proTourDoneCta: "رفتن به داشبورد",
    tourNext: "بعدی", tourBack: "قبلی", tourSkip: "رد کردن",
    tourStartCta: "شروع با Klussie",
    tourSetupHomeCta: "اول خانه‌ام را تنظیم کن",

    helpSectionTitle: "راهنما و توضیح",
    helpReplayTour: "دیدن دوباره راهنما",
  },
  tr: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "Klussie bugün sana nasıl yardımcı olabilir?",
    homeHeroFallbackLabel: "Sıcak bir ev içi",
    homeTabsLabel: "Evinin bölümleri",
    homeTabKlussie: "Klussie", homeTabMyHome: "Evim", homeTabMyItems: "Eşyalarım",

    intentsLabel: "Konu ne?",
    intentBroken: "Bir şey bozuldu", intentImprove: "Bir şeyi iyileştirmek istiyorum",
    intentMaintain: "Bakım planlamak istiyorum", intentAdvice: "Tavsiyeye ihtiyacım var",
    intentOther: "Başka bir şey",
    intentChosen: "Seçildi", intentChange: "Başka bir şey seç",

    homeComposerPlaceholder: "Kısaca neler olduğunu anlat…",
    homeVoiceAction: "Konuş", homePhotoAction: "Fotoğraf ekle", homeSendAction: "Gönder",
    homeAnswerLabel: "Yanıtın",
    followUpProgress: "Soru {n} / {total}",
    followUpBack: "Önceki soru", followUpSkip: "Atla ve gönder",

    safetyTitle: "Bu güvenli olmayabilir",
    safetyBody: "Gaz kokusu alıyor, ateş görüyor, su birikmesi ya da elektrik tehlikesi mi var? Önce acil servisi veya şebeke operatörünü ara. Klussie teşhis koymaz.",
    safetyContinue: "Yine de talebimle devam et", safetyBack: "Geri",

    todayHeading: "Bugün evin için",
    todayQuotesTitle: "Teklifler seçimini bekliyor",
    todayQuotesBody: "{service} için teklifleri incele ve işi kimin yapacağını seç.",
    todayBookedTitle: "İşin planlandı",
    todayBookedBody: "{service} rezerve edildi. Ustan seni bilgilendirecek.",
    todayAwaitingTitle: "Talebin tek bir ustada",
    todayAwaitingBody: "{service} — yanıt verir vermez haber vereceğiz.",
    todayCollectingTitle: "Ustalar talebini inceliyor",
    todayCollectingBody: "{service} — teklifler genellikle birkaç dakika içinde gelir.",
    todayReviewTitle: "Nasıl geçtiğini bize anlat",
    todayReviewBody: "{service} tamamlandı. Değerlendirmen sonraki müşteriye yardımcı olur.",
    todayOpenCta: "Talebi görüntüle",
    todayEmptyTitle: "Klussie ile evini daha akıllı yap",
    todayEmptyBody: "İlk odanı, tesisatını veya ev eşyanı ekle.",
    todayEmptyCta: "Evimi ayarla",
    homeActiveTitle: "Şu anda devam ediyor",

    myHomeQuestion: "Evinle ilgili neyi görmek veya takip etmek istersin?",
    homeReportProblem: "Sorun bildir",
    myHomeNoPropertyYet: "Klussie üzerinden bir iş yaptırdığın anda evinin geçmişi burada oluşmaya başlar.",
    myHomeKnownSince: "{date} tarihinden beri Klussie'de",
    myHomeJobsSummary: "{total} talep, bunlardan {completed} tanesi tamamlandı.",
    myHomeDoneBy: "{name} tarafından yapıldı",
    myHomeAiRead: "Klussie şunu anladı",
    myHomeActiveTitle: "Şu anda devam eden",
    myHomeActiveEmpty: "Şu anda devam eden bir şey yok.",
    myHomeProsTitle: "Evini tanıyan ustalar",
    myHomeProsEmpty: "Henüz burada iş tamamlayan bir usta yok.",
    myHomeOneJobTogether: "Birlikte 1 iş",
    myHomeJobsTogether: "Birlikte {count} iş",
    myHomeHistoryTitle: "Evinin geçmişi",
    myHomeHistoryEmpty: "Klussie üzerinden bir işi tamamladığında burada görünür.",
    myHomeReviewsTitle: "Değerlendirmelerin",
    myHomeReviewsEmpty: "Henüz bir değerlendirme yazmadın.",
    myHomeAiTitle: "Klussie'nin anladığı",
    myHomeAiEmpty: "Henüz bir işe ait yapay zekâ analizi yok.",
    myHomePhotosTitle: "Evinin fotoğrafları",
    myHomePhotosEmpty: "Henüz bir talebe fotoğraf eklenmedi.",
    myHomePhotosLoading: "Fotoğraflar yükleniyor…",

    myItemsQuestion: "Ne eklemek veya yeniden bulmak istersin?",
    myItemsEmptyTitle: "Henüz bir şey eklemedin.",
    myItemsEmptyHint: "Kombini, çamaşır makineni veya aletlerini ekle — böylece gerektiğinde hangi model olduğunu tam olarak bilirsin.",
    myItemsLoading: "Eşyaların yükleniyor…",
    myItemsLoadFailed: "Eşyaların yüklenemedi. Lütfen daha sonra tekrar dene.",
    myItemsRoomsTitle: "Odalar", myItemsRoomsEmpty: "Henüz oda eklenmedi.",
    myItemsMaintenanceTitle: "Bakım", myItemsMaintenanceEmpty: "Planlanan veya gecikmiş bir şey yok.",
    myItemsMaintenanceOverdue: "Gecikmiş", myItemsMaintenanceDueOn: "Son tarih: {date}",
    myItemsDocumentsTitle: "Belgeler", myItemsDocumentsEmpty: "Henüz belge eklenmedi.",
    myItemsDocumentExpired: "Süresi doldu", myItemsDocumentValidUntil: "{date} tarihine kadar geçerli",
    homeBuilderTitle: "Odalar", homeBuilderLoading: "Odalar yükleniyor…",
    homeBuilderNoPropertyYet: "Evinizi hâlâ ayarlıyoruz. Lütfen kısa süre sonra tekrar deneyin.",
    homeBuilderEmptyTitle: "Evinizi oluşturmaya başlayın",
    homeBuilderEmptyHint: "İlk odanızı ekleyin — örneğin mutfak veya oturma odası — ve oradan devam edin.",
    homeBuilderAddFirstRoom: "İlk odanızı ekleyin", homeBuilderAddAnotherRoom: "Başka bir oda ekle",
    locationEditTitle: "Odayı düzenle", locationSaveChanges: "Değişiklikleri kaydet",
    locationAddItemHere: "Bu odaya bir şey ekle", locationRemove: "Odayı kaldır",
    locationRemoveConfirm: "Bu oda kaldırılsın mı? Bu işlem geri alınamaz.",
    locationRetireBlockedChildren: "Bu odanın içinde hâlâ başka bir oda var. Önce onu kaldırın.",
    locationRetireBlockedItems: "Bu odada hâlâ bir şey var. Önce onu kaldırın veya taşıyın.",
    locationFormAddTitle: "Oda ekle", locationFormNameLabel: "Ad",
    locationFormNamePlaceholder: "örn. Tavan arası", locationFormTypeLabel: "Tür (isteğe bağlı)",
    locationFormTypePlaceholder: "örn. yatak odası", locationFormParentLabel: "İçinde (isteğe bağlı)",
    locationFormParentNone: "Yok — üst düzey", locationFormSaveNew: "Odayı kaydet",
    locationFormSaveFailed: "Odayı kaydedemedik. Lütfen daha sonra tekrar dene.",
    documentFormAddTitle: "Belge ekle", documentFormFileLabel: "Dosya",
    documentFormFileAdd: "Dosya seç", documentFormTypeLabel: "Tür",
    documentTypeWarranty: "Garanti", documentTypeCertificate: "Sertifika",
    documentTypeManual: "Kılavuz", documentTypeOther: "Diğer",
    documentTypePortfolioPhoto: "Portfolyo fotoğrafı", documentTypeRequestPhoto: "Talep fotoğrafı",
    documentFormIssuerLabel: "Veren kurum (isteğe bağlı)", documentFormValidUntilLabel: "Son geçerlilik (isteğe bağlı)",
    documentFormSaveNew: "Belgeyi kaydet",
    documentFormSaveFailed: "Belgeyi kaydedemedik. Lütfen daha sonra tekrar dene.",
    myItemsOneItem: "1 eşya", myItemsCount: "{count} eşya",
    itemCatAppliance: "Beyaz eşya", itemCatElectronics: "Elektronik",
    itemCatFurniture: "Mobilya ve aydınlatma", itemCatGarden: "Bahçe",
    itemCatTool: "Aletler", itemCatOther: "Diğer",
    itemRoomKitchen: "Mutfak", itemRoomLiving: "Oturma odası", itemRoomBedroom: "Yatak odası",
    itemRoomBathroom: "Banyo", itemRoomGarage: "Garaj", itemRoomGarden: "Bahçe",
    itemRoomAttic: "Çatı katı", itemRoomBasement: "Bodrum",
    itemAddTitle: "Eşya ekle", itemEditTitle: "Eşyayı düzenle",
    itemNameLabel: "Bu nedir?", itemNamePlaceholder: "ör. çamaşır makinesi",
    itemCategoryLabel: "Tür", itemRoomLabel: "Nerede duruyor?", itemRoomPlaceholder: "ör. mutfak",
    itemRoomNone: "Oda seçilmedi",
    itemBrandLabel: "Marka (isteğe bağlı)", itemModelLabel: "Model (isteğe bağlı)",
    itemPhotoLabel: "Fotoğraf (isteğe bağlı)", itemPhotoAdd: "Fotoğraf ekle", itemPhotoRemove: "Fotoğrafı kaldır",
    itemPurchasedLabel: "Satın alma tarihi (isteğe bağlı)", itemNotesLabel: "Notlar (isteğe bağlı)",
    itemSaveNew: "Eşyayı kaydet", itemSaveChanges: "Değişiklikleri kaydet",
    itemDelete: "Eşyayı sil",
    itemDeleteConfirm: "Bu eşya silinsin mi? Bu işlem geri alınamaz.",

    tourTitle: "Klussie'ye kısa bir tur",
    tourProgress: "Adım {n} / {total}",
    tourStep1Title: "Neler olduğunu anlat veya göster",
    tourStep1Body: "Metin, ses veya fotoğraf kullan.",
    tourStep2Title: "Klussie doğru soruları sorar",
    tourStep2Body: "Birlikte net bir talep oluştururuz.",
    tourStep3Title: "Evinle ilgili her şeyi sakla",
    tourStep3Body: "Odaları, tesisatları, belgeleri ve bakımı takip et.",
    tourStep4Title: "Eşyalarını ve garantilerini takip et",
    tourStep4Body: "Ürünleri, fişleri, kılavuzları ve garantileri sakla.",
    proTourStep0Title: "Hoş geldin", proTourStep0Body: "Az sonra göreceğin her iş, iyi olduğun şeyi yapmak — ve karşılığında adil bir ücret almak için bir fırsat. Sana etrafı göstereyim.",
    proTourStep1Title: "Panel", proTourStep1Body: "Yakınındaki bir müşteri tam olarak sunduğun şeyi aradığı an burada görürsün — tesadüfen değil, sana uyduğu için.",
    proTourStep2Title: "İşlerim", proTourStep2Body: "Gönderdiğin her teklif, ayırttığın her iş, teklifinden ödemesine kadar — hepsi tek bir yerde.",
    proTourStep3Title: "Mesajlar", proTourStep3Body: "Müşterinle doğrudan konuş, numara paylaşmadan.",
    proTourStep4Title: "Senin hızın, senin seçimin", proTourStep4Body: "Şu an vaktin yok mu? Kendini burada geçici olarak duraklat — kaybolmazsın, sadece yeni işler için geçici olarak görünmez olursun.",
    proTourStep5Title: "Bu kadar", proTourStep5Body: "İşler sana gelir — neyi kabul edeceğine sen karar verirsin.",
    proTourDoneCta: "Panele git",
    tourNext: "İleri", tourBack: "Geri", tourSkip: "Atla",
    tourStartCta: "Klussie ile başla", tourSetupHomeCta: "Önce evimi ayarla",
    helpSectionTitle: "Yardım ve açıklama", helpReplayTour: "Turu tekrar izle",
  },

  ru: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "Чем Klussie может помочь вам сегодня?",
    homeHeroFallbackLabel: "Тёплый интерьер дома",
    homeTabsLabel: "Разделы вашего дома",
    homeTabKlussie: "Klussie", homeTabMyHome: "Мой дом", homeTabMyItems: "Мои вещи",

    intentsLabel: "О чём речь?",
    intentBroken: "Что-то сломалось", intentImprove: "Хочу что-то улучшить",
    intentMaintain: "Хочу запланировать обслуживание", intentAdvice: "Нужен совет",
    intentOther: "Что-то другое",
    intentChosen: "Выбрано", intentChange: "Выбрать другое",

    homeComposerPlaceholder: "Кратко опишите, что происходит…",
    homeVoiceAction: "Сказать голосом", homePhotoAction: "Добавить фото", homeSendAction: "Отправить",
    homeAnswerLabel: "Ваш ответ",
    followUpProgress: "Вопрос {n} из {total}",
    followUpBack: "Предыдущий вопрос", followUpSkip: "Пропустить и отправить",

    safetyTitle: "Возможно, это небезопасно",
    safetyBody: "Чувствуете запах газа, видите огонь, стоит вода или есть опасность от электричества? Сначала позвоните в экстренные службы или своему сетевому оператору. Klussie не ставит диагноз.",
    safetyContinue: "Всё равно продолжить заявку", safetyBack: "Назад",

    todayHeading: "Сегодня для вашего дома",
    todayQuotesTitle: "Предложения ждут вашего выбора",
    todayQuotesBody: "Посмотрите предложения по услуге «{service}» и выберите исполнителя.",
    todayBookedTitle: "Работа запланирована",
    todayBookedBody: "«{service}» забронировано. Мастер будет держать вас в курсе.",
    todayAwaitingTitle: "Ваша заявка у одного мастера",
    todayAwaitingBody: "«{service}» — мы сообщим, как только он ответит.",
    todayCollectingTitle: "Мастера изучают вашу заявку",
    todayCollectingBody: "«{service}» — предложения обычно приходят за несколько минут.",
    todayReviewTitle: "Расскажите, как всё прошло",
    todayReviewBody: "«{service}» завершено. Ваш отзыв поможет следующему клиенту.",
    todayOpenCta: "Открыть заявку",
    todayEmptyTitle: "Сделайте свой дом умнее с Klussie",
    todayEmptyBody: "Добавьте первую комнату, установку или бытовую вещь.",
    todayEmptyCta: "Настроить мой дом",
    homeActiveTitle: "Сейчас в работе",

    myHomeQuestion: "Что вы хотите посмотреть или отслеживать по своему дому?",
    homeReportProblem: "Сообщить о проблеме",
    myHomeNoPropertyYet: "Как только вы что-то сделаете через Klussie, здесь начнёт складываться история вашего дома.",
    myHomeKnownSince: "В Klussie с {date}",
    myHomeJobsSummary: "{total} заявок, из них {completed} завершено.",
    myHomeDoneBy: "Выполнил {name}",
    myHomeAiRead: "Klussie понял",
    myHomeActiveTitle: "Сейчас в работе",
    myHomeActiveEmpty: "Сейчас ничего не выполняется.",
    myHomeProsTitle: "Мастера, которые знают ваш дом",
    myHomeProsEmpty: "Пока ни один мастер не завершил здесь работу.",
    myHomeOneJobTogether: "1 работа вместе",
    myHomeJobsTogether: "{count} работ вместе",
    myHomeHistoryTitle: "История вашего дома",
    myHomeHistoryEmpty: "Как только вы завершите работу через Klussie, она появится здесь.",
    myHomeReviewsTitle: "Ваши отзывы",
    myHomeReviewsEmpty: "Вы ещё не написали ни одного отзыва.",
    myHomeAiTitle: "Что понял Klussie",
    myHomeAiEmpty: "Пока нет ИИ-анализа по работам.",
    myHomePhotosTitle: "Фотографии вашего дома",
    myHomePhotosEmpty: "К заявкам пока не добавлено ни одной фотографии.",
    myHomePhotosLoading: "Загрузка фотографий…",

    myItemsQuestion: "Что вы хотите добавить или найти?",
    myItemsEmptyTitle: "Вы ещё ничего не добавили.",
    myItemsEmptyHint: "Добавьте котёл, стиральную машину или инструменты — тогда вы точно будете знать модель, когда это понадобится.",
    myItemsLoading: "Загрузка ваших вещей…",
    myItemsLoadFailed: "Не удалось загрузить ваши вещи. Попробуйте позже.",
    myItemsRoomsTitle: "Комнаты", myItemsRoomsEmpty: "Пока не добавлено ни одной комнаты.",
    myItemsMaintenanceTitle: "Обслуживание", myItemsMaintenanceEmpty: "Ничего не запланировано и нет просрочек.",
    myItemsMaintenanceOverdue: "Просрочено", myItemsMaintenanceDueOn: "Срок: {date}",
    myItemsDocumentsTitle: "Документы", myItemsDocumentsEmpty: "Пока не добавлено ни одного документа.",
    myItemsDocumentExpired: "Истёк", myItemsDocumentValidUntil: "Действителен до {date}",
    homeBuilderTitle: "Комнаты", homeBuilderLoading: "Загрузка комнат…",
    homeBuilderNoPropertyYet: "Мы всё ещё настраиваем ваш дом. Загляните ещё раз чуть позже.",
    homeBuilderEmptyTitle: "Начните обустраивать свой дом",
    homeBuilderEmptyHint: "Добавьте первую комнату — например, кухню или гостиную — и продолжайте оттуда.",
    homeBuilderAddFirstRoom: "Добавить первую комнату", homeBuilderAddAnotherRoom: "Добавить ещё одну комнату",
    locationEditTitle: "Изменить комнату", locationSaveChanges: "Сохранить изменения",
    locationAddItemHere: "Добавить что-то в эту комнату", locationRemove: "Удалить комнату",
    locationRemoveConfirm: "Удалить эту комнату? Это нельзя отменить.",
    locationRetireBlockedChildren: "В этой комнате всё ещё есть другая комната. Сначала удалите её.",
    locationRetireBlockedItems: "В этой комнате всё ещё что-то есть. Сначала удалите или переместите это.",
    locationFormAddTitle: "Добавить комнату", locationFormNameLabel: "Название",
    locationFormNamePlaceholder: "напр. Чердак", locationFormTypeLabel: "Тип (необязательно)",
    locationFormTypePlaceholder: "напр. спальня", locationFormParentLabel: "Внутри (необязательно)",
    locationFormParentNone: "Нет — верхний уровень", locationFormSaveNew: "Сохранить комнату",
    locationFormSaveFailed: "Не удалось сохранить комнату. Попробуйте позже.",
    documentFormAddTitle: "Добавить документ", documentFormFileLabel: "Файл",
    documentFormFileAdd: "Выбрать файл", documentFormTypeLabel: "Тип",
    documentTypeWarranty: "Гарантия", documentTypeCertificate: "Сертификат",
    documentTypeManual: "Инструкция", documentTypeOther: "Другое",
    documentTypePortfolioPhoto: "Фото портфолио", documentTypeRequestPhoto: "Фото заявки",
    documentFormIssuerLabel: "Кем выдан (необязательно)", documentFormValidUntilLabel: "Действителен до (необязательно)",
    documentFormSaveNew: "Сохранить документ",
    documentFormSaveFailed: "Не удалось сохранить документ. Попробуйте позже.",
    myItemsOneItem: "1 предмет", myItemsCount: "{count} предметов",
    itemCatAppliance: "Техника", itemCatElectronics: "Электроника",
    itemCatFurniture: "Мебель и освещение", itemCatGarden: "Сад",
    itemCatTool: "Инструменты", itemCatOther: "Другое",
    itemRoomKitchen: "Кухня", itemRoomLiving: "Гостиная", itemRoomBedroom: "Спальня",
    itemRoomBathroom: "Ванная", itemRoomGarage: "Гараж", itemRoomGarden: "Сад",
    itemRoomAttic: "Чердак", itemRoomBasement: "Подвал",
    itemAddTitle: "Добавить предмет", itemEditTitle: "Изменить предмет",
    itemNameLabel: "Что это?", itemNamePlaceholder: "напр. стиральная машина",
    itemCategoryLabel: "Тип", itemRoomLabel: "Где находится?", itemRoomPlaceholder: "напр. кухня",
    itemRoomNone: "Комната не выбрана",
    itemBrandLabel: "Марка (необязательно)", itemModelLabel: "Модель (необязательно)",
    itemPhotoLabel: "Фото (необязательно)", itemPhotoAdd: "Добавить фото", itemPhotoRemove: "Удалить фото",
    itemPurchasedLabel: "Дата покупки (необязательно)", itemNotesLabel: "Заметки (необязательно)",
    itemSaveNew: "Сохранить предмет", itemSaveChanges: "Сохранить изменения",
    itemDelete: "Удалить предмет",
    itemDeleteConfirm: "Удалить этот предмет? Это нельзя отменить.",

    tourTitle: "Короткая экскурсия по Klussie",
    tourProgress: "Шаг {n} из {total}",
    tourStep1Title: "Расскажите или покажите, что случилось",
    tourStep1Body: "Используйте текст, голос или фото.",
    tourStep2Title: "Klussie задаёт нужные вопросы",
    tourStep2Body: "Вместе мы составим понятную заявку.",
    tourStep3Title: "Храните всё о своём доме",
    tourStep3Body: "Ведите комнаты, установки, документы и обслуживание.",
    tourStep4Title: "Следите за вещами и гарантиями",
    tourStep4Body: "Храните товары, чеки, инструкции и гарантии.",
    proTourStep0Title: "Добро пожаловать", proTourStep0Body: "Каждая работа, которую вы сейчас увидите, — это шанс делать то, в чём вы хороши, и получать за это справедливую оплату. Позвольте я всё покажу.",
    proTourStep1Title: "Панель", proTourStep1Body: "Как только клиент поблизости ищет именно то, что вы предлагаете, вы увидите это здесь — не случайно, а потому что это вам подходит.",
    proTourStep2Title: "Мои заказы", proTourStep2Body: "Каждое отправленное предложение, каждый забронированный заказ, от предложения до оплаты — всё в одном месте.",
    proTourStep3Title: "Сообщения", proTourStep3Body: "Общайтесь напрямую с клиентом, не обмениваясь номерами.",
    proTourStep4Title: "Ваш темп, ваш выбор", proTourStep4Body: "Сейчас нет времени? Поставьте себя на паузу здесь — вы не исчезаете, просто временно не видны для новых заказов.",
    proTourStep5Title: "Вот и всё", proTourStep5Body: "Заказы приходят к вам сами — вы сами решаете, что взять.",
    proTourDoneCta: "Перейти к панели",
    tourNext: "Далее", tourBack: "Назад", tourSkip: "Пропустить",
    tourStartCta: "Начать с Klussie", tourSetupHomeCta: "Сначала настроить мой дом",
    helpSectionTitle: "Помощь и пояснения", helpReplayTour: "Пересмотреть экскурсию",
  },

  zh: {
    homeGreetName: "{greeting}，{name}", homeGreetNoName: "{greeting}",
    homeQuestion: "今天 Klussie 能帮你做什么？",
    homeHeroFallbackLabel: "温馨的住宅室内",
    homeTabsLabel: "你家的各个板块",
    homeTabKlussie: "Klussie", homeTabMyHome: "我的住宅", homeTabMyItems: "我的物品",

    intentsLabel: "是关于什么的？",
    intentBroken: "有东西坏了", intentImprove: "我想改善某处",
    intentMaintain: "我想安排保养", intentAdvice: "我需要建议",
    intentOther: "其他事情",
    intentChosen: "已选择", intentChange: "换一个",

    homeComposerPlaceholder: "简单说说发生了什么……",
    homeVoiceAction: "语音描述", homePhotoAction: "添加照片", homeSendAction: "发送",
    homeAnswerLabel: "你的回答",
    followUpProgress: "第 {n} 个问题，共 {total} 个",
    followUpBack: "上一个问题", followUpSkip: "跳过并发送",

    safetyTitle: "这可能不安全",
    safetyBody: "闻到煤气、看到明火、有积水或存在触电危险吗？请先联系急救部门或供电供气单位。Klussie 不做诊断。",
    safetyContinue: "仍然继续我的申请", safetyBack: "返回",

    todayHeading: "今天为你的家",
    todayQuotesTitle: "报价正在等你选择",
    todayQuotesBody: "查看「{service}」的报价，选择由谁来做。",
    todayBookedTitle: "你的工作已排期",
    todayBookedBody: "「{service}」已预订。师傅会随时告知进展。",
    todayAwaitingTitle: "你的申请已发给一位师傅",
    todayAwaitingBody: "「{service}」——对方回复后我们会通知你。",
    todayCollectingTitle: "师傅们正在查看你的申请",
    todayCollectingBody: "「{service}」——报价通常几分钟内送达。",
    todayReviewTitle: "告诉我们进行得如何",
    todayReviewBody: "「{service}」已完成。你的评价能帮到下一位客户。",
    todayOpenCta: "查看申请",
    todayEmptyTitle: "用 Klussie 让你的家更聪明",
    todayEmptyBody: "添加第一个房间、设备或家居物品。",
    todayEmptyCta: "设置我的住宅",
    homeActiveTitle: "正在进行中",

    myHomeQuestion: "关于你的住宅，你想查看或记录什么？",
    homeReportProblem: "报告问题",
    myHomeNoPropertyYet: "只要你通过 Klussie 完成一件事，这里就会开始积累你住宅的历史。",
    myHomeKnownSince: "自 {date} 起在 Klussie",
    myHomeJobsSummary: "共 {total} 个请求，其中 {completed} 个已完成。",
    myHomeDoneBy: "由 {name} 完成",
    myHomeAiRead: "Klussie 的理解",
    myHomeActiveTitle: "正在进行",
    myHomeActiveEmpty: "目前没有正在进行的事项。",
    myHomeProsTitle: "了解你住宅的师傅",
    myHomeProsEmpty: "还没有师傅在这里完成过活儿。",
    myHomeOneJobTogether: "一起完成 1 单",
    myHomeJobsTogether: "一起完成 {count} 单",
    myHomeHistoryTitle: "你住宅的历史",
    myHomeHistoryEmpty: "当你通过 Klussie 完成一单后，就会显示在这里。",
    myHomeReviewsTitle: "你的评价",
    myHomeReviewsEmpty: "你还没有写过评价。",
    myHomeAiTitle: "Klussie 理解到的内容",
    myHomeAiEmpty: "暂时还没有对活儿的 AI 分析。",
    myHomePhotosTitle: "你住宅的照片",
    myHomePhotosEmpty: "还没有为任何请求添加照片。",
    myHomePhotosLoading: "正在加载照片…",

    myItemsQuestion: "你想添加或找回什么？",
    myItemsEmptyTitle: "你还没有添加任何东西。",
    myItemsEmptyHint: "把锅炉、洗衣机或工具添加进来——需要的时候你就能准确知道是哪个型号。",
    myItemsLoading: "正在加载你的物品…",
    myItemsLoadFailed: "无法加载你的物品，请稍后重试。",
    myItemsRoomsTitle: "房间", myItemsRoomsEmpty: "还没有添加房间。",
    myItemsMaintenanceTitle: "维护", myItemsMaintenanceEmpty: "没有安排或逾期的事项。",
    myItemsMaintenanceOverdue: "已逾期", myItemsMaintenanceDueOn: "到期日 {date}",
    myItemsDocumentsTitle: "文件", myItemsDocumentsEmpty: "还没有添加文件。",
    myItemsDocumentExpired: "已过期", myItemsDocumentValidUntil: "有效期至 {date}",
    homeBuilderTitle: "房间", homeBuilderLoading: "正在加载房间…",
    homeBuilderNoPropertyYet: "我们仍在为您设置住宅，请稍后再试。",
    homeBuilderEmptyTitle: "开始搭建您的家",
    homeBuilderEmptyHint: "添加您的第一个房间——例如厨房或客厅——然后继续添加。",
    homeBuilderAddFirstRoom: "添加第一个房间", homeBuilderAddAnotherRoom: "再添加一个房间",
    locationEditTitle: "编辑房间", locationSaveChanges: "保存更改",
    locationAddItemHere: "在此房间添加物品", locationRemove: "删除房间",
    locationRemoveConfirm: "要删除此房间吗？此操作无法撤销。",
    locationRetireBlockedChildren: "此房间内仍包含另一个房间，请先删除该房间。",
    locationRetireBlockedItems: "此房间内仍放着物品，请先删除或移动它。",
    locationFormAddTitle: "添加房间", locationFormNameLabel: "名称",
    locationFormNamePlaceholder: "例如：阁楼", locationFormTypeLabel: "类型（可选）",
    locationFormTypePlaceholder: "例如：卧室", locationFormParentLabel: "位于（可选）",
    locationFormParentNone: "无 — 顶层", locationFormSaveNew: "保存房间",
    locationFormSaveFailed: "无法保存房间，请稍后重试。",
    documentFormAddTitle: "添加文件", documentFormFileLabel: "文件",
    documentFormFileAdd: "选择文件", documentFormTypeLabel: "类型",
    documentTypeWarranty: "保修单", documentTypeCertificate: "证书",
    documentTypeManual: "说明书", documentTypeOther: "其他",
    documentTypePortfolioPhoto: "作品照片", documentTypeRequestPhoto: "请求照片",
    documentFormIssuerLabel: "签发方（可选）", documentFormValidUntilLabel: "有效期至（可选）",
    documentFormSaveNew: "保存文件",
    documentFormSaveFailed: "无法保存文件，请稍后重试。",
    myItemsOneItem: "1 件", myItemsCount: "{count} 件",
    itemCatAppliance: "家电", itemCatElectronics: "电子产品",
    itemCatFurniture: "家具与照明", itemCatGarden: "花园",
    itemCatTool: "工具", itemCatOther: "其他",
    itemRoomKitchen: "厨房", itemRoomLiving: "客厅", itemRoomBedroom: "卧室",
    itemRoomBathroom: "浴室", itemRoomGarage: "车库", itemRoomGarden: "花园",
    itemRoomAttic: "阁楼", itemRoomBasement: "地下室",
    itemAddTitle: "添加物品", itemEditTitle: "编辑物品",
    itemNameLabel: "这是什么？", itemNamePlaceholder: "例如：洗衣机",
    itemCategoryLabel: "种类", itemRoomLabel: "放在哪里？", itemRoomPlaceholder: "例如：厨房",
    itemRoomNone: "未选择房间",
    itemBrandLabel: "品牌（可选）", itemModelLabel: "型号（可选）",
    itemPhotoLabel: "照片（可选）", itemPhotoAdd: "添加照片", itemPhotoRemove: "移除照片",
    itemPurchasedLabel: "购买日期（可选）", itemNotesLabel: "备注（可选）",
    itemSaveNew: "保存物品", itemSaveChanges: "保存更改",
    itemDelete: "删除物品",
    itemDeleteConfirm: "要删除这件物品吗？此操作无法撤销。",

    tourTitle: "Klussie 快速导览",
    tourProgress: "第 {n} 步，共 {total} 步",
    tourStep1Title: "说出或拍下发生了什么",
    tourStep1Body: "可以用文字、语音或照片。",
    tourStep2Title: "Klussie 会问对的问题",
    tourStep2Body: "我们一起整理成一份清晰的申请。",
    tourStep3Title: "记录关于住宅的一切",
    tourStep3Body: "管理房间、设备、文件和保养。",
    tourStep4Title: "追踪物品与保修",
    tourStep4Body: "保存产品、购买凭证、说明书和保修。",
    proTourStep0Title: "欢迎", proTourStep0Body: "你即将看到的每一项工作，都是发挥你专长、并获得合理报酬的机会。让我带你了解一下。",
    proTourStep1Title: "仪表盘", proTourStep1Body: "一旦附近的客户正好需要你提供的服务，你就会在这里看到——不是偶然，而是因为它适合你。",
    proTourStep2Title: "我的工作", proTourStep2Body: "你发出的每一份报价，你预订的每一项工作，从提议到付款——都在一个地方。",
    proTourStep3Title: "消息", proTourStep3Body: "直接与客户交流，无需交换电话号码。",
    proTourStep4Title: "你的节奏，你的选择", proTourStep4Body: "现在没时间？在这里暂停自己——你不会消失，只是暂时对新工作不可见。",
    proTourStep5Title: "就这些", proTourStep5Body: "工作会主动找上你——你来选择接哪些。",
    proTourDoneCta: "前往仪表盘",
    tourNext: "下一步", tourBack: "上一步", tourSkip: "跳过",
    tourStartCta: "开始使用 Klussie", tourSetupHomeCta: "先设置我的住宅",
    helpSectionTitle: "帮助与说明", helpReplayTour: "重新观看导览",
  },
};

// Fills {placeholder} slots in a localized template. Kept here next to the copy it
// serves rather than in a component, so every call site interpolates the same way —
// a missing key must show as a literal "{name}", not as an empty string that hides
// the bug (the pattern src/__tests__/conversationHome.test.jsx already pins).
export function interpolate(template, values) {
  if (!template) return "";
  return Object.keys(values || {}).reduce(
    (acc, key) => acc.split(`{${key}}`).join(values[key]),
    template
  );
}
