// Locale copy for the customer home surface (hero, section tabs, intents, the
// "today" card, My Home, My Items, and the first-login tour).
//
// Kept out of src/App.jsx's STRINGS object on purpose: that file is already the
// largest in the repository (MASTER_CONTEXT.md §12 tracks it as high-severity
// debt), and adding ~90 keys across 8 locales to it would make the single worst
// file measurably worse. App() merges this in, so `t` stays one flat lookup at
// every call site — same shape, different home.
//
// Dutch is the reference locale (COPY_GUIDELINES.md); the other seven follow it.
// Any string describing something not yet built says so plainly rather than
// implying the capability exists (Constitution Rule 9).

export const HOME_STRINGS = {
  nl: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "Waarmee kan Klussie je vandaag helpen?",
    homeHeroFallbackLabel: "Warm interieur van een woning",
    homeTabsLabel: "Onderdelen van je woning",
    homeTabKlussie: "Klussie", homeTabMyHome: "Mijn woning", homeTabMyItems: "Mijn spullen",

    intentsLabel: "Waar gaat het over?",
    intentBroken: "Er is iets kapot", intentImprove: "Ik wil iets verbeteren",
    intentMaintain: "Ik wil onderhoud plannen", intentAdvice: "Ik heb advies nodig",
    intentOther: "Iets anders",
    intentChosen: "Gekozen", intentChange: "Kies iets anders",

    homeComposerPlaceholder: "Beschrijf kort wat er aan de hand is…",
    homeVoiceAction: "Inspreken", homePhotoAction: "Foto toevoegen", homeSendAction: "Versturen",
    homeAnswerLabel: "Jouw antwoord",
    followUpProgress: "Vraag {n} van {total}",
    followUpBack: "Vorige vraag", followUpSkip: "Sla over en verstuur",

    safetyTitle: "Dit klinkt mogelijk onveilig",
    safetyBody: "Ruik je gas, zie je vuur, staat er water of is er gevaar door elektriciteit? Bel dan eerst de hulpdiensten of je netbeheerder. Klussie stelt geen diagnose.",
    safetyContinue: "Toch verder met mijn aanvraag", safetyBack: "Terug",

    todayHeading: "Vandaag voor jouw woning",
    todayQuotesTitle: "Offertes wachten op je keuze",
    todayQuotesBody: "Bekijk de offertes voor {service} en kies wie de klus doet.",
    todayBookedTitle: "Je klus staat gepland",
    todayBookedBody: "{service} is geboekt. Je vakman houdt je op de hoogte.",
    todayAwaitingTitle: "Je aanvraag ligt bij één vakman",
    todayAwaitingBody: "{service} — je hoort het zodra hij of zij reageert.",
    todayCollectingTitle: "Vakmensen bekijken je aanvraag",
    todayCollectingBody: "{service} — offertes komen meestal binnen enkele minuten binnen.",
    todayReviewTitle: "Laat weten hoe het ging",
    todayReviewBody: "{service} is afgerond. Je beoordeling helpt de volgende klant.",
    todayOpenCta: "Bekijk aanvraag",
    todayEmptyTitle: "Maak je woning slimmer met Klussie",
    todayEmptyBody: "Voeg je eerste ruimte, installatie of huishoudelijk item toe.",
    todayEmptyCta: "Stel mijn woning in",
    homeActiveTitle: "Loopt op dit moment",

    myHomeQuestion: "Wat wil je over je woning bekijken of bijhouden?",
    myHomeAddRoom: "Ruimte toevoegen", myHomeAddInstallation: "Installatie toevoegen",
    myHomeUploadDoc: "Document uploaden", myHomeLogMaintenance: "Onderhoud vastleggen",
    homeReportProblem: "Probleem melden",
    myHomeSummaryTitle: "Overzicht van je woning", myHomeRoomsTitle: "Ruimtes",
    myHomeInstallationsTitle: "Belangrijke installaties", myHomeMaintenanceTitle: "Gepland onderhoud",
    myHomeDocumentsTitle: "Documenten en attesten", myHomeHistoryTitle: "Eerder werk",
    myHomeHistoryEmpty: "Zodra je een klus afrondt via Klussie, verschijnt die hier.",

    myItemsQuestion: "Wat wil je toevoegen of terugvinden?",
    myItemsScan: "Product scannen", myItemsReceipt: "Aankoopbewijs uploaden",
    myItemsWarranty: "Garantie controleren", myItemsManual: "Handleiding zoeken",
    myItemsAppliances: "Toestellen", myItemsElectronics: "Elektronica",
    myItemsFurniture: "Meubels en verlichting", myItemsGarden: "Tuin en gereedschap",
    myItemsRecent: "Recent toegevoegd",

    homeNothingSavedYet: "Je hebt hier nog niets bewaard.",
    homeNotBuiltYet: "Nog niet beschikbaar",
    homeNotBuiltYetNote: "Klussie bewaart je woning en je spullen nog niet. We bouwen dit — tot dan kun je hier niets toevoegen, en doen we ook niet alsof.",

    tourTitle: "Rondleiding door Klussie",
    tourProgress: "Stap {n} van {total}",
    tourStep1Title: "Vertel of toon wat er aan de hand is",
    tourStep1Body: "Gebruik tekst, spraak of een foto.",
    tourStep2Title: "Klussie stelt de juiste vragen",
    tourStep2Body: "We maken samen een duidelijke aanvraag.",
    tourStep3Title: "Bewaar alles over je woning",
    tourStep3Body: "Houd ruimtes, installaties, documenten en onderhoud bij.",
    tourStep4Title: "Volg je spullen en garanties",
    tourStep4Body: "Bewaar producten, aankoopbewijzen, handleidingen en garanties.",
    tourNext: "Volgende", tourBack: "Vorige", tourSkip: "Overslaan",
    tourStartCta: "Start met Klussie", tourSetupHomeCta: "Stel eerst mijn woning in",
    helpSectionTitle: "Hulp & uitleg", helpReplayTour: "Rondleiding opnieuw bekijken",
  },

  fr: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "Comment Klussie peut-il t'aider aujourd'hui ?",
    homeHeroFallbackLabel: "Intérieur chaleureux d'une habitation",
    homeTabsLabel: "Sections de ton logement",
    homeTabKlussie: "Klussie", homeTabMyHome: "Mon logement", homeTabMyItems: "Mes objets",

    intentsLabel: "De quoi s'agit-il ?",
    intentBroken: "Quelque chose est cassé", intentImprove: "Je veux améliorer quelque chose",
    intentMaintain: "Je veux planifier un entretien", intentAdvice: "J'ai besoin de conseils",
    intentOther: "Autre chose",
    intentChosen: "Choisi", intentChange: "Choisir autre chose",

    homeComposerPlaceholder: "Décris brièvement ce qui se passe…",
    homeVoiceAction: "Dicter", homePhotoAction: "Ajouter une photo", homeSendAction: "Envoyer",
    homeAnswerLabel: "Ta réponse",
    followUpProgress: "Question {n} sur {total}",
    followUpBack: "Question précédente", followUpSkip: "Passer et envoyer",

    safetyTitle: "Cela peut être dangereux",
    safetyBody: "Tu sens le gaz, tu vois du feu, il y a de l'eau ou un danger électrique ? Appelle d'abord les secours ou ton gestionnaire de réseau. Klussie ne pose aucun diagnostic.",
    safetyContinue: "Continuer quand même ma demande", safetyBack: "Retour",

    todayHeading: "Aujourd'hui pour ton logement",
    todayQuotesTitle: "Des devis attendent ton choix",
    todayQuotesBody: "Consulte les devis pour {service} et choisis qui fera le travail.",
    todayBookedTitle: "Ta tâche est planifiée",
    todayBookedBody: "{service} est réservé. Ton pro te tient au courant.",
    todayAwaitingTitle: "Ta demande est chez un seul pro",
    todayAwaitingBody: "{service} — tu seras prévenu dès qu'il ou elle répond.",
    todayCollectingTitle: "Les pros examinent ta demande",
    todayCollectingBody: "{service} — les devis arrivent généralement en quelques minutes.",
    todayReviewTitle: "Dis-nous comment cela s'est passé",
    todayReviewBody: "{service} est terminé. Ton avis aide le prochain client.",
    todayOpenCta: "Voir la demande",
    todayEmptyTitle: "Rends ton logement plus intelligent avec Klussie",
    todayEmptyBody: "Ajoute ta première pièce, installation ou objet du foyer.",
    todayEmptyCta: "Configurer mon logement",
    homeActiveTitle: "En cours actuellement",

    myHomeQuestion: "Que veux-tu consulter ou suivre pour ton logement ?",
    myHomeAddRoom: "Ajouter une pièce", myHomeAddInstallation: "Ajouter une installation",
    myHomeUploadDoc: "Téléverser un document", myHomeLogMaintenance: "Enregistrer un entretien",
    homeReportProblem: "Signaler un problème",
    myHomeSummaryTitle: "Aperçu de ton logement", myHomeRoomsTitle: "Pièces",
    myHomeInstallationsTitle: "Installations importantes", myHomeMaintenanceTitle: "Entretien prévu",
    myHomeDocumentsTitle: "Documents et attestations", myHomeHistoryTitle: "Travaux précédents",
    myHomeHistoryEmpty: "Dès que tu termines une tâche via Klussie, elle apparaît ici.",

    myItemsQuestion: "Que veux-tu ajouter ou retrouver ?",
    myItemsScan: "Scanner un produit", myItemsReceipt: "Téléverser une preuve d'achat",
    myItemsWarranty: "Vérifier la garantie", myItemsManual: "Chercher un manuel",
    myItemsAppliances: "Électroménager", myItemsElectronics: "Électronique",
    myItemsFurniture: "Meubles et éclairage", myItemsGarden: "Jardin et outils",
    myItemsRecent: "Ajoutés récemment",

    homeNothingSavedYet: "Tu n'as encore rien enregistré ici.",
    homeNotBuiltYet: "Pas encore disponible",
    homeNotBuiltYetNote: "Klussie ne conserve pas encore ton logement ni tes objets. Nous le construisons — d'ici là, tu ne peux rien ajouter ici, et nous ne prétendons pas le contraire.",

    tourTitle: "Visite guidée de Klussie",
    tourProgress: "Étape {n} sur {total}",
    tourStep1Title: "Raconte ou montre ce qui se passe",
    tourStep1Body: "Utilise le texte, la voix ou une photo.",
    tourStep2Title: "Klussie pose les bonnes questions",
    tourStep2Body: "Nous construisons ensemble une demande claire.",
    tourStep3Title: "Garde tout sur ton logement",
    tourStep3Body: "Suis tes pièces, installations, documents et entretiens.",
    tourStep4Title: "Suis tes objets et tes garanties",
    tourStep4Body: "Conserve produits, preuves d'achat, manuels et garanties.",
    tourNext: "Suivant", tourBack: "Précédent", tourSkip: "Passer",
    tourStartCta: "Commencer avec Klussie", tourSetupHomeCta: "Configurer d'abord mon logement",
    helpSectionTitle: "Aide & explications", helpReplayTour: "Revoir la visite guidée",
  },

  de: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "Womit kann Klussie dir heute helfen?",
    homeHeroFallbackLabel: "Warmer Innenraum einer Wohnung",
    homeTabsLabel: "Bereiche deines Zuhauses",
    homeTabKlussie: "Klussie", homeTabMyHome: "Mein Zuhause", homeTabMyItems: "Meine Sachen",

    intentsLabel: "Worum geht es?",
    intentBroken: "Etwas ist kaputt", intentImprove: "Ich möchte etwas verbessern",
    intentMaintain: "Ich möchte Wartung planen", intentAdvice: "Ich brauche einen Rat",
    intentOther: "Etwas anderes",
    intentChosen: "Ausgewählt", intentChange: "Etwas anderes wählen",

    homeComposerPlaceholder: "Beschreibe kurz, was los ist…",
    homeVoiceAction: "Sprechen", homePhotoAction: "Foto hinzufügen", homeSendAction: "Senden",
    homeAnswerLabel: "Deine Antwort",
    followUpProgress: "Frage {n} von {total}",
    followUpBack: "Vorherige Frage", followUpSkip: "Überspringen und senden",

    safetyTitle: "Das klingt möglicherweise gefährlich",
    safetyBody: "Riechst du Gas, siehst du Feuer, steht Wasser oder besteht Gefahr durch Strom? Rufe zuerst den Notruf oder deinen Netzbetreiber an. Klussie stellt keine Diagnose.",
    safetyContinue: "Trotzdem mit meiner Anfrage weitermachen", safetyBack: "Zurück",

    todayHeading: "Heute für dein Zuhause",
    todayQuotesTitle: "Angebote warten auf deine Wahl",
    todayQuotesBody: "Sieh dir die Angebote für {service} an und wähle, wer die Arbeit macht.",
    todayBookedTitle: "Dein Auftrag ist geplant",
    todayBookedBody: "{service} ist gebucht. Dein Profi hält dich auf dem Laufenden.",
    todayAwaitingTitle: "Deine Anfrage liegt bei einem Profi",
    todayAwaitingBody: "{service} — du hörst es, sobald er oder sie antwortet.",
    todayCollectingTitle: "Profis sehen sich deine Anfrage an",
    todayCollectingBody: "{service} — Angebote kommen meist innerhalb weniger Minuten.",
    todayReviewTitle: "Sag uns, wie es gelaufen ist",
    todayReviewBody: "{service} ist abgeschlossen. Deine Bewertung hilft dem nächsten Kunden.",
    todayOpenCta: "Anfrage ansehen",
    todayEmptyTitle: "Mach dein Zuhause schlauer mit Klussie",
    todayEmptyBody: "Füge deinen ersten Raum, deine erste Anlage oder dein erstes Haushaltsgerät hinzu.",
    todayEmptyCta: "Mein Zuhause einrichten",
    homeActiveTitle: "Läuft gerade",

    myHomeQuestion: "Was möchtest du zu deinem Zuhause ansehen oder festhalten?",
    myHomeAddRoom: "Raum hinzufügen", myHomeAddInstallation: "Anlage hinzufügen",
    myHomeUploadDoc: "Dokument hochladen", myHomeLogMaintenance: "Wartung festhalten",
    homeReportProblem: "Problem melden",
    myHomeSummaryTitle: "Überblick über dein Zuhause", myHomeRoomsTitle: "Räume",
    myHomeInstallationsTitle: "Wichtige Anlagen", myHomeMaintenanceTitle: "Geplante Wartung",
    myHomeDocumentsTitle: "Dokumente und Nachweise", myHomeHistoryTitle: "Frühere Arbeiten",
    myHomeHistoryEmpty: "Sobald du einen Auftrag über Klussie abschließt, erscheint er hier.",

    myItemsQuestion: "Was möchtest du hinzufügen oder wiederfinden?",
    myItemsScan: "Produkt scannen", myItemsReceipt: "Kaufbeleg hochladen",
    myItemsWarranty: "Garantie prüfen", myItemsManual: "Anleitung suchen",
    myItemsAppliances: "Haushaltsgeräte", myItemsElectronics: "Elektronik",
    myItemsFurniture: "Möbel und Beleuchtung", myItemsGarden: "Garten und Werkzeug",
    myItemsRecent: "Kürzlich hinzugefügt",

    homeNothingSavedYet: "Du hast hier noch nichts gespeichert.",
    homeNotBuiltYet: "Noch nicht verfügbar",
    homeNotBuiltYetNote: "Klussie speichert dein Zuhause und deine Sachen noch nicht. Wir bauen das gerade — bis dahin kannst du hier nichts hinzufügen, und wir tun auch nicht so.",

    tourTitle: "Rundgang durch Klussie",
    tourProgress: "Schritt {n} von {total}",
    tourStep1Title: "Erzähl oder zeig, was los ist",
    tourStep1Body: "Nutze Text, Sprache oder ein Foto.",
    tourStep2Title: "Klussie stellt die richtigen Fragen",
    tourStep2Body: "Gemeinsam machen wir daraus eine klare Anfrage.",
    tourStep3Title: "Halte alles zu deinem Zuhause fest",
    tourStep3Body: "Räume, Anlagen, Dokumente und Wartung an einem Ort.",
    tourStep4Title: "Behalte Sachen und Garantien im Blick",
    tourStep4Body: "Bewahre Produkte, Kaufbelege, Anleitungen und Garantien auf.",
    tourNext: "Weiter", tourBack: "Zurück", tourSkip: "Überspringen",
    tourStartCta: "Mit Klussie starten", tourSetupHomeCta: "Zuerst mein Zuhause einrichten",
    helpSectionTitle: "Hilfe & Erklärung", helpReplayTour: "Rundgang erneut ansehen",
  },

  en: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "What can Klussie help you with today?",
    homeHeroFallbackLabel: "Warm interior of a home",
    homeTabsLabel: "Sections of your home",
    homeTabKlussie: "Klussie", homeTabMyHome: "My Home", homeTabMyItems: "My Items",

    intentsLabel: "What is this about?",
    intentBroken: "Something is broken", intentImprove: "I want to improve something",
    intentMaintain: "I want to plan maintenance", intentAdvice: "I need advice",
    intentOther: "Something else",
    intentChosen: "Chosen", intentChange: "Choose something else",

    homeComposerPlaceholder: "Briefly describe what's going on…",
    homeVoiceAction: "Speak", homePhotoAction: "Add a photo", homeSendAction: "Send",
    homeAnswerLabel: "Your answer",
    followUpProgress: "Question {n} of {total}",
    followUpBack: "Previous question", followUpSkip: "Skip and send",

    safetyTitle: "This may not be safe",
    safetyBody: "Do you smell gas, see fire, is there standing water, or a danger from electricity? Call emergency services or your grid operator first. Klussie does not make a diagnosis.",
    safetyContinue: "Continue with my request anyway", safetyBack: "Back",

    todayHeading: "Today for your home",
    todayQuotesTitle: "Quotes are waiting for your choice",
    todayQuotesBody: "Review the quotes for {service} and choose who does the job.",
    todayBookedTitle: "Your job is scheduled",
    todayBookedBody: "{service} is booked. Your professional will keep you posted.",
    todayAwaitingTitle: "Your request is with one professional",
    todayAwaitingBody: "{service} — you'll hear from us as soon as they respond.",
    todayCollectingTitle: "Professionals are reviewing your request",
    todayCollectingBody: "{service} — quotes usually arrive within a few minutes.",
    todayReviewTitle: "Let us know how it went",
    todayReviewBody: "{service} is finished. Your review helps the next customer.",
    todayOpenCta: "View request",
    todayEmptyTitle: "Make your home smarter with Klussie",
    todayEmptyBody: "Add your first room, installation, or household item.",
    todayEmptyCta: "Set up my home",
    homeActiveTitle: "In progress right now",

    myHomeQuestion: "What would you like to view or keep track of about your home?",
    myHomeAddRoom: "Add a room", myHomeAddInstallation: "Add an installation",
    myHomeUploadDoc: "Upload a document", myHomeLogMaintenance: "Log maintenance",
    homeReportProblem: "Report a problem",
    myHomeSummaryTitle: "Your home at a glance", myHomeRoomsTitle: "Rooms",
    myHomeInstallationsTitle: "Important installations", myHomeMaintenanceTitle: "Upcoming maintenance",
    myHomeDocumentsTitle: "Documents and certificates", myHomeHistoryTitle: "Previous work",
    myHomeHistoryEmpty: "As soon as you complete a job through Klussie, it shows up here.",

    myItemsQuestion: "What would you like to add or find again?",
    myItemsScan: "Scan a product", myItemsReceipt: "Upload a proof of purchase",
    myItemsWarranty: "Check a guarantee", myItemsManual: "Find a manual",
    myItemsAppliances: "Appliances", myItemsElectronics: "Electronics",
    myItemsFurniture: "Furniture and lighting", myItemsGarden: "Garden and tools",
    myItemsRecent: "Recently added",

    homeNothingSavedYet: "You haven't saved anything here yet.",
    homeNotBuiltYet: "Not available yet",
    homeNotBuiltYetNote: "Klussie doesn't store your home or your items yet. We're building it — until then you can't add anything here, and we won't pretend otherwise.",

    tourTitle: "A quick tour of Klussie",
    tourProgress: "Step {n} of {total}",
    tourStep1Title: "Tell or show us what's going on",
    tourStep1Body: "Use text, your voice, or a photo.",
    tourStep2Title: "Klussie asks the right questions",
    tourStep2Body: "Together we turn it into a clear request.",
    tourStep3Title: "Keep everything about your home",
    tourStep3Body: "Track rooms, installations, documents, and maintenance.",
    tourStep4Title: "Track your items and guarantees",
    tourStep4Body: "Keep products, receipts, manuals, and guarantees.",
    tourNext: "Next", tourBack: "Back", tourSkip: "Skip",
    tourStartCta: "Start with Klussie", tourSetupHomeCta: "Set up my home first",
    helpSectionTitle: "Help & explanation", helpReplayTour: "Watch the tour again",
  },

  ar: {
    homeGreetName: "{greeting}، {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "بماذا يمكن أن يساعدك Klussie اليوم؟",
    homeHeroFallbackLabel: "منزل دافئ من الداخل",
    homeTabsLabel: "أقسام منزلك",
    homeTabKlussie: "Klussie", homeTabMyHome: "منزلي", homeTabMyItems: "أغراضي",

    intentsLabel: "عن ماذا يدور الأمر؟",
    intentBroken: "هناك شيء معطّل", intentImprove: "أريد تحسين شيء ما",
    intentMaintain: "أريد جدولة صيانة", intentAdvice: "أحتاج إلى نصيحة",
    intentOther: "شيء آخر",
    intentChosen: "تم الاختيار", intentChange: "اختر شيئًا آخر",

    homeComposerPlaceholder: "صف باختصار ما الذي يحدث…",
    homeVoiceAction: "تحدّث", homePhotoAction: "أضف صورة", homeSendAction: "إرسال",
    homeAnswerLabel: "إجابتك",
    followUpProgress: "السؤال {n} من {total}",
    followUpBack: "السؤال السابق", followUpSkip: "تخطَّ وأرسل",

    safetyTitle: "قد لا يكون هذا آمنًا",
    safetyBody: "هل تشمّ غازًا، أو ترى نارًا، أو هناك مياه راكدة أو خطر كهربائي؟ اتصل أولًا بخدمات الطوارئ أو بمشغّل الشبكة. Klussie لا يقدّم تشخيصًا.",
    safetyContinue: "المتابعة بطلبي على أي حال", safetyBack: "رجوع",

    todayHeading: "اليوم من أجل منزلك",
    todayQuotesTitle: "عروض أسعار بانتظار اختيارك",
    todayQuotesBody: "راجع عروض {service} واختر من سينفّذ العمل.",
    todayBookedTitle: "تم جدولة مهمتك",
    todayBookedBody: "تم حجز {service}. سيبقيك الحرفي على اطّلاع.",
    todayAwaitingTitle: "طلبك لدى حرفي واحد",
    todayAwaitingBody: "{service} — سنخبرك حالما يردّ.",
    todayCollectingTitle: "الحرفيون يراجعون طلبك",
    todayCollectingBody: "{service} — تصل العروض عادةً خلال دقائق.",
    todayReviewTitle: "أخبرنا كيف سارت الأمور",
    todayReviewBody: "اكتمل {service}. تقييمك يساعد العميل التالي.",
    todayOpenCta: "عرض الطلب",
    todayEmptyTitle: "اجعل منزلك أذكى مع Klussie",
    todayEmptyBody: "أضف أول غرفة أو تركيبة أو غرض منزلي.",
    todayEmptyCta: "إعداد منزلي",
    homeActiveTitle: "قيد التنفيذ الآن",

    myHomeQuestion: "ما الذي تريد الاطّلاع عليه أو تتبّعه بشأن منزلك؟",
    myHomeAddRoom: "أضف غرفة", myHomeAddInstallation: "أضف تركيبة",
    myHomeUploadDoc: "ارفع مستندًا", myHomeLogMaintenance: "سجّل صيانة",
    homeReportProblem: "أبلغ عن مشكلة",
    myHomeSummaryTitle: "نظرة عامة على منزلك", myHomeRoomsTitle: "الغرف",
    myHomeInstallationsTitle: "التركيبات المهمة", myHomeMaintenanceTitle: "الصيانة القادمة",
    myHomeDocumentsTitle: "المستندات والشهادات", myHomeHistoryTitle: "أعمال سابقة",
    myHomeHistoryEmpty: "بمجرد إنهاء مهمة عبر Klussie، ستظهر هنا.",

    myItemsQuestion: "ما الذي تريد إضافته أو العثور عليه؟",
    myItemsScan: "امسح منتجًا", myItemsReceipt: "ارفع إثبات شراء",
    myItemsWarranty: "تحقّق من الضمان", myItemsManual: "ابحث عن دليل",
    myItemsAppliances: "الأجهزة المنزلية", myItemsElectronics: "الإلكترونيات",
    myItemsFurniture: "الأثاث والإضاءة", myItemsGarden: "الحديقة والأدوات",
    myItemsRecent: "أُضيف مؤخرًا",

    homeNothingSavedYet: "لم تحفظ شيئًا هنا بعد.",
    homeNotBuiltYet: "غير متاح بعد",
    homeNotBuiltYetNote: "لا يحفظ Klussie منزلك أو أغراضك بعد. نحن نبني ذلك — وحتى ذلك الحين لا يمكنك إضافة شيء هنا، ولن ندّعي العكس.",

    tourTitle: "جولة سريعة في Klussie",
    tourProgress: "الخطوة {n} من {total}",
    tourStep1Title: "احكِ أو أرِنا ما الذي يحدث",
    tourStep1Body: "استخدم النص أو صوتك أو صورة.",
    tourStep2Title: "يطرح Klussie الأسئلة الصحيحة",
    tourStep2Body: "معًا نحوّلها إلى طلب واضح.",
    tourStep3Title: "احتفظ بكل شيء عن منزلك",
    tourStep3Body: "تتبّع الغرف والتركيبات والمستندات والصيانة.",
    tourStep4Title: "تتبّع أغراضك وضماناتك",
    tourStep4Body: "احتفظ بالمنتجات وإثباتات الشراء والأدلة والضمانات.",
    tourNext: "التالي", tourBack: "السابق", tourSkip: "تخطّي",
    tourStartCta: "ابدأ مع Klussie", tourSetupHomeCta: "إعداد منزلي أولًا",
    helpSectionTitle: "المساعدة والشرح", helpReplayTour: "إعادة مشاهدة الجولة",
  },

  tr: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "Klussie bugün sana nasıl yardımcı olabilir?",
    homeHeroFallbackLabel: "Sıcak bir ev içi",
    homeTabsLabel: "Evinin bölümleri",
    homeTabKlussie: "Klussie", homeTabMyHome: "Evim", homeTabMyItems: "Eşyalarım",

    intentsLabel: "Konu ne?",
    intentBroken: "Bir şey bozuldu", intentImprove: "Bir şeyi iyileştirmek istiyorum",
    intentMaintain: "Bakım planlamak istiyorum", intentAdvice: "Tavsiyeye ihtiyacım var",
    intentOther: "Başka bir şey",
    intentChosen: "Seçildi", intentChange: "Başka bir şey seç",

    homeComposerPlaceholder: "Kısaca neler olduğunu anlat…",
    homeVoiceAction: "Konuş", homePhotoAction: "Fotoğraf ekle", homeSendAction: "Gönder",
    homeAnswerLabel: "Yanıtın",
    followUpProgress: "Soru {n} / {total}",
    followUpBack: "Önceki soru", followUpSkip: "Atla ve gönder",

    safetyTitle: "Bu güvenli olmayabilir",
    safetyBody: "Gaz kokusu alıyor, ateş görüyor, su birikmesi ya da elektrik tehlikesi mi var? Önce acil servisi veya şebeke operatörünü ara. Klussie teşhis koymaz.",
    safetyContinue: "Yine de talebimle devam et", safetyBack: "Geri",

    todayHeading: "Bugün evin için",
    todayQuotesTitle: "Teklifler seçimini bekliyor",
    todayQuotesBody: "{service} için teklifleri incele ve işi kimin yapacağını seç.",
    todayBookedTitle: "İşin planlandı",
    todayBookedBody: "{service} rezerve edildi. Ustan seni bilgilendirecek.",
    todayAwaitingTitle: "Talebin tek bir ustada",
    todayAwaitingBody: "{service} — yanıt verir vermez haber vereceğiz.",
    todayCollectingTitle: "Ustalar talebini inceliyor",
    todayCollectingBody: "{service} — teklifler genellikle birkaç dakika içinde gelir.",
    todayReviewTitle: "Nasıl geçtiğini bize anlat",
    todayReviewBody: "{service} tamamlandı. Değerlendirmen sonraki müşteriye yardımcı olur.",
    todayOpenCta: "Talebi görüntüle",
    todayEmptyTitle: "Klussie ile evini daha akıllı yap",
    todayEmptyBody: "İlk odanı, tesisatını veya ev eşyanı ekle.",
    todayEmptyCta: "Evimi ayarla",
    homeActiveTitle: "Şu anda devam ediyor",

    myHomeQuestion: "Evinle ilgili neyi görmek veya takip etmek istersin?",
    myHomeAddRoom: "Oda ekle", myHomeAddInstallation: "Tesisat ekle",
    myHomeUploadDoc: "Belge yükle", myHomeLogMaintenance: "Bakım kaydet",
    homeReportProblem: "Sorun bildir",
    myHomeSummaryTitle: "Evine genel bakış", myHomeRoomsTitle: "Odalar",
    myHomeInstallationsTitle: "Önemli tesisatlar", myHomeMaintenanceTitle: "Yaklaşan bakım",
    myHomeDocumentsTitle: "Belgeler ve sertifikalar", myHomeHistoryTitle: "Önceki işler",
    myHomeHistoryEmpty: "Klussie üzerinden bir işi tamamladığında burada görünür.",

    myItemsQuestion: "Ne eklemek veya yeniden bulmak istersin?",
    myItemsScan: "Ürün tara", myItemsReceipt: "Satın alma belgesi yükle",
    myItemsWarranty: "Garantiyi kontrol et", myItemsManual: "Kılavuz ara",
    myItemsAppliances: "Beyaz eşya", myItemsElectronics: "Elektronik",
    myItemsFurniture: "Mobilya ve aydınlatma", myItemsGarden: "Bahçe ve aletler",
    myItemsRecent: "Yakında eklenenler",

    homeNothingSavedYet: "Burada henüz bir şey kaydetmedin.",
    homeNotBuiltYet: "Henüz kullanılamıyor",
    homeNotBuiltYetNote: "Klussie evini ve eşyalarını henüz saklamıyor. Bunu geliştiriyoruz — o zamana kadar buraya bir şey ekleyemezsin ve öyleymiş gibi de yapmıyoruz.",

    tourTitle: "Klussie'ye kısa bir tur",
    tourProgress: "Adım {n} / {total}",
    tourStep1Title: "Neler olduğunu anlat veya göster",
    tourStep1Body: "Metin, ses veya fotoğraf kullan.",
    tourStep2Title: "Klussie doğru soruları sorar",
    tourStep2Body: "Birlikte net bir talep oluştururuz.",
    tourStep3Title: "Evinle ilgili her şeyi sakla",
    tourStep3Body: "Odaları, tesisatları, belgeleri ve bakımı takip et.",
    tourStep4Title: "Eşyalarını ve garantilerini takip et",
    tourStep4Body: "Ürünleri, fişleri, kılavuzları ve garantileri sakla.",
    tourNext: "İleri", tourBack: "Geri", tourSkip: "Atla",
    tourStartCta: "Klussie ile başla", tourSetupHomeCta: "Önce evimi ayarla",
    helpSectionTitle: "Yardım ve açıklama", helpReplayTour: "Turu tekrar izle",
  },

  ru: {
    homeGreetName: "{greeting}, {name}", homeGreetNoName: "{greeting}",
    homeQuestion: "Чем Klussie может помочь вам сегодня?",
    homeHeroFallbackLabel: "Тёплый интерьер дома",
    homeTabsLabel: "Разделы вашего дома",
    homeTabKlussie: "Klussie", homeTabMyHome: "Мой дом", homeTabMyItems: "Мои вещи",

    intentsLabel: "О чём речь?",
    intentBroken: "Что-то сломалось", intentImprove: "Хочу что-то улучшить",
    intentMaintain: "Хочу запланировать обслуживание", intentAdvice: "Нужен совет",
    intentOther: "Что-то другое",
    intentChosen: "Выбрано", intentChange: "Выбрать другое",

    homeComposerPlaceholder: "Кратко опишите, что происходит…",
    homeVoiceAction: "Сказать голосом", homePhotoAction: "Добавить фото", homeSendAction: "Отправить",
    homeAnswerLabel: "Ваш ответ",
    followUpProgress: "Вопрос {n} из {total}",
    followUpBack: "Предыдущий вопрос", followUpSkip: "Пропустить и отправить",

    safetyTitle: "Возможно, это небезопасно",
    safetyBody: "Чувствуете запах газа, видите огонь, стоит вода или есть опасность от электричества? Сначала позвоните в экстренные службы или своему сетевому оператору. Klussie не ставит диагноз.",
    safetyContinue: "Всё равно продолжить заявку", safetyBack: "Назад",

    todayHeading: "Сегодня для вашего дома",
    todayQuotesTitle: "Предложения ждут вашего выбора",
    todayQuotesBody: "Посмотрите предложения по услуге «{service}» и выберите исполнителя.",
    todayBookedTitle: "Работа запланирована",
    todayBookedBody: "«{service}» забронировано. Мастер будет держать вас в курсе.",
    todayAwaitingTitle: "Ваша заявка у одного мастера",
    todayAwaitingBody: "«{service}» — мы сообщим, как только он ответит.",
    todayCollectingTitle: "Мастера изучают вашу заявку",
    todayCollectingBody: "«{service}» — предложения обычно приходят за несколько минут.",
    todayReviewTitle: "Расскажите, как всё прошло",
    todayReviewBody: "«{service}» завершено. Ваш отзыв поможет следующему клиенту.",
    todayOpenCta: "Открыть заявку",
    todayEmptyTitle: "Сделайте свой дом умнее с Klussie",
    todayEmptyBody: "Добавьте первую комнату, установку или бытовую вещь.",
    todayEmptyCta: "Настроить мой дом",
    homeActiveTitle: "Сейчас в работе",

    myHomeQuestion: "Что вы хотите посмотреть или вести по своему дому?",
    myHomeAddRoom: "Добавить комнату", myHomeAddInstallation: "Добавить установку",
    myHomeUploadDoc: "Загрузить документ", myHomeLogMaintenance: "Записать обслуживание",
    homeReportProblem: "Сообщить о проблеме",
    myHomeSummaryTitle: "Ваш дом в общих чертах", myHomeRoomsTitle: "Комнаты",
    myHomeInstallationsTitle: "Важные установки", myHomeMaintenanceTitle: "Предстоящее обслуживание",
    myHomeDocumentsTitle: "Документы и сертификаты", myHomeHistoryTitle: "Прошлые работы",
    myHomeHistoryEmpty: "Как только вы завершите работу через Klussie, она появится здесь.",

    myItemsQuestion: "Что вы хотите добавить или найти снова?",
    myItemsScan: "Сканировать товар", myItemsReceipt: "Загрузить чек",
    myItemsWarranty: "Проверить гарантию", myItemsManual: "Найти инструкцию",
    myItemsAppliances: "Бытовая техника", myItemsElectronics: "Электроника",
    myItemsFurniture: "Мебель и освещение", myItemsGarden: "Сад и инструменты",
    myItemsRecent: "Недавно добавленное",

    homeNothingSavedYet: "Вы ещё ничего здесь не сохранили.",
    homeNotBuiltYet: "Пока недоступно",
    homeNotBuiltYetNote: "Klussie пока не хранит данные о вашем доме и вещах. Мы это создаём — до тех пор сюда ничего нельзя добавить, и мы не делаем вид, что можно.",

    tourTitle: "Короткая экскурсия по Klussie",
    tourProgress: "Шаг {n} из {total}",
    tourStep1Title: "Расскажите или покажите, что случилось",
    tourStep1Body: "Используйте текст, голос или фото.",
    tourStep2Title: "Klussie задаёт нужные вопросы",
    tourStep2Body: "Вместе мы составим понятную заявку.",
    tourStep3Title: "Храните всё о своём доме",
    tourStep3Body: "Ведите комнаты, установки, документы и обслуживание.",
    tourStep4Title: "Следите за вещами и гарантиями",
    tourStep4Body: "Храните товары, чеки, инструкции и гарантии.",
    tourNext: "Далее", tourBack: "Назад", tourSkip: "Пропустить",
    tourStartCta: "Начать с Klussie", tourSetupHomeCta: "Сначала настроить мой дом",
    helpSectionTitle: "Помощь и пояснения", helpReplayTour: "Пересмотреть экскурсию",
  },

  zh: {
    homeGreetName: "{greeting}，{name}", homeGreetNoName: "{greeting}",
    homeQuestion: "今天 Klussie 能帮你做什么？",
    homeHeroFallbackLabel: "温馨的住宅室内",
    homeTabsLabel: "你家的各个板块",
    homeTabKlussie: "Klussie", homeTabMyHome: "我的住宅", homeTabMyItems: "我的物品",

    intentsLabel: "是关于什么的？",
    intentBroken: "有东西坏了", intentImprove: "我想改善某处",
    intentMaintain: "我想安排保养", intentAdvice: "我需要建议",
    intentOther: "其他事情",
    intentChosen: "已选择", intentChange: "换一个",

    homeComposerPlaceholder: "简单说说发生了什么……",
    homeVoiceAction: "语音描述", homePhotoAction: "添加照片", homeSendAction: "发送",
    homeAnswerLabel: "你的回答",
    followUpProgress: "第 {n} 个问题，共 {total} 个",
    followUpBack: "上一个问题", followUpSkip: "跳过并发送",

    safetyTitle: "这可能不安全",
    safetyBody: "闻到煤气、看到明火、有积水或存在触电危险吗？请先联系急救部门或供电供气单位。Klussie 不做诊断。",
    safetyContinue: "仍然继续我的申请", safetyBack: "返回",

    todayHeading: "今天为你的家",
    todayQuotesTitle: "报价正在等你选择",
    todayQuotesBody: "查看「{service}」的报价，选择由谁来做。",
    todayBookedTitle: "你的工作已排期",
    todayBookedBody: "「{service}」已预订。师傅会随时告知进展。",
    todayAwaitingTitle: "你的申请已发给一位师傅",
    todayAwaitingBody: "「{service}」——对方回复后我们会通知你。",
    todayCollectingTitle: "师傅们正在查看你的申请",
    todayCollectingBody: "「{service}」——报价通常几分钟内送达。",
    todayReviewTitle: "告诉我们进行得如何",
    todayReviewBody: "「{service}」已完成。你的评价能帮到下一位客户。",
    todayOpenCta: "查看申请",
    todayEmptyTitle: "用 Klussie 让你的家更聪明",
    todayEmptyBody: "添加第一个房间、设备或家居物品。",
    todayEmptyCta: "设置我的住宅",
    homeActiveTitle: "正在进行中",

    myHomeQuestion: "关于你的住宅，你想查看或记录什么？",
    myHomeAddRoom: "添加房间", myHomeAddInstallation: "添加设备",
    myHomeUploadDoc: "上传文件", myHomeLogMaintenance: "记录保养",
    homeReportProblem: "报告问题",
    myHomeSummaryTitle: "住宅概览", myHomeRoomsTitle: "房间",
    myHomeInstallationsTitle: "重要设备", myHomeMaintenanceTitle: "即将到期的保养",
    myHomeDocumentsTitle: "文件与证书", myHomeHistoryTitle: "过往施工",
    myHomeHistoryEmpty: "通过 Klussie 完成一次工作后，就会出现在这里。",

    myItemsQuestion: "你想添加或找回什么？",
    myItemsScan: "扫描产品", myItemsReceipt: "上传购买凭证",
    myItemsWarranty: "查看保修", myItemsManual: "查找说明书",
    myItemsAppliances: "家用电器", myItemsElectronics: "电子产品",
    myItemsFurniture: "家具与照明", myItemsGarden: "花园与工具",
    myItemsRecent: "最近添加",

    homeNothingSavedYet: "你还没有在这里保存任何内容。",
    homeNotBuiltYet: "尚未开放",
    homeNotBuiltYetNote: "Klussie 目前还不会保存你的住宅和物品资料。我们正在开发——在那之前这里无法添加内容，我们也不会假装可以。",

    tourTitle: "Klussie 快速导览",
    tourProgress: "第 {n} 步，共 {total} 步",
    tourStep1Title: "说出或拍下发生了什么",
    tourStep1Body: "可以用文字、语音或照片。",
    tourStep2Title: "Klussie 会问对的问题",
    tourStep2Body: "我们一起整理成一份清晰的申请。",
    tourStep3Title: "记录关于住宅的一切",
    tourStep3Body: "管理房间、设备、文件和保养。",
    tourStep4Title: "追踪物品与保修",
    tourStep4Body: "保存产品、购买凭证、说明书和保修。",
    tourNext: "下一步", tourBack: "上一步", tourSkip: "跳过",
    tourStartCta: "开始使用 Klussie", tourSetupHomeCta: "先设置我的住宅",
    helpSectionTitle: "帮助与说明", helpReplayTour: "重新观看导览",
  },
};

// Fills {placeholder} slots in a localized template. Kept here next to the copy it
// serves rather than in a component, so every call site interpolates the same way —
// a missing key must show as a literal "{name}", not as an empty string that hides
// the bug (the pattern src/__tests__/conversationHome.test.jsx already pins).
export function interpolate(template, values) {
  if (!template) return "";
  return Object.keys(values || {}).reduce(
    (acc, key) => acc.split(`{${key}}`).join(values[key]),
    template
  );
}
