// The follow-up questions each homepage intent opens with, in all 10 locales.
//
// Split from homeStrings.js purely by size — these 21 keys are one coherent block
// (the question bank) and keeping them apart makes both files reviewable. Merged
// into `t` alongside HOME_STRINGS by App(), so call sites see one flat lookup.
//
// The *order* and the *conditions* under which each question is asked are not here:
// that is configuration, and it lives in src/lib/homeIntents.js. This file only
// owns the words.

export const FOLLOW_UP_STRINGS = {
  nl: {
    fuBrokenWhat: "Wat werkt er niet?",
    fuBrokenWhere: "Waar in je woning is dat?",
    fuBrokenPhoto: "Kun je het laten zien met een foto?",
    fuBrokenSince: "Sinds wanneer is dat zo?",
    fuBrokenUrgent: "Is het dringend of mogelijk onveilig?",
    fuBrokenWhen: "Wanneer zou een vakman mogen komen?",
    fuImproveWhat: "Wat wil je verbeteren?",
    fuImproveWhere: "Welke ruimte of welk deel van je woning?",
    fuImproveResult: "Welk resultaat wil je bereiken?",
    fuImproveInspiration: "Heb je inspiratiefoto's?",
    fuImproveBudget: "Heb je al een richtbudget in gedachten?",
    fuImproveWhen: "Wanneer zou het werk mogen starten?",
    fuMaintainWhat: "Wat heeft onderhoud nodig?",
    fuMaintainLast: "Wanneer is het voor het laatst onderhouden?",
    fuMaintainSaved: "Staat het al bij Mijn woning?",
    fuMaintainRecurring: "Is dit eenmalig of terugkerend?",
    fuMaintainDates: "Welke data passen jou?",
    fuAdviceAbout: "Waarover twijfel je?",
    fuAdviceTopic: "Gaat het over kosten, herstel, renovatie, energie of veiligheid?",
    fuAdviceDoc: "Kun je een foto of document toevoegen?",
    fuAdviceWant: "Wil je alleen advies, of ook offertes van vakmensen?",
  },
  fr: {
    fuBrokenWhat: "Qu'est-ce qui ne fonctionne pas ?",
    fuBrokenWhere: "Où cela se trouve-t-il dans ton logement ?",
    fuBrokenPhoto: "Peux-tu le montrer avec une photo ?",
    fuBrokenSince: "Depuis quand est-ce ainsi ?",
    fuBrokenUrgent: "Est-ce urgent ou potentiellement dangereux ?",
    fuBrokenWhen: "Quand un pro pourrait-il passer ?",
    fuImproveWhat: "Que veux-tu améliorer ?",
    fuImproveWhere: "Quelle pièce ou quelle partie du logement ?",
    fuImproveResult: "Quel résultat souhaites-tu obtenir ?",
    fuImproveInspiration: "As-tu des photos d'inspiration ?",
    fuImproveBudget: "As-tu déjà un budget indicatif en tête ?",
    fuImproveWhen: "Quand les travaux pourraient-ils commencer ?",
    fuMaintainWhat: "Qu'est-ce qui a besoin d'entretien ?",
    fuMaintainLast: "Quand cela a-t-il été entretenu pour la dernière fois ?",
    fuMaintainSaved: "Est-ce déjà enregistré dans Mon logement ?",
    fuMaintainRecurring: "Est-ce ponctuel ou récurrent ?",
    fuMaintainDates: "Quelles dates te conviennent ?",
    fuAdviceAbout: "Sur quoi hésites-tu ?",
    fuAdviceTopic: "S'agit-il de coûts, de réparation, de rénovation, d'énergie ou de sécurité ?",
    fuAdviceDoc: "Peux-tu ajouter une photo ou un document ?",
    fuAdviceWant: "Veux-tu seulement un conseil, ou aussi des devis de pros ?",
  },
  de: {
    fuBrokenWhat: "Was funktioniert nicht?",
    fuBrokenWhere: "Wo in deinem Zuhause ist das?",
    fuBrokenPhoto: "Kannst du es mit einem Foto zeigen?",
    fuBrokenSince: "Seit wann ist das so?",
    fuBrokenUrgent: "Ist es dringend oder möglicherweise gefährlich?",
    fuBrokenWhen: "Wann dürfte ein Profi kommen?",
    fuImproveWhat: "Was möchtest du verbessern?",
    fuImproveWhere: "Welcher Raum oder welcher Teil deines Zuhauses?",
    fuImproveResult: "Welches Ergebnis möchtest du erreichen?",
    fuImproveInspiration: "Hast du Inspirationsfotos?",
    fuImproveBudget: "Hast du schon ein ungefähres Budget im Kopf?",
    fuImproveWhen: "Wann dürften die Arbeiten starten?",
    fuMaintainWhat: "Was braucht Wartung?",
    fuMaintainLast: "Wann wurde es zuletzt gewartet?",
    fuMaintainSaved: "Steht es schon unter Mein Zuhause?",
    fuMaintainRecurring: "Ist das einmalig oder wiederkehrend?",
    fuMaintainDates: "Welche Termine passen dir?",
    fuAdviceAbout: "Worüber bist du unsicher?",
    fuAdviceTopic: "Geht es um Kosten, Reparatur, Renovierung, Energie oder Sicherheit?",
    fuAdviceDoc: "Kannst du ein Foto oder Dokument hinzufügen?",
    fuAdviceWant: "Möchtest du nur eine Einschätzung oder auch Angebote von Profis?",
  },
  en: {
    fuBrokenWhat: "What isn't working?",
    fuBrokenWhere: "Where in your home is it?",
    fuBrokenPhoto: "Can you show it with a photo?",
    fuBrokenSince: "When did it start?",
    fuBrokenUrgent: "Is it urgent or possibly unsafe?",
    fuBrokenWhen: "When could a professional come by?",
    fuImproveWhat: "What would you like to improve?",
    fuImproveWhere: "Which room or part of your home?",
    fuImproveResult: "What result are you hoping for?",
    fuImproveInspiration: "Do you have inspiration photos?",
    fuImproveBudget: "Do you have a rough budget in mind?",
    fuImproveWhen: "When could the work start?",
    fuMaintainWhat: "What needs maintenance?",
    fuMaintainLast: "When was it last maintained?",
    fuMaintainSaved: "Is it already saved under My Home?",
    fuMaintainRecurring: "Is this one-time or recurring?",
    fuMaintainDates: "Which dates work for you?",
    fuAdviceAbout: "What are you unsure about?",
    fuAdviceTopic: "Is it about cost, repair, renovation, energy, or safety?",
    fuAdviceDoc: "Can you add a photo or a document?",
    fuAdviceWant: "Do you want guidance only, or also quotes from professionals?",
  },
  es: {
    fuBrokenWhat: "¿Qué no funciona?",
    fuBrokenWhere: "¿En qué parte de tu casa está?",
    fuBrokenPhoto: "¿Puedes enseñarlo con una foto?",
    fuBrokenSince: "¿Desde cuándo pasa?",
    fuBrokenUrgent: "¿Es urgente o puede ser peligroso?",
    fuBrokenWhen: "¿Cuándo podría pasar un profesional?",
    fuImproveWhat: "¿Qué te gustaría mejorar?",
    fuImproveWhere: "¿Qué habitación o parte de tu casa?",
    fuImproveResult: "¿Qué resultado esperas?",
    fuImproveInspiration: "¿Tienes fotos de inspiración?",
    fuImproveBudget: "¿Tienes un presupuesto aproximado en mente?",
    fuImproveWhen: "¿Cuándo podrían empezar los trabajos?",
    fuMaintainWhat: "¿Qué necesita mantenimiento?",
    fuMaintainLast: "¿Cuándo se hizo el último mantenimiento?",
    fuMaintainSaved: "¿Ya está guardado en Mi vivienda?",
    fuMaintainRecurring: "¿Es puntual o periódico?",
    fuMaintainDates: "¿Qué fechas te vienen bien?",
    fuAdviceAbout: "¿Sobre qué tienes dudas?",
    fuAdviceTopic: "¿Se trata de coste, reparación, reforma, energía o seguridad?",
    fuAdviceDoc: "¿Puedes añadir una foto o un documento?",
    fuAdviceWant: "¿Quieres solo orientación o también presupuestos de profesionales?",
  },
  ar: {
    fuBrokenWhat: "ما الذي لا يعمل؟",
    fuBrokenWhere: "أين يقع ذلك في منزلك؟",
    fuBrokenPhoto: "هل يمكنك إظهاره بصورة؟",
    fuBrokenSince: "منذ متى وهو كذلك؟",
    fuBrokenUrgent: "هل الأمر عاجل أو قد يكون غير آمن؟",
    fuBrokenWhen: "متى يمكن أن يمرّ الحرفي؟",
    fuImproveWhat: "ما الذي تريد تحسينه؟",
    fuImproveWhere: "أي غرفة أو أي جزء من المنزل؟",
    fuImproveResult: "ما النتيجة التي تريدها؟",
    fuImproveInspiration: "هل لديك صور مُلهِمة؟",
    fuImproveBudget: "هل لديك ميزانية تقريبية في ذهنك؟",
    fuImproveWhen: "متى يمكن أن يبدأ العمل؟",
    fuMaintainWhat: "ما الذي يحتاج إلى صيانة؟",
    fuMaintainLast: "متى تمت صيانته آخر مرة؟",
    fuMaintainSaved: "هل هو محفوظ بالفعل في «منزلي»؟",
    fuMaintainRecurring: "هل هذا لمرة واحدة أم متكرر؟",
    fuMaintainDates: "ما التواريخ التي تناسبك؟",
    fuAdviceAbout: "ما الذي تتردد بشأنه؟",
    fuAdviceTopic: "هل يتعلق الأمر بالتكلفة أو الإصلاح أو التجديد أو الطاقة أو السلامة؟",
    fuAdviceDoc: "هل يمكنك إضافة صورة أو مستند؟",
    fuAdviceWant: "هل تريد النصيحة فقط أم عروض أسعار من الحرفيين أيضًا؟",
  },
  fa: {
    fuBrokenWhat: "چه چیزی کار نمی‌کند؟",
    fuBrokenWhere: "کجای خانه‌تان است؟",
    fuBrokenPhoto: "می‌توانید با یک عکس نشان دهید؟",
    fuBrokenSince: "از چه زمانی شروع شده؟",
    fuBrokenUrgent: "فوری است یا احتمال خطر دارد؟",
    fuBrokenWhen: "چه زمانی متخصص می‌تواند بیاید؟",
    fuImproveWhat: "چه چیزی را می‌خواهید بهتر کنید؟",
    fuImproveWhere: "کدام اتاق یا کدام بخش از خانه؟",
    fuImproveResult: "به چه نتیجه‌ای می‌خواهید برسید؟",
    fuImproveInspiration: "عکس نمونه یا ایده دارید؟",
    fuImproveBudget: "بودجه تقریبی در ذهن دارید؟",
    fuImproveWhen: "کار از چه زمانی می‌تواند شروع شود؟",
    fuMaintainWhat: "چه چیزی نیاز به سرویس دارد؟",
    fuMaintainLast: "آخرین بار کی سرویس شد؟",
    fuMaintainSaved: "آیا از قبل در «خانه من» ذخیره شده است؟",
    fuMaintainRecurring: "یک‌باره است یا دوره‌ای؟",
    fuMaintainDates: "چه تاریخ‌هایی برایتان مناسب است؟",
    fuAdviceAbout: "درباره چه چیزی تردید دارید؟",
    fuAdviceTopic: "موضوع هزینه است، تعمیر، بازسازی، انرژی یا ایمنی؟",
    fuAdviceDoc: "می‌توانید عکس یا سندی اضافه کنید؟",
    fuAdviceWant: "فقط راهنمایی می‌خواهید یا پیشنهاد قیمت از متخصصان هم؟",
  },
  tr: {
    fuBrokenWhat: "Ne çalışmıyor?",
    fuBrokenWhere: "Evinin neresinde?",
    fuBrokenPhoto: "Bir fotoğrafla gösterebilir misin?",
    fuBrokenSince: "Ne zamandır böyle?",
    fuBrokenUrgent: "Acil mi, güvenli olmayabilir mi?",
    fuBrokenWhen: "Bir usta ne zaman gelebilir?",
    fuImproveWhat: "Neyi iyileştirmek istiyorsun?",
    fuImproveWhere: "Hangi oda ya da evin hangi bölümü?",
    fuImproveResult: "Nasıl bir sonuç istiyorsun?",
    fuImproveInspiration: "İlham veren fotoğrafların var mı?",
    fuImproveBudget: "Aklında kabaca bir bütçe var mı?",
    fuImproveWhen: "Çalışma ne zaman başlayabilir?",
    fuMaintainWhat: "Neyin bakıma ihtiyacı var?",
    fuMaintainLast: "En son ne zaman bakım yapıldı?",
    fuMaintainSaved: "Evim bölümünde kayıtlı mı?",
    fuMaintainRecurring: "Bu tek seferlik mi, tekrarlayan mı?",
    fuMaintainDates: "Hangi tarihler sana uyar?",
    fuAdviceAbout: "Neyden emin değilsin?",
    fuAdviceTopic: "Konu maliyet mi, onarım mı, tadilat mı, enerji mi, güvenlik mi?",
    fuAdviceDoc: "Bir fotoğraf veya belge ekleyebilir misin?",
    fuAdviceWant: "Sadece tavsiye mi istiyorsun, yoksa ustalardan teklif de mi?",
  },
  ru: {
    fuBrokenWhat: "Что не работает?",
    fuBrokenWhere: "Где именно в доме это находится?",
    fuBrokenPhoto: "Можете показать это на фото?",
    fuBrokenSince: "С каких пор это так?",
    fuBrokenUrgent: "Это срочно или может быть небезопасно?",
    fuBrokenWhen: "Когда мастеру удобно приехать?",
    fuImproveWhat: "Что вы хотите улучшить?",
    fuImproveWhere: "Какая комната или какая часть дома?",
    fuImproveResult: "Какого результата вы хотите добиться?",
    fuImproveInspiration: "Есть ли у вас фото для вдохновения?",
    fuImproveBudget: "Есть ли примерный бюджет?",
    fuImproveWhen: "Когда работы могут начаться?",
    fuMaintainWhat: "Что требует обслуживания?",
    fuMaintainLast: "Когда его обслуживали в последний раз?",
    fuMaintainSaved: "Это уже сохранено в разделе «Мой дом»?",
    fuMaintainRecurring: "Это разово или регулярно?",
    fuMaintainDates: "Какие даты вам подходят?",
    fuAdviceAbout: "В чём вы сомневаетесь?",
    fuAdviceTopic: "Речь о стоимости, ремонте, реновации, энергии или безопасности?",
    fuAdviceDoc: "Можете добавить фото или документ?",
    fuAdviceWant: "Вам нужен только совет или ещё и предложения мастеров?",
  },
  zh: {
    fuBrokenWhat: "什么坏了？",
    fuBrokenWhere: "在家里的哪个位置？",
    fuBrokenPhoto: "能拍张照片给我们看看吗？",
    fuBrokenSince: "从什么时候开始的？",
    fuBrokenUrgent: "是否紧急，或可能不安全？",
    fuBrokenWhen: "师傅什么时候方便上门？",
    fuImproveWhat: "你想改善什么？",
    fuImproveWhere: "哪个房间或家里的哪个部分？",
    fuImproveResult: "你希望达到什么效果？",
    fuImproveInspiration: "有参考图片吗？",
    fuImproveBudget: "心里有大致预算吗？",
    fuImproveWhen: "工作什么时候可以开始？",
    fuMaintainWhat: "什么需要保养？",
    fuMaintainLast: "上一次保养是什么时候？",
    fuMaintainSaved: "它已经保存在「我的住宅」里了吗？",
    fuMaintainRecurring: "这是一次性的还是定期的？",
    fuMaintainDates: "哪些日期适合你？",
    fuAdviceAbout: "你在犹豫什么？",
    fuAdviceTopic: "是关于费用、维修、翻新、能源还是安全？",
    fuAdviceDoc: "能添加一张照片或一份文件吗？",
    fuAdviceWant: "你只想要建议，还是也想要师傅的报价？",
  },
};
