// UUIDv7 generation for aggregate identifiers.
//
// SUPABASE_ARCHITECTURE.md §3: "UUIDv7 for every aggregate identifier, generated by the
// application rather than the database." Both halves have reasons, and both shape what is
// below.
//
// WHY THE APPLICATION GENERATES THEM. An engine must know an aggregate's identity before
// it writes, so it can emit an event referencing it in the same transaction (§12,
// constraint 5). Waiting for the database to assign one forces either a round trip or a
// deferred event, and a deferred event is a change without an event.
//
// WHY v7 RATHER THAN v4. Random identifiers scatter B-tree inserts across every page of
// the index, so at billions of event rows every insert dirties a different page.
// Time-ordered identifiers keep inserts at the right-hand edge, which reduces write
// amplification, keeps caches warm, and makes range scans by recency — the dominant access
// pattern for events, messages, transitions and notifications — physically sequential.
//
// That benefit depends entirely on the values actually being ordered, which is why the
// monotonicity below is the substance of this module rather than a detail. A v7 that
// reorders within a millisecond is a v4 with extra steps for any burst of writes, and
// bursts are exactly when it matters.
//
// This is the runtime generator. Backfills mint their identifiers in SQL instead
// (ADR-0022), from each row's own creation time, through a function no engine can execute.

// RFC 9562 §5.7 layout:
//   48 bits  unix timestamp in milliseconds
//    4 bits  version (0111)
//   12 bits  rand_a — used here as a monotonic counter
//    2 bits  variant (10)
//   62 bits  rand_b — random
const VERSION_NIBBLE = "7";
const COUNTER_BITS = 12;
const MAX_COUNTER = (1 << COUNTER_BITS) - 1;

// A new millisecond seeds the counter in its lower half, leaving roughly two thousand
// increments of headroom before the borrow path below is needed. Seeding at zero would be
// simpler and would leak the number of identifiers issued in each millisecond to anyone
// who sees two of them.
const COUNTER_SEED_CEILING = 1 << (COUNTER_BITS - 1);

let lastTimestamp = -1;
let counter = 0;

function randomBytes(length: number): Uint8Array {
  return crypto.getRandomValues(new Uint8Array(length));
}

function seedCounter(): number {
  const [high, low] = randomBytes(2);
  return (((high << 8) | low) >>> 0) % COUNTER_SEED_CEILING;
}

/**
 * Advances the generator state, and is where every ordering guarantee is actually made.
 *
 * Three cases, and the two that are not the happy path are the ones that matter:
 *
 * - **A later millisecond** — take it, reseed the counter.
 * - **The same millisecond, or an earlier one** — increment the counter and keep the
 *   timestamp we already issued. That covers a burst within one millisecond *and* a clock
 *   that has gone backwards, which happens on NTP correction and on any virtual machine
 *   that has been suspended. Trusting the clock in that moment would issue an identifier
 *   below one already written.
 * - **The counter is exhausted** — borrow a millisecond from the future rather than wrap.
 *   The identifier is then a fraction of a millisecond "early", which is a rounding error;
 *   wrapping would emit a value below its predecessor, which breaks the ordering the whole
 *   type exists for.
 */
function advance(nowMs: number): { timestamp: number; counter: number } {
  if (nowMs > lastTimestamp) {
    lastTimestamp = nowMs;
    counter = seedCounter();
  } else if (counter >= MAX_COUNTER) {
    lastTimestamp += 1;
    counter = seedCounter();
  } else {
    counter += 1;
  }

  return { timestamp: lastTimestamp, counter };
}

function toHex(bytes: Uint8Array): string {
  let hex = "";
  for (const byte of bytes) hex += byte.toString(16).padStart(2, "0");
  return hex;
}

/**
 * Generates a UUIDv7.
 *
 * `nowMs` is injectable so a test can pin a millisecond and prove ordering within it,
 * matching the house pattern (`timeGreeting(t, now)` in `src/home/useHomeContext.js`). It
 * is not a way to backdate an identifier: the generator never issues a value below one it
 * has already issued, whatever it is told the time is.
 */
export function uuidv7(nowMs: number = Date.now()): string {
  const { timestamp, counter: sequence } = advance(nowMs);

  const random = randomBytes(8);
  // The variant, written into the top two bits of the first random byte: 10xx xxxx.
  random[0] = (random[0] & 0x3f) | 0x80;

  const hex =
    timestamp.toString(16).padStart(12, "0") +
    VERSION_NIBBLE +
    sequence.toString(16).padStart(3, "0") +
    toHex(random);

  return [
    hex.slice(0, 8),
    hex.slice(8, 12),
    hex.slice(12, 16),
    hex.slice(16, 20),
    hex.slice(20),
  ].join("-");
}
