// Keeps 0025_identity.sql inside the two rules SUPABASE_ARCHITECTURE.md §11.4 imposes on
// every migration in this epic — and on every migration after it.
//
// Both are broken by writing something that looks entirely ordinary:
//
//   · A foreign key to the identity row. It is the obviously correct thing to write, it
//     is what a reviewer expects to see, and it makes erasure either impossible or
//     destructive.
//   · A copy of personal data on a durable record. A display name denormalised into a
//     service record for convenience is a personal-data leak that erasure cannot reach.
//
// The first is checked here for this migration and across the whole database by
// VERIFY_IDENTITY.sql check 2, because the migration that breaks it will not be this one.
//
// Structural. Behaviour is proven against staging by that diagnostic.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";

const MIGRATION = "supabase/migrations/0025_identity.sql";

// Line comments AND string literals are stripped, so what is matched below is executable
// DDL only. The literals matter here in a way they have not in earlier migrations: this
// file's `comment on column` bodies explain *why there is no foreign key*, and a test
// searching the raw text for "foreign key" finds the explanation and fails on the
// documentation. Stripping them is the difference between asserting what the migration
// does and asserting what it says about itself.
const code = readFileSync(MIGRATION, "utf8")
  .split("\n")
  .filter((line) => !line.trimStart().startsWith("--"))
  .join("\n")
  .replace(/'(?:[^']|'')*'/g, "''");

describe("0025_identity migration", () => {
  it("declares no foreign key, in either direction", () => {
    // Out of the table as well as into it: §11.4 says deleting an auth user must never
    // cascade, and a foreign key would have to choose an ON DELETE behaviour. Every choice
    // couples two lifecycles the architecture requires to be separable.
    expect(code).not.toMatch(/\breferences\b/i);
    expect(code).not.toMatch(/\bforeign key\b/i);
    expect(code).not.toMatch(/\bon delete\b/i);
  });

  it("gives the person reference no database default", () => {
    // §3: UUIDv7, application-generated, because an engine must know an aggregate's
    // identity before it writes so it can emit an event referencing it in the same
    // transaction. `gen_random_uuid()` would be wrong twice over — v4, and generated by
    // the database — and a default is the kind of convenience that quietly becomes the
    // way rows are made.
    expect(code).toMatch(/person_ref\s+uuid\s+not null,/);
    expect(code).not.toMatch(/person_ref[^,]*default/i);
    expect(code).not.toMatch(/gen_random_uuid|uuid_generate/i);
  });

  it("lets an identity exist without an auth user", () => {
    // Not a formality. A NOT NULL here would mean losing authentication is losing
    // identity, which is exactly what §11.4 refuses.
    expect(code).toMatch(/auth_user_id\s+uuid,/);
    expect(code).not.toMatch(/auth_user_id\s+uuid\s+not null/i);
  });

  it("refuses an erasure that left personal data behind", () => {
    // The constraint exists because the failure is invisible and unlawful rather than
    // merely wrong: a redaction that missed a column looks like an ordinary sparse row.
    expect(code).toMatch(/identities_erasure_is_complete/);
    for (const field of ["full_name", "avatar_url", "city", "email", "phone"]) {
      expect(
        code.slice(code.indexOf("identities_erasure_is_complete")),
        `${field} is not covered by the erasure constraint`
      ).toMatch(new RegExp(`${field} is null`));
    }
  });

  it("grants UPDATE and withholds DELETE", () => {
    // Mutable in its attributes (§8), so it opts in by name per ROLES.md §3 rule 2 — this
    // platform's default is append-only and grants only SELECT and INSERT.
    //
    // DELETE is withheld from everyone because §8 says an identity is "ended only by
    // erasure, never by inactivity" and §11.4 makes erasure a redaction. There is no
    // correct reason for a row to leave this table.
    expect(code).toMatch(/grant update on identity\.identities to klussie_engine_identity/i);
    expect(code).not.toMatch(/grant[^;]*\bdelete\b/is);
  });

  it("enables RLS and defines no policy yet", () => {
    // §24 item 5 enables it everywhere. The policy that lets a person read their own row
    // belongs with WP 02.06, where reading starts — until then the absent policy is the
    // deny.
    expect(code).toMatch(/alter table identity\.identities enable row level security/i);
    expect(code).not.toMatch(/create policy/i);
  });

  it("grants the client-facing roles nothing", () => {
    for (const role of ["anon", "authenticated", "service_role"]) {
      expect(code).not.toMatch(new RegExp(`\\bgrant\\b[^;]*\\bto\\s+[^;]*\\b${role}\\b`, "is"));
    }
  });

  it("keeps personal data in one place and touches nothing existing", () => {
    // The epic is a migration, not a rewrite: `public.profiles` keeps working and keeps
    // being written until step 6 retires it, which is not in this epic.
    expect(code).not.toMatch(/\bpublic\./i);
    expect(code).not.toMatch(/\balter table public\b/i);
  });

  it("is re-runnable", () => {
    expect(code).toMatch(/create table if not exists identity\.identities/);
  });
});
