// Keeps 0030_workspace.sql inside the shape DATABASE_ARCHITECTURE.md §9 and §10 require,
// and inside the one rule every migration after Epic 02 inherits (SUPABASE_ARCHITECTURE.md
// §5, §11.4): no foreign key from a durable record to identity, because the person
// reference must survive erasure and a foreign key would make that impossible or cascade
// destruction into history. This is the first migration since identity.identities itself
// (0025) to carry a person reference, so it is the first place that rule can be broken by
// someone reaching for the "obviously correct" `references identity.identities`.
//
// Structural, like every migration test in this repository (docs/engineering/TESTING.md
// §3: there is no database in this harness). Behaviour is proven against staging by
// VERIFY_WORKSPACE.sql, recorded in the work package.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";

const MIGRATION = "supabase/migrations/0030_workspace.sql";

// Comments stripped, for the same reason as identity.test.js: this migration's own column
// comments use words like "references", "foreign key" and "delete" in prose explaining why
// those things are absent, and a test over the raw text would fail on the explanation
// rather than the code.
const codeNoComments = readFileSync(MIGRATION, "utf8")
  .split("\n")
  .filter((line) => !line.trimStart().startsWith("--"))
  .join("\n");

// String literals additionally stripped, for checks that only need structure (column
// names, grants, table names) and would otherwise risk matching prose inside a `comment on
// ... is '...'` body. Checks that need to read an actual literal value — the membership
// states, for instance — use codeNoComments instead, since stripping string literals
// destroys exactly the value being inspected.
const code = codeNoComments.replace(/'(?:[^']|'')*'/g, "''");

describe("0030_workspace migration", () => {
  it("creates exactly the three tables the epic names, guardedly", () => {
    const created = [
      ...code.matchAll(/create table if not exists (workspace\.\w+)/gi),
    ].map((m) => m[1]);

    expect(created.sort()).toEqual([
      "workspace.membership_history",
      "workspace.memberships",
      "workspace.workspaces",
    ]);
  });

  it("declares no foreign key from memberships or history to identity, in either direction", () => {
    // The exact defect this test exists to catch: `person_ref uuid not null references
    // identity.identities (person_ref)` reads as obviously correct and breaks erasure.
    expect(code).not.toMatch(/references\s+identity\./i);
  });

  it("gives every person reference no database default and no foreign key", () => {
    const personRefLines = [...code.matchAll(/person_ref\s+uuid\s+not null,?/gi)];
    expect(personRefLines.length).toBeGreaterThanOrEqual(2); // memberships and membership_history
    expect(code).not.toMatch(/person_ref[^,]*default/i);
    expect(code).not.toMatch(/person_ref[^,]*references/i);
  });

  it("gives every primary key no database default — UUIDv7 is application-generated", () => {
    // SUPABASE_ARCHITECTURE.md §3, and the same reasoning as identity.identities: a
    // database default would produce a v4, generated by the database, contradicting both
    // halves of the rule.
    expect(code).not.toMatch(/id\s+uuid\s+not null[^,]*default/i);
    expect(code).not.toMatch(/gen_random_uuid|uuid_generate/i);
  });

  it("references workspaces from memberships and history, and memberships from history", () => {
    // Unlike identity, workspace IS a safe foreign-key target: it is archived, never
    // deleted (§9), so a plain reference with no ON DELETE clause cannot cascade destruction
    // — the property that ruled out referencing identity at all.
    expect(code).toMatch(/workspace_id\s+uuid\s+not null\s+references workspace\.workspaces \(id\)/i);
    expect(code).toMatch(/membership_id\s+uuid\s+not null\s+references workspace\.memberships \(id\)/i);
  });

  it("names the four membership states verbatim from the domain model", () => {
    // PLATFORM_DOMAIN_MODEL.md §7: "a state (invited, active, suspended, ended)." Read from
    // codeNoComments, not the string-literal-stripped code — the values under test are
    // string literals, and stripping them would leave nothing to assert on.
    const stateChecks = [...codeNoComments.matchAll(/check \(state in \(([^)]+)\)\)/gi)];
    expect(stateChecks.length).toBeGreaterThanOrEqual(2); // memberships and membership_history
    for (const m of stateChecks) {
      const values = m[1].split(",").map((v) => v.trim().replace(/'/g, ""));
      expect(values.sort()).toEqual(["active", "ended", "invited", "suspended"]);
    }
  });

  it("declares no check constraint enumerating role names", () => {
    // ADR-0026 and this migration's own comment: role vocabulary differs per workspace
    // type and is not closed (future custom roles, §7 "how it evolves"). Unlike state,
    // there is deliberately no `check (role in (...))`.
    expect(code).not.toMatch(/check\s*\(\s*role\s+in\b/i);
  });

  it("grants UPDATE on the two mutable tables and withholds DELETE everywhere", () => {
    // Mutable class (§4): workspaces and memberships change in place. Append-only class:
    // membership_history does not, and gets no such grant.
    expect(code).toMatch(/grant update on workspace\.workspaces to klussie_engine_workspace/i);
    expect(code).toMatch(/grant update on workspace\.memberships to klussie_engine_workspace/i);
    expect(code).not.toMatch(/grant update on workspace\.membership_history/i);
    expect(code).not.toMatch(/grant[^;]*\bdelete\b/is);
  });

  it("enforces membership_history as append-only with a guard trigger", () => {
    // The same pattern as platform.audit_records (migration 0022): withheld privileges
    // plus a guard trigger, because they fail differently.
    expect(code).toMatch(/before update or delete on workspace\.membership_history/i);
    expect(code).toMatch(/membership_history_reject_mutation/i);
  });

  it("enables RLS on all three tables and defines no policy yet", () => {
    // The membership helper that would let a policy answer "who may read this" is
    // WP 03.02, one migration away. Until then the absent policy is the deny.
    for (const table of ["workspaces", "memberships", "membership_history"]) {
      expect(code).toMatch(
        new RegExp(`alter table workspace\\.${table} enable row level security`, "i")
      );
    }
    expect(code).not.toMatch(/create policy/i);
  });

  it("grants the client-facing roles nothing", () => {
    for (const role of ["anon", "authenticated", "service_role"]) {
      expect(code).not.toMatch(new RegExp(`\\bgrant\\b[^;]*\\bto\\s+[^;]*\\b${role}\\b`, "is"));
    }
    expect(code).toMatch(/revoke all on workspace\.workspaces from anon, authenticated, service_role/i);
    expect(code).toMatch(/revoke all on workspace\.memberships from anon, authenticated, service_role/i);
    expect(code).toMatch(/revoke all on workspace\.membership_history from anon, authenticated, service_role/i);
  });

  it("touches nothing in public", () => {
    expect(code).not.toMatch(/\bpublic\./i);
    expect(code).not.toMatch(/\balter table public\b/i);
  });

  it("is re-runnable — every table created guardedly", () => {
    const allCreations = [...code.matchAll(/create table/gi)];
    const guardedCreations = [...code.matchAll(/create table if not exists/gi)];
    expect(allCreations).toHaveLength(guardedCreations.length);
  });

  it("declares no uniqueness constraint on (person_ref, workspace_id)", () => {
    // Deliberate: a person may hold a second membership after leaving one. Deciding how
    // re-joining works belongs to whichever engine implements invitations, not this
    // structural migration.
    expect(code).not.toMatch(/unique\s*\([^)]*person_ref[^)]*workspace_id[^)]*\)/i);
    expect(code).not.toMatch(/unique\s*\([^)]*workspace_id[^)]*person_ref[^)]*\)/i);
  });
});
