-- Verifies the dual-write in 0027_identity_dual_write.sql.
--
--   psql -w -h <pooler-host> -p 5432 -U postgres.<project-ref> -d postgres \
--        -v ON_ERROR_STOP=1 -f supabase/diagnostics/VERIFY_IDENTITY_DUAL_WRITE.sql
--
-- Every check inserts into `auth.users` and rolls back. That is deliberate and is what
-- makes this file worth more than the ones before it: inserting an auth user fires
-- `on_auth_user_created`, so these exercise **the real production path** — the same
-- trigger, in the same transaction, that runs when a person signs up — rather than a copy
-- of it. Nothing persists.
--
-- Safe against staging. Do NOT run against production: it writes to auth.users, and a
-- rollback that failed would leave a synthetic account behind.

\set ON_ERROR_STOP on

-- =========================================================================
-- 1 · A signup creates exactly one identity, in the same transaction
--
-- The application's own signups carry a person_ref generated by src/lib/ids.ts and passed
-- through the signup metadata, which is what §3 means by application-generated.

begin;

insert into auth.users (id, instance_id, aud, role, email, raw_user_meta_data, created_at, updated_at)
values (
  '01920000-0000-4000-8000-00000000e001',
  '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
  'dualwrite-app@example.test',
  '{"full_name":"App Signup","person_ref":"01920000-0000-7000-8000-00000000e0a1"}'::jsonb,
  now(), now()
);

do $$
declare
  v_identities bigint;
  v_row identity.identities;
begin
  select count(*) into v_identities from identity.identities
  where auth_user_id = '01920000-0000-4000-8000-00000000e001';

  if v_identities <> 1 then
    raise exception 'One signup produced % identities, expected exactly 1', v_identities;
  end if;

  select * into v_row from identity.identities
  where auth_user_id = '01920000-0000-4000-8000-00000000e001';

  -- The application's identifier was used, not a freshly minted one. If this fails, the
  -- generator in src/lib/ids.ts is decorative and the database is really in charge.
  if v_row.person_ref <> '01920000-0000-7000-8000-00000000e0a1' then
    raise exception
      'The person reference the application generated was discarded; got %', v_row.person_ref;
  end if;

  if v_row.full_name <> 'App Signup' or v_row.email <> 'dualwrite-app@example.test' then
    raise exception 'Signup attributes did not reach the identity row';
  end if;

  -- The profile still exists and is still authoritative. Step 3 adds a write; it does not
  -- move one.
  if not exists (select 1 from public.profiles where id = '01920000-0000-4000-8000-00000000e001') then
    raise exception 'The profile was not created — the existing behaviour changed';
  end if;
  if not exists (select 1 from public.profile_contacts where profile_id = '01920000-0000-4000-8000-00000000e001') then
    raise exception 'The contact row was not created — the existing behaviour changed';
  end if;

  raise notice '1 · one signup produced one identity, carrying the application''s own reference';
end;
$$;

rollback;

-- =========================================================================
-- 2 · A signup the application did not make still produces exactly one identity
--
-- The Supabase dashboard's "Add user", the admin API, and OAuth once a provider is
-- configured. None of them can carry metadata this application wrote, so the trigger
-- mints — ADR-0022's case of an identifier for a row the application did not create.

begin;

insert into auth.users (id, instance_id, aud, role, email, raw_user_meta_data, created_at, updated_at)
values (
  '01920000-0000-4000-8000-00000000e002',
  '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
  'dualwrite-external@example.test', '{}'::jsonb, now(), now()
);

do $$
declare
  v_row identity.identities;
begin
  select * into v_row from identity.identities
  where auth_user_id = '01920000-0000-4000-8000-00000000e002';

  if v_row.person_ref is null then
    raise exception 'A user created outside the application got no identity';
  end if;

  -- Minted, and minted correctly: version 7 in the 13th hex digit.
  if pg_catalog.substr(v_row.person_ref::text, 15, 1) <> '7' then
    raise exception 'The minted person reference is not a UUIDv7: %', v_row.person_ref;
  end if;

  raise notice '2 · a user created outside the application got exactly one identity, minted as v7';
end;
$$;

rollback;

-- =========================================================================
-- 3 · A malformed reference from a client falls back rather than failing the signup
--
-- A client sending nonsense is a defect worth finding. Failing a person's signup over it
-- is not the way to find it, and would be a behaviour change this package promised not to
-- make.

begin;

insert into auth.users (id, instance_id, aud, role, email, raw_user_meta_data, created_at, updated_at)
values (
  '01920000-0000-4000-8000-00000000e003',
  '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
  'dualwrite-garbage@example.test',
  '{"person_ref":"not-a-uuid-at-all"}'::jsonb, now(), now()
);

do $$
declare
  v_row identity.identities;
begin
  select * into v_row from identity.identities
  where auth_user_id = '01920000-0000-4000-8000-00000000e003';

  if v_row.person_ref is null then
    raise exception 'A malformed person_ref cost the user their identity';
  end if;
  if pg_catalog.substr(v_row.person_ref::text, 15, 1) <> '7' then
    raise exception 'The fallback did not mint a v7';
  end if;

  raise notice '3 · a malformed reference fell back to a minted one, and the signup survived';
end;
$$;

rollback;

-- =========================================================================
-- 4 · Profile updates never change the person reference
--
-- Twice, and with different attributes each time, because "it did not change" is only
-- interesting after something has actually tried to change it.

begin;

insert into auth.users (id, instance_id, aud, role, email, raw_user_meta_data, created_at, updated_at)
values (
  '01920000-0000-4000-8000-00000000e004',
  '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
  'dualwrite-updates@example.test',
  '{"full_name":"Before","person_ref":"01920000-0000-7000-8000-00000000e0a4"}'::jsonb,
  now(), now()
);

do $$
declare
  v_original uuid;
  v_after_first uuid;
  v_after_second uuid;
  v_row identity.identities;
  v_count bigint;
begin
  select person_ref into v_original from identity.identities
  where auth_user_id = '01920000-0000-4000-8000-00000000e004';

  -- What updateProfile() does.
  update public.profiles set full_name = 'After One', city = 'Brussels'
  where id = '01920000-0000-4000-8000-00000000e004';

  select person_ref into v_after_first from identity.identities
  where auth_user_id = '01920000-0000-4000-8000-00000000e004';

  update public.profiles set full_name = 'After Two', locale = 'fr'
  where id = '01920000-0000-4000-8000-00000000e004';

  select * into v_row from identity.identities
  where auth_user_id = '01920000-0000-4000-8000-00000000e004';
  v_after_second := v_row.person_ref;

  if v_original is distinct from v_after_first or v_original is distinct from v_after_second then
    raise exception
      'The person reference changed across profile updates: % then % then %',
      v_original, v_after_first, v_after_second;
  end if;

  -- The attributes did follow, which is what makes this a dual-write rather than an
  -- orphaned row.
  if v_row.full_name <> 'After Two' or v_row.city <> 'Brussels' or v_row.locale <> 'fr' then
    raise exception 'Profile attributes did not reach the identity: %, %, %',
      v_row.full_name, v_row.city, v_row.locale;
  end if;

  -- And no second identity appeared along the way.
  select count(*) into v_count from identity.identities
  where auth_user_id = '01920000-0000-4000-8000-00000000e004';
  if v_count <> 1 then
    raise exception 'Profile updates produced % identities', v_count;
  end if;

  raise notice '4 · two profile updates carried attributes across and left the reference untouched';
end;
$$;

rollback;

-- =========================================================================
-- 5 · An update that changes nothing mirrored does not touch the identity
--
-- markRoleSelected() writes only `onboarding_role_selected`. Without the trigger's WHEN
-- clause that would bump the identity's updated_at, and WP 02.05's reconciliation would
-- read it as attributes having drifted.

begin;

insert into auth.users (id, instance_id, aud, role, email, raw_user_meta_data, created_at, updated_at)
values (
  '01920000-0000-4000-8000-00000000e005',
  '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
  'dualwrite-flag@example.test', '{"full_name":"Flag"}'::jsonb, now(), now()
);

do $$
declare
  v_before timestamptz;
  v_after timestamptz;
begin
  select updated_at into v_before from identity.identities
  where auth_user_id = '01920000-0000-4000-8000-00000000e005';

  update public.profiles set onboarding_role_selected = true
  where id = '01920000-0000-4000-8000-00000000e005';

  select updated_at into v_after from identity.identities
  where auth_user_id = '01920000-0000-4000-8000-00000000e005';

  if v_before is distinct from v_after then
    raise exception 'An unrelated profile flag touched the identity row';
  end if;

  raise notice '5 · an update to application state left the identity alone';
end;
$$;

rollback;

-- =========================================================================
-- 6 · A profile update for an erased person does not resurrect their data
--
-- The guard that has to exist before WP 02.07 adds erasure. Without it the mirror writes
-- the name back, identities_erasure_is_complete rejects the row, and the rejection fails
-- the caller's profile update — erasure becoming a bug in somebody else's screen.

begin;

insert into auth.users (id, instance_id, aud, role, email, raw_user_meta_data, created_at, updated_at)
values (
  '01920000-0000-4000-8000-00000000e006',
  '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
  'dualwrite-erased@example.test', '{"full_name":"To Be Erased"}'::jsonb, now(), now()
);

do $$
declare
  v_row identity.identities;
begin
  -- Erasure as WP 02.07 will perform it: redact, keep the reference.
  update identity.identities
  set full_name = null, avatar_url = null, city = null, email = null, phone = null,
      erased_at = now()
  where auth_user_id = '01920000-0000-4000-8000-00000000e006';

  -- The profile still exists and can still be edited — by an admin, by a stale client, by
  -- anything that has not caught up.
  update public.profiles set full_name = 'Resurrected', city = 'Ghent'
  where id = '01920000-0000-4000-8000-00000000e006';

  select * into v_row from identity.identities
  where auth_user_id = '01920000-0000-4000-8000-00000000e006';

  if v_row.full_name is not null or v_row.city is not null then
    raise exception 'A profile update wrote personal data back onto an erased identity';
  end if;
  if v_row.erased_at is null then
    raise exception 'The erasure marker was cleared by a profile update';
  end if;

  raise notice '6 · a profile update for an erased person changed nothing, and did not fail';
end;
$$;

rollback;

-- =========================================================================
-- 7 · A failed signup leaves no orphan identity
--
-- The property that makes this a transaction rather than three hopeful writes. The failure
-- is injected after the trigger has run, which is the only interesting moment: the
-- identity exists, and then the transaction does not.

do $$
declare
  v_orphans bigint;
begin
  begin
    insert into auth.users (id, instance_id, aud, role, email, raw_user_meta_data, created_at, updated_at)
    values (
      '01920000-0000-4000-8000-00000000e007',
      '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
      'dualwrite-doomed@example.test', '{"full_name":"Doomed"}'::jsonb, now(), now()
    );

    -- Something later in the same transaction fails, as a constraint or a concurrent
    -- change would.
    raise exception 'injected failure';
  exception when others then
    null;
  end;

  select count(*) into v_orphans from identity.identities
  where auth_user_id = '01920000-0000-4000-8000-00000000e007';
  if v_orphans <> 0 then
    raise exception 'A failed signup left % orphan identity row(s)', v_orphans;
  end if;

  -- And the other two are gone with it, which is the consistency being claimed.
  if exists (select 1 from public.profiles where id = '01920000-0000-4000-8000-00000000e007') then
    raise exception 'A failed signup left an orphan profile';
  end if;
  if exists (select 1 from auth.users where id = '01920000-0000-4000-8000-00000000e007') then
    raise exception 'A failed signup left an orphan auth user';
  end if;

  raise notice '7 · a failed signup left no auth user, no profile and no identity';
end;
$$;

-- =========================================================================
-- 8 · Nothing was left behind
--
-- Seven transactions, all rolled back. This environment must look exactly as it did.

do $$
declare
  v_left bigint;
begin
  select count(*) into v_left from identity.identities
  where auth_user_id::text like '01920000-0000-4000-8000-00000000e%';
  if v_left > 0 then
    raise exception 'The verification left % identity row(s) behind', v_left;
  end if;

  select count(*) into v_left from auth.users
  where email like 'dualwrite-%@example.test';
  if v_left > 0 then
    raise exception 'The verification left % auth user(s) behind', v_left;
  end if;

  raise notice '8 · no synthetic auth users or identities remain';
end;
$$;

-- =========================================================================

do $$
begin
  raise notice 'VERIFY_IDENTITY_DUAL_WRITE: all checks passed';
end;
$$;
